export default dataObj = [
    {
        typeOfScreen: '3',
        correctAnswers: ['Mia', 'går', 'sakte', 'i', 'parken.', 'Hun', 'ser', 'ofte', 'på', 'blomstene', 'og', 'lytter', 'alltid', 'til', 'fuglene.', 'I', 'dag', 'finner', 'hun', 'en', 'katt', 'som', 'spinner', 'rolig', 'ved', 'et', 'tre.'],
        wordsWithGaps: ['Mia', '            ', 'sakte', 'i', 'parken.', 'Hun', 'ser', '            ', 'på', 'blomstene', 'og', '            ', 'alltid', 'til', 'fuglene.', 'I', 'dag', 'finner', 'hun', 'en', 'katt', 'som', 'spinner', '            ', 'ved', 'et', 'tre.', '!!!', 'lytter', 'rolig', 'går', 'ofte'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Petter', 'jobber', 'vanligvis', 'i', 'en', 'butikk', 'men', 'idag', 'er', 'han', 'syk.', 'Han', 'ligger', 'stille', 'i', 'sengen', 'og', 'ser', 'på', 'TV.', 'Han', 'drikker', 'te', 'og', 'håper', 'å', 'føle', 'seg', 'bedre', 'snart.', 'Utenfor', 'snør', 'det', 'rolig', 'og', 'barna', 'leker', 'lykkelig', 'i', 'snøen.'],
        wordsWithGaps: ['Petter', 'jobber', '            ', 'i', 'en', 'butikk', 'men', 'idag', 'er', 'han', 'syk.', 'Han', 'ligger', '            ', 'i', 'sengen', 'og', 'ser', 'på', 'TV.', 'Han', 'drikker', 'te', 'og', 'håper', 'å', 'føle', 'seg', '            ', 'snart.', 'Utenfor', 'snør', 'det', 'rolig', 'og', 'barna', 'leker', '            ', 'i', 'snøen.', '!!!', 'bedre', 'stille', 'vanligvis', 'lykkelig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Lars', 'står', 'tidlig', 'opp', 'hver', 'morgen', 'og', 'spiser', 'fort', 'frokost.', 'Han', 'jobber', 'hardt', 'på', 'kontoret', 'og', 'kommer', 'sent', 'hjem.', 'Om', 'kvelden', 'leker', 'han', 'ofte', 'med', 'sin', 'hund', 'og', 'leser', 'stille', 'før', 'han', 'sover.'],
        wordsWithGaps: ['Lars', 'står', '            ', 'opp', 'hver', 'morgen', 'og', 'spiser', 'fort', 'frokost.', 'Han', 'jobber', '            ', 'på', 'kontoret', 'og', 'kommer', '            ', 'hjem.', 'Om', 'kvelden', 'leker', 'han', '            ', 'med', 'sin', 'hund', 'og', 'leser', 'stille', 'før', 'han', 'sover.', '!!!', 'sent', 'ofte', 'hardt', 'raskt', 'tidlig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Anna', 'studerer', 'på', 'biblioteket.', 'Hun', 'snakker', 'sjelden', 'høyt', 'og', 'går', 'alltid', 'forsiktig', 'med', 'bøkene.', 'Hver', 'ettermiddag', 'spaserer', 'hun', 'langsomt', 'hjem', 'og', 'tenker', 'ofte', 'på', 'dagen.', 'Hun', 'sover', 'alltid', 'godt', 'etter', 'en', 'produktiv', 'dag.'],
        wordsWithGaps: ['Anna', 'studerer', 'på', 'biblioteket.', 'Hun', 'snakker', '            ', 'høyt', 'og', 'går', '            ', 'forsiktig', 'med', 'bøkene.', 'Hver', 'ettermiddag', 'spaserer', 'hun', '            ', 'hjem', 'og', 'tenker', 'ofte', 'på', 'dagen.', 'Hun', 'sover', 'alltid', 'godt', 'etter', 'en', '            ', 'dag.', '!!!', 'produktiv', 'sjelden', 'langsomt', 'alltid',],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Ole', 'går', 'vanligvis', 'til', 'skolen', 'men', 'idag', 'sykler', 'han', 'raskt', 'fordi', 'han', 'våknet', 'sent', '.', 'På', 'skolen', 'svarer', 'han', 'alltid', 'nøye', 'på', 'lærerens', 'spørsmål.', 'Etter', 'skolen', 'spiller', 'han', 'fotball', 'med', 'vennene', 'sine.', 'Hjemme', 'hjelper', 'han', 'gjerne','med', 'middagen.'],
        wordsWithGaps: ['Ole', 'går', '            ', 'til', 'skolen', 'men', 'idag', 'sykler', 'han', '            ', 'fordi', 'han', 'våknet', '            ', '.', 'På', 'skolen', 'svarer', 'han', 'alltid', '            ', 'på', 'lærerens', 'spørsmål.', 'Etter', 'skolen', 'spiller', 'han', 'fotball', 'med', 'vennene', 'sine.', 'Hjemme', 'hjelper', 'han', '            ', 'med', 'middagen.', '!!!', 'sent', 'gjerne', 'raskt', 'vanligvis', 'nøye'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Kari', 'leser', 'stille', 'på', 'biblioteket.', 'Hun', 'skriver', 'alltid', 'nøye', 'notater.', 'Etter', 'timene', 'snakker', 'hun', 'ofte', 'med', 'vennene', 'sine', 'om', 'lekser.', 'Hun', 'går', 'raskt', 'hjem', 'og', 'spiser', 'middag', 'tidlig', 'med', 'familien', 'sin.'],
        wordsWithGaps: ['Kari', 'leser', 'stille', 'på', 'biblioteket.', 'Hun', 'skriver', 'alltid', '            ', 'notater.', 'Etter', 'timene', 'snakker', 'hun', '            ', 'med', 'vennene', 'sine', 'om', 'lekser.', 'Hun', 'går', '            ', 'hjem', 'og', 'spiser', 'middag', '            ', 'med', 'familien', 'sin.', '!!!', 'ofte', 'nøye', 'tidlig', 'raskt'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Magnus', 'spiser', 'frokost', 'på', 'kjøkkenet', 'hver', 'morgen.', 'I', 'dag', 'går', 'han', 'til', 'jobben', 'under', 'den', 'klare', 'himmelen.', 'Han', 'jobber', 'effektivt', 'og', 'fullfører', 'oppgavene', 'før', 'lunsj.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'på', 'en', 'kafé', 'i', 'byen.', 'De', 'diskuterer', 'ofte', 'politikk', 'og', 'sport', '.'],
        wordsWithGaps: ['Magnus', 'spiser', 'frokost', 'på', 'kjøkkenet', '            ', 'morgen.', 'I', 'dag', 'går', 'han', 'til', 'jobben', '            ', 'den', 'klare', 'himmelen.', 'Han', 'jobber', '            ', 'og', 'fullfører', 'oppgavene', '            ', 'lunsj.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'på', 'en', 'kafé', 'i', 'byen.', 'De', 'diskuterer', '            ', 'politikk', 'og', 'sport', '.', '!!!', 'sjelden', 'hver', 'før', 'ofte', 'effektivt', 'under'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Lars', 'bor', 'i', 'en', 'liten', 'by', 'ved', 'havet.', 'Hver', 'morgen', 'ser', 'han', 'den', 'fantastiske', 'soloppgangen', 'mens', 'han', 'drikker', 'sin', 'kaffe.', 'Han', 'jobber', 'som', 'fisker', 'og', 'drar', 'tidlig', 'ut', 'med', 'sin', 'gamle', 'båt.', 'På', 'kveldene', 'går', 'han', 'ofte', 'lange', 'turer', 'langs', 'den', 'sanddekte', 'stranden.'],
        wordsWithGaps: ['Lars', 'bor', 'i', 'en', 'liten', 'by', '            ', 'havet.', 'Hver', 'morgen', 'ser', 'han', 'den', 'fantastiske', 'soloppgangen', '            ', 'han', 'drikker', 'sin', 'kaffe.', 'Han', 'jobber', 'som', 'fisker', 'og', 'drar', '            ', 'ut', 'med', 'sin', '            ', 'båt.', 'På', 'kveldene', 'går', 'han', 'ofte', '            ', 'turer', 'langs', 'den', 'sanddekte', 'stranden.', '!!!',  'gamle', 'mens', 'ved', 'lange', 'tidlig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    }
];