export default dataObj = [
    {
        nor: 'å bo',
        eng: 'to live',
        pl: 'mieszkać',
        ar: 'أن يعيش',
        ger: 'wohnen',
        lt: 'gyventi',
        ua: 'жити', 
        sp: 'vivir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbo.mp3?alt=media&token=d06c822d-5c69-4dae-aa35-82a2477c2e7c',
      },
      {
        nor: 'å stå',
        eng: 'to stand',
        pl: 'stać',
        ar: 'يقف',
        ger: 'stehen',
        lt: 'stovėti',
        ua: 'стояти', 
        sp: 'estar de pie',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstaa.mp3?alt=media&token=3f7552fe-a9b0-43ab-9269-577674275a2c',
      },
      {
        nor: 'å sitte',
        eng: 'to sit',
        pl: 'siedzieć',
        ar: 'جلس',
        ger: 'sitzen',
        lt: 'sėdėti',
        ua: 'сидіти', 
        sp: 'sentarse',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsitte.mp3?alt=media&token=0f05cab9-248b-4a5b-9626-b538c71d31af',
      },
      {
        nor: 'å få',
        eng: 'to get',
        pl: 'dostać',
        ar: 'الحصول على',
        ger: 'bekommen',
        lt: 'gauti',
        ua: 'отримати',
        sp: 'obtener',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffaa.mp3?alt=media&token=e975bbf1-d4ff-43d8-bb89-5218805b69b5',
      },
      {
        nor: 'å ville',
        eng: 'to want',
        pl: 'chcieć',
        ar: 'يريد',
        ger: 'wollen',
        lt: 'norėti',
        ua: 'хотіти',
        sp: 'querer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fville.mp3?alt=media&token=68914219-53ff-45ac-a103-b7b5c01a1ad2',
      },
      {
        nor: 'å kunne',
        eng: 'to be able',
        pl: 'móc',
        ar: 'يستطيع',
        ger: 'können',
        lt: 'galėti',
        ua: 'могти',
        sp: 'poder',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkunne.mp3?alt=media&token=cbc28c39-0a78-46a2-b1ca-072b363a4e9f',
      },
      {
        nor: 'å måtte',
        eng: 'to have to',
        pl: 'musieć',
        ar: 'يجب أن',
        ger: 'müssen',
        lt: 'turėti',
        ua: 'мати',
        sp: 'tener que',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaatte.mp3?alt=media&token=02f2a784-2710-44ff-9eeb-46c1b851df58',
      },
      {
        nor: 'å reise',
        eng: 'to travel',
        pl: 'podróżować',
        ar: 'السفر',
        ger: 'reisen',
        lt: 'keliauti',
        ua: 'подорожувати',
        sp: 'viajar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freise.mp3?alt=media&token=c2a0e50a-1e12-44af-853d-54eb9943f575',
    },
    {
        nor: 'å lytte',
        eng: 'to listen',
        pl: 'słuchać',
        ar: 'يستمع',
        ger: 'zuhören',
        lt: 'klausytis',
        ua: 'слухати',
        sp: 'escuchar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flytte.mp3?alt=media&token=be3d123d-ddd5-4013-9f6b-d70d5178ac64',
    },
    {
        nor: 'å lære',
        eng: 'to learn',
        pl: 'uczyć się',
        ar: 'تعلم',
        ger: 'lernen',
        lt: 'mokytis',
        ua: 'вчитися',
        sp: 'aprender',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleere.mp3?alt=media&token=febdecc0-e9d4-440c-8f48-ea54f8942dbb',
    },
    {
        nor: 'å se',
        eng: 'to see',
        pl: 'zobaczyć',
        ar: 'أنظر',
        ger: 'sehen',
        lt: 'matyti',
        ua: 'дивитися',
        sp: 'ver',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fse.mp3?alt=media&token=8b1dfd13-b9df-4854-9deb-bed4f03872c9',
    },
    {
        nor: 'å spise',
        eng: 'to eat',
        pl: 'jeść',
        ar: 'يأكل',
        ger: 'essen',
        lt: 'valgyti',
        ua: 'їсти',
        sp: 'comer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspise.mp3?alt=media&token=94f0d894-ea58-461c-a006-acde95933f20',
    },
    {
      nor: 'å legge',
      eng: 'to put',
      pl: 'kłaść',
      ar: 'وضع',
      ger: 'legen',
      lt: 'dėti',
      ua: 'класти',
      sp: 'poner',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flegge.mp3?alt=media&token=269e98ed-6417-453f-aefe-1c5c7af0c617',
    },
    {
      nor: 'å arbeide',
      eng: 'to work',
      pl: 'pracować',
      ar: 'العمل',
      ger: 'arbeiten',
      lt: 'dirbti',
      ua: 'працювати',
      sp: 'trabajar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farbeide.mp3?alt=media&token=8392cbe4-a500-4810-a39e-bec82adb3d58',
    },
    {
      nor: 'å studere',
      eng: 'to study',
      pl: 'studiować',
      ar: 'يدرس',
      ger: 'studieren',
      lt: 'mokytis',
      ua: 'вчитися',
      sp: 'estudiar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstudere.mp3?alt=media&token=7a3ed484-3cfa-4f51-b425-a391dd8bfeb7',
    },
    {
      nor: 'å le',
      eng: 'to laugh',
      pl: 'śmiać się',
      ar: 'يضحك',
      ger: 'lachen',
      lt: 'juoktis',
      ua: 'сміятися',
      sp: 'reír',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fle.mp3?alt=media&token=921151a7-0b0d-49f1-9b59-42e62020b141',
    },
    {
      nor: 'å gråte',
      eng: 'to cry',
      pl: 'płakać',
      ar: 'يبكي',
      ger: 'weinen',
      lt: 'verkti',
      ua: 'плакати',
      sp: 'llorar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgraate.mp3?alt=media&token=05035171-780d-4f38-a58f-c2d3193e58cc',
    },
    {
      nor: 'å komme',
      eng: 'to come',
      pl: 'przychodzić',
      ar: 'يأتي',
      ger: 'kommen',
      lt: 'ateiti',
      ua: 'приходити',
      sp: 'venir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkomme.mp3?alt=media&token=f8dc22a8-84a8-43bd-9d35-5687491a5250',
    },
    {
      nor: 'å tenke',
      eng: 'to think',
      pl: 'myśleć',
      ar: 'يفكر',
      ger: 'denken',
      lt: 'galvoti',
      ua: 'думати',
      sp: 'pensar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftenke.mp3?alt=media&token=c212e447-1309-4079-8427-3e764d4cfc84',
    },
    {
      nor: 'å kjøpe',
      eng: 'to buy',
      pl: 'kupować',
      ar: 'يشترى',
      ger: 'kaufen',
      lt: 'pirkti',
      ua: 'купувати',
      sp: 'comprar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjoope.mp3?alt=media&token=f3344d5b-7cff-41e2-81ef-85048f014e97',
    },
    {
      nor: 'å kjøre',
      eng: 'to drive',
      pl: 'prowadzić',
      ar: 'يقود',
      ger: 'fahren',
      lt: 'vairuoti',
      ua: 'водити',
      sp: 'conducir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkjoore.mp3?alt=media&token=5cf53e21-e03e-4298-97c4-ad1ca1bae3d8',
    },
    {
      nor: 'å løpe',
      eng: 'to run',
      pl: 'biegać',
      ar: 'يركض',
      ger: 'laufen',
      lt: 'bėgti',
      ua: 'бігти',
      sp: 'correr',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Floope.mp3?alt=media&token=7c6f40c4-347c-49e4-8bf2-644c3833e752',
    },
    {
      nor: 'å hoppe',
      eng: 'to jump',
      pl: 'skakać',
      ar: 'يقفز',
      ger: 'springen',
      lt: 'šokti',
      ua: 'стрибати',
      sp: 'saltar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhoppe.mp3?alt=media&token=3ce26483-25a6-4ccb-b59d-44d45ee36060',
    },
    {
      nor: 'å svømme',
      eng: 'to swim',
      pl: 'pływać',
      ar: 'يسبح',
      ger: 'schwimmen',
      lt: 'plaukti',
      ua: 'плавати',
      sp: 'nadar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvoomme.mp3?alt=media&token=05b4f451-9219-4d7a-92ff-bb4a5c98a7d4',
    },
    {
      nor: 'å danse',
      eng: 'to dance',
      pl: 'tańczyć',
      ar: 'يرقص',
      ger: 'tanzen',
      lt: 'šokti',
      ua: 'танцювати',
      sp: 'bailar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdanse.mp3?alt=media&token=6201b96c-bf31-4b45-bb8d-81f84525074e',
    },
    {
      nor: 'å synge',
      eng: 'to sing',
      pl: 'śpiewać',
      ar: 'يغني',
      ger: 'singen',
      lt: 'dainuoti',
      ua: 'співати',
      sp: 'cantar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsynge.mp3?alt=media&token=84f330d1-1057-4980-8682-729d62f29455',
    },
    {
      nor: 'å spille',
      eng: 'to play',
      pl: 'grać',
      ar: 'يلعب',
      ger: 'spielen',
      lt: 'žaisti',
      ua: 'грати',
      sp: 'jugar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspille.mp3?alt=media&token=c8412b2d-36d5-49e5-bfac-507e9bf923b3',
    },
    {
      nor: 'å selge',
      eng: 'to sell',
      pl: 'sprzedawać',
      ar: 'يبيع',
      ger: 'verkaufen',
      lt: 'parduoti',
      ua: 'продавати',
      sp: 'vender',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselge.mp3?alt=media&token=fa8254cc-1a1e-4b3d-b4d1-8e3fbd9d85fb',
    },
    {
      nor: 'å møte',
      eng: 'to meet',
      pl: 'spotykać',
      ar: 'يلتقي',
      ger: 'treffen',
      lt: 'susitikti',
      ua: 'зустрічати',
      sp: 'encontrar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmoote.mp3?alt=media&token=8a46d9c3-a836-493d-9860-5c5e387ed988',
    },
    {
      nor: 'å besøke',
      eng: 'to visit',
      pl: 'odwiedzać',
      ar: 'يزور',
      ger: 'besuchen',
      lt: 'aplankyti',
      ua: 'відвідувати',
      sp: 'visitar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbesooke.mp3?alt=media&token=57db6c29-53b0-4b90-b37c-f5b8a7ea1dd7',
    },
    {
      nor: 'å være',
      eng: 'to be',
      pl: 'być',
      ar: 'كان',
      ger: 'sein',
      lt: 'būti',
      ua: 'бути',
      sp: 'ser',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fveere.mp3?alt=media&token=4ad4cd0a-4321-40e3-a422-76f2e2b7efb4',
    },
    {
      nor: 'å ha',
      eng: 'to have',
      pl: 'mieć',
      ar: 'يملك',
      ger: 'haben',
      lt: 'turėti',
      ua: 'мати',
      sp: 'tener',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fha.mp3?alt=media&token=6fe73f1e-6074-4c0c-ad9b-655a3c8fac70',
    },
    {
      nor: 'å jobbe',
      eng: 'to work',
      pl: 'pracować',
      ar: 'يعمل',
      ger: 'arbeiten',
      lt: 'dirbti',
      ua: 'працювати',
      sp: 'trabajar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjobbe.mp3?alt=media&token=ab2880a4-698c-4e45-a2ba-a3177a5a52a0',
    },
    {
      nor: 'å snakke',
      eng: 'to talk',
      pl: 'rozmawiać',
      ar: 'يتحدث',
      ger: 'sprechen',
      lt: 'kalbėti',
      ua: 'говорити',
      sp: 'hablar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsnakke.mp3?alt=media&token=f782e4b1-e87c-47a6-a3bc-574315421a2a',
    },
    {
      nor: 'å gjøre',
      eng: 'to do',
      pl: 'robić',
      ar: 'يفعل',
      ger: 'tun',
      lt: 'daryti',
      ua: 'робити',
      sp: 'hacer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgjoore.mp3?alt=media&token=2f6950bb-a431-4afe-9f84-2958da541b43',
    },
    {
      nor: 'å si',
      eng: 'to say',
      pl: 'mówić',
      ar: 'يقول',
      ger: 'sagen',
      lt: 'sakyti',
      ua: 'казати',
      sp: 'decir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsi.mp3?alt=media&token=54d7c707-7615-47e3-ba3f-5ddab6daf7f8',
    },
    {
      nor: 'å gå',
      eng: 'to go',
      pl: 'iść',
      ar: 'يذهب',
      ger: 'gehen',
      lt: 'eiti',
      ua: 'йти',
      sp: 'ir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgaa.mp3?alt=media&token=fba1a90c-60ac-4d0e-a729-97db3c7a1f3b',
    },
    {
      nor: 'å drikke',
      eng: 'to drink',
      pl: 'pić',
      ar: 'يشرب',
      ger: 'trinken',
      lt: 'gerti',
      ua: 'пити',
      sp: 'beber',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdrikke.mp3?alt=media&token=63e8e0d2-c805-48e3-95ff-bb4b58d67d2b',
    },
    {
      nor: 'å lese',
      eng: 'to read',
      pl: 'czytać',
      ar: 'يقرأ',
      ger: 'lesen',
      lt: 'skaityti',
      ua: 'читати',
      sp: 'leer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flese.mp3?alt=media&token=dfd0822b-364a-45c6-aa78-7e4ec2dd6546',
    },
    {
      nor: 'å skrive',
      eng: 'to write',
      pl: 'pisać',
      ar: 'يكتب',
      ger: 'schreiben',
      lt: 'rašyti',
      ua: 'писати',
      sp: 'escribir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskrive.mp3?alt=media&token=086fbd16-cfa1-4e37-ace8-e5f9ae263f4e',
    },
    {
      nor: 'å sove',
      eng: 'to sleep',
      pl: 'spać',
      ar: 'ينام',
      ger: 'schlafen',
      lt: 'miegoti',
      ua: 'спати',
      sp: 'dormir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsove.mp3?alt=media&token=820919d1-9a40-4cd7-b0b3-98cd5120c75f',
    },
    {
      nor: 'å spørre',
      eng: 'to ask',
      pl: 'pytać',
      ar: 'يسأل',
      ger: 'fragen',
      lt: 'klausti',
      ua: 'запитувати',
      sp: 'preguntar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspoorre.mp3?alt=media&token=9425af20-3a4e-4a9c-97a3-8307a4477aa3',
    },
    {
      nor: 'å svare',
      eng: 'to answer',
      pl: 'odpowiadać',
      ar: 'يجيب',
      ger: 'antworten',
      lt: 'atsakyti',
      ua: 'відповідати',
      sp: 'responder',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvare.mp3?alt=media&token=4f2c7adc-3be2-4efa-afd8-ded0149a5a7a',
    },
    {
      nor: 'å åpne',
      eng: 'to open',
      pl: 'otwierać',
      ar: 'يفتح',
      ger: 'öffnen',
      lt: 'atidaryti',
      ua: 'відкривати',
      sp: 'abrir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faapne.mp3?alt=media&token=e4c7c91d-1e98-4d7a-9dbc-39de78fb11e5',
    },
    {
      nor: 'å lukke',
      eng: 'to close',
      pl: 'zamykać',
      ar: 'يغلق',
      ger: 'schließen',
      lt: 'uždaryti',
      ua: 'закривати',
      sp: 'cerrar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukke.mp3?alt=media&token=ed1851f9-8f52-4342-a6aa-ee5bfe6cdc25',
    },
    {
      nor: 'å gi',
      eng: 'to give',
      pl: 'dawać',
      ar: 'يعطي',
      ger: 'geben',
      lt: 'duoti',
      ua: 'давати',
      sp: 'dar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgi.mp3?alt=media&token=11c6e157-1ddc-4e96-b3a0-b4328154a84f',
    },
    {
      nor: 'å ta',
      eng: 'to take',
      pl: 'brać',
      ar: 'يأخذ',
      ger: 'nehmen',
      lt: 'imti',
      ua: 'брати',
      sp: 'tomar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fta.mp3?alt=media&token=7bbe88a2-8c70-43a6-b709-b60e25556b57',
    },
    {
      nor: 'å forstå',
      eng: 'to understand',
      pl: 'rozumieć',
      ar: 'يفهم',
      ger: 'verstehen',
      lt: 'suprasti',
      ua: 'розуміти',
      sp: 'entender',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforstaa.mp3?alt=media&token=df6f43cc-ad2d-41b5-96f4-ec448dd367cd',
    },
    {
      nor: 'å øve',
      eng: 'to practice',
      pl: 'ćwiczyć',
      ar: 'يمارس',
      ger: 'üben',
      lt: 'praktikuotis',
      ua: 'практикуватися',
      sp: 'practicar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foove.mp3?alt=media&token=33df2ade-a7b6-42d0-97c1-81bb5d7c1b15',
    },
    {
      nor: 'å planlegge',
      eng: 'to plan',
      pl: 'planować',
      ar: 'يخطط',
      ger: 'planen',
      lt: 'planuoti',
      ua: 'планувати',
      sp: 'planear',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fplanlegge.mp3?alt=media&token=3d4d3dc9-576c-4705-b76e-757ac23fb50c',
    },
    {
      nor: 'å hilse',
      eng: 'to greet',
      pl: 'witać',
      ar: 'يحيي',
      ger: 'grüßen',
      lt: 'sveikintis',
      ua: 'вітати',
      sp: 'saludar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhilse.mp3?alt=media&token=ab43a3af-a1e3-4b4c-9af7-c16b23affe2a',
    },
    {
      nor: 'å legge seg',
      eng: 'to go to bed',
      pl: 'kłaść się spać',
      ar: 'الذهاب إلى الفراش',
      ger: 'ins Bett gehen',
      lt: 'eiti miegoti',
      ua: 'лягати спати',
      sp: 'acostarse',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleggeseg.mp3?alt=media&token=3a4e6e34-4347-4a63-9954-2b197cd9832d',
    },
    {
      nor: 'å prøve',
      eng: 'to try',
      pl: 'próbować',
      ar: 'يجرب',
      ger: 'versuchen',
      lt: 'bandyti',
      ua: 'спробувати',
      sp: 'intentar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fproove.mp3?alt=media&token=f80d8d1f-c43c-4a7e-a32f-0d03f33e0829',
    },
    {
      nor: 'å huske',
      eng: 'to remember',
      pl: 'pamiętać',
      ar: 'تذكر',
      ger: 'sich erinnern',
      lt: 'atsiminti',
      ua: 'пам’ятати',
      sp: 'recordar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhuske.mp3?alt=media&token=56dcc196-4d87-4d74-a5c2-b87410285c93',
    },
    {
      nor: 'å glemme',
      eng: 'to forget',
      pl: 'zapominać',
      ar: 'ينسى',
      ger: 'vergessen',
      lt: 'pamiršti',
      ua: 'забувати',
      sp: 'olvidar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fglemme.mp3?alt=media&token=14c10b03-7f5e-49f9-8e6c-d13837d3da88',
    },
    {
      nor: 'å lukte',
      eng: 'to smell',
      pl: 'pachnieć',
      ar: 'يشم',
      ger: 'riechen',
      lt: 'uostyti',
      ua: 'пахнути',
      sp: 'oler',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukte.mp3?alt=media&token=03349ab9-8528-4fff-8122-9c8e19a5eabe',
    },
    {
      nor: 'å finne',
      eng: 'to find',
      pl: 'znaleźć',
      ar: 'يجد',
      ger: 'finden',
      lt: 'rasti',
      ua: 'знайти',
      sp: 'encontrar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffinne.mp3?alt=media&token=891f0c90-18e1-4bf6-ad17-bae365f553e2',
    },
    {
      nor: 'å smake',
      eng: 'to taste',
      pl: 'smakować',
      ar: 'يتذوق',
      ger: 'schmecken',
      lt: 'ragauti',
      ua: 'смакувати',
      sp: 'saborear',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmake.mp3?alt=media&token=f7748a02-9b25-46bf-bb34-e7433776cb08',
    },
    {
      nor: 'å tro',
      eng: 'to believe',
      pl: 'wierzyć',
      ar: 'يعتقد',
      ger: 'glauben',
      lt: 'tikėti',
      ua: 'вірити',
      sp: 'creer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftro.mp3?alt=media&token=968c1501-c08b-4800-9c13-2de5e6413020',
    },
    {
      nor: 'å frykte',
      eng: 'to fear',
      pl: 'bać się',
      ar: 'خوف',
      ger: 'fürchten',
      lt: 'bijoti',
      ua: 'боятися',
      sp: 'temer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrykte.mp3?alt=media&token=b961a07c-0576-4050-9831-a4a5717a1e3f',
    },
    {
      nor: 'å håpe',
      eng: 'to hope',
      pl: 'mieć nadzieję',
      ar: 'أمل',
      ger: 'hoffen',
      lt: 'tikėtis',
      ua: 'сподіватися',
      sp: 'esperar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhaape.mp3?alt=media&token=fa0f2597-ee2a-4603-aed5-eb5753d375c8',
    },
    {
      nor: 'å elske',
      eng: 'to love',
      pl: 'kochać',
      ar: 'يحب',
      ger: 'lieben',
      lt: 'mylėti',
      ua: 'любити',
      sp: 'amar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felske.mp3?alt=media&token=18925ad8-60ba-4711-b780-76cf98bc92a1',
    },
    {
      nor: 'å hate',
      eng: 'to hate',
      pl: 'nienawidzić',
      ar: 'يكره',
      ger: 'hassen',
      lt: 'nekęsti',
      ua: 'ненавидіти',
      sp: 'odiar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhate.mp3?alt=media&token=4d9508b9-66cb-4763-861e-044798d9e8c3',
    },
    {
      nor: 'å bære',
      eng: 'to carry',
      pl: 'nosić',
      ar: 'يحمل',
      ger: 'tragen',
      lt: 'nešti',
      ua: 'нести',
      sp: 'llevar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeere.mp3?alt=media&token=7a97ec24-6e28-4614-b963-a2d75c96b082',
    },
    {
      nor: 'å ringe',
      eng: 'to call',
      pl: 'dzwonić',
      ar: 'يتصل',
      ger: 'anrufen',
      lt: 'skambinti',
      ua: 'дзвонити',
      sp: 'llamar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fringe.mp3?alt=media&token=76f5cf71-69e3-408f-8794-feb5215feb64',
    },
    {
      nor: 'å bruke',
      eng: 'to use',
      pl: 'używać',
      ar: 'استعمل',
      ger: 'benutzen',
      lt: 'naudoti',
      ua: 'використовувати',
      sp: 'usar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbruke.mp3?alt=media&token=df8ecc00-cc2b-4444-95f5-5061abe7f073',
    },
    {
      nor: 'å skjære',
      eng: 'to cut',
      pl: 'kroić',
      ar: 'قطع',
      ger: 'schneiden',
      lt: 'pjaustyti',
      ua: 'різати',
      sp: 'cortar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjeere.mp3?alt=media&token=619cdf08-1e84-4bbd-b931-413691dad984',
    },
    {
      nor: 'å føle',
      eng: 'to feel',
      pl: 'czuć',
      ar: 'يشعر',
      ger: 'fühlen',
      lt: 'jausti',
      ua: 'відчувати',
      sp: 'sentir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffoole.mp3?alt=media&token=3de49428-1c0e-466e-9605-2e13e307ddb8',
    },
    {
      nor: 'å holde',
      eng: 'to hold',
      pl: 'trzymać',
      ar: 'يمسك',
      ger: 'halten',
      lt: 'laikyti',
      ua: 'тримати',
      sp: 'mantener',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fholde.mp3?alt=media&token=2e9a3043-9079-41cd-a002-c9f0e7fa3181',
    },
    {
      nor: 'å skrike',
      eng: 'to scream',
      pl: 'krzyczeć',
      ar: 'يصرخ',
      ger: 'schreien',
      lt: 'šaukti',
      ua: 'кричати',
      sp: 'gritar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskrike.mp3?alt=media&token=80f33a9d-bcc2-427e-b868-b8804c82a68f',
    },
    {
      nor: 'å rope',
      eng: 'to shout',
      pl: 'wołać',
      ar: 'يصيح',
      ger: 'rufen',
      lt: 'šaukti',
      ua: 'кликати',
      sp: 'llamar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frope.mp3?alt=media&token=e7d78f3d-4534-4620-a551-7ed9679f6a7a',
    },
    {
      nor: 'å tørste',
      eng: 'to thirst',
      pl: 'pragnąć',
      ar: 'يعطش',
      ger: 'durstig sein',
      lt: 'trokšti',
      ua: 'спрагнутися',
      sp: 'tener sed',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorste.mp3?alt=media&token=77edd996-8638-4117-b4da-a4751f67392c',
    },
    {
      nor: 'å kysse',
      eng: 'to kiss',
      pl: 'całować',
      ar: 'يُقبِّل',
      ger: 'küssen',
      lt: 'bučiuoti',
      ua: 'цілуватися',
      sp: 'besar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkysse.mp3?alt=media&token=a7319234-7906-483a-a73c-7278236d4332',
    },
    {
      nor: 'å sykle',
      eng: 'to cycle',
      pl: 'jeździć na rowerze',
      ar: 'يَركَب الدَرّاجَة',
      ger: 'Rad fahren',
      lt: 'važiuoti dviračiu',
      ua: 'їздити на велосипеді',
      sp: 'andar en bicicleta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykle.mp3?alt=media&token=9167762b-65ef-4e3a-b7be-ac7a777cc4c3',
    },
    {
      nor: 'å varsel',
      eng: 'to warn',
      pl: 'ostrzegać',
      ar: 'يحذر',
      ger: 'warnen',
      lt: 'įspėti',
      ua: 'попередження',
      sp: 'advertir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvarsel.mp3?alt=media&token=ccc0edf3-60ee-4032-a765-37ce7a33973a',
    },
    {
      nor: 'å skjule',
      eng: 'to hide',
      pl: 'ukrywać',
      ar: 'يختبئ',
      ger: 'verstecken',
      lt: 'paslėpti',
      ua: 'ховати',
      sp: 'ocultar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjule.mp3?alt=media&token=1d8654f1-b294-4621-95e0-606a85df61fb',
    },
    {
      nor: 'å puste',
      eng: 'to breathe',
      pl: 'oddychać',
      ar: 'يتنفس',
      ger: 'atmen',
      lt: 'kvėpuoti',
      ua: 'дихати',
      sp: 'respirar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpuste.mp3?alt=media&token=c72a3eb3-a016-4585-90b3-b3727a4643c4',
    },
    {
      nor: 'å smitte',
      eng: 'to infect',
      pl: 'zarażać',
      ar: 'يعدي',
      ger: 'anstecken',
      lt: 'užkrėsti',
      ua: 'заражати',
      sp: 'infectar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmitte.mp3?alt=media&token=6aec707f-8a31-47a6-873b-570c883a4cde',
    },
    {
      nor: 'å leve',
      eng: 'to live',
      pl: 'żyć',
      ar: 'يعيش',
      ger: 'leben',
      lt: 'gyventi',
      ua: 'жити',
      sp: 'vivir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleve.mp3?alt=media&token=c039671d-0012-4080-899c-602d27ea4777',
    },
    {
      nor: 'å beskytte',
      eng: 'to protect',
      pl: 'chronić',
      ar: 'يحمي',
      ger: 'schützen',
      lt: 'apsaugoti',
      ua: 'захищати',
      sp: 'proteger',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeskytte.mp3?alt=media&token=c67c79fa-b979-498c-8b7c-4fd2a1cd6026',
    },
    {
      nor: 'å fly',
      eng: 'to fly',
      pl: 'lecieć',
      ar: 'يطير',
      ger: 'fliegen',
      lt: 'skristi',
      ua: 'літати',
      sp: 'volar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffly.mp3?alt=media&token=cf5367d8-d071-46d2-9bbd-589b44327020',
    },
]