export default dataObj = [
    {
    title: {
        eng: 'Listen & Sort',
        pl: 'Słuchaj i Sortuj',
        ar: 'استمع ورتب',
        ger: 'Hören & Sortieren',
        lt: 'Klausykis ir Rūšiuok',
        ua: 'Слухай і Сортуй', 
        sp: 'Escucha y Ordena',
    },
    description: {
        eng: 'Arrange the words in the right order',
        pl: 'Uporządkuj słowa we właściwej kolejności',
        ar: 'رتب الكلمات بالترتيب الصحيح',
        ger: 'Ordne die Wörter in der richtigen Reihenfolge',
        lt: 'Išdėstyk žodžius teisinga tvarka',
        ua: 'Розташуй слова у правильному порядку', 
        sp: 'Organiza las palabras en el orden correcto',
    },
    link: 'Exc5x1x1',
    key: 1,
    requiresPro: true
    },
    {
    title: {
        eng: 'Tense Mastery',
        pl: 'Opanowanie Czasów',
        ar: 'إتقان الأزمنة',
        ger: 'Zeitenbeherrschung',
        lt: 'Laikų Valdymas',
        ua: 'Володіння Часами', 
        sp: 'Dominio de los Tiempos',
    },
    description: {
        eng: 'Grasp the essence of all tenses',
        pl: 'Pojmij istotę wszystkich czasów',
        ar: 'استوعب جوهر جميع الأزمنة',
        ger: 'Erfasse das Wesen aller Zeitformen',
        lt: 'Suvaldykite visų laikų esmę',
        ua: 'Освойте суть усіх часів', 
        sp: 'Capta la esencia de todos los tiempos verbales',
    },
    link: 'Exc5x2x1',
    key: 2,
    requiresPro: true
   },
    {
    title: {
        eng: 'Passive Voice',
        pl: 'Strona Bierna',
        ar: 'الصوت السلبي',
        ger: 'Passiv',
        lt: 'Pasiva',
        ua: 'Пасивний Стан', 
        sp: 'Voz Pasiva',
    },
    description: {
        eng: 'Unlock the subtleties of passive construction',
        pl: 'Odkryj subtelności konstrukcji biernej',
        ar: 'استكشف دقائق البناء السلبي',
        ger: 'Erschließe die Feinheiten der Passivkonstruktion',
        lt: 'Atskleisk pasyviosios konstrukcijos subtilybes',
        ua: 'Розкрийте тонкощі пасивної конструкції', 
        sp: 'Desbloquea las sutilezas de la construcción pasiva',
    },
    link: 'Exc5x3x1',
    key: 3,
    requiresPro: true
   },
    {
    title: {
        eng: 'Conditionals',
        pl: 'Tryby Warunkowe',
        ar: 'الشرطية',
        ger: 'Konditionalsätze',
        lt: 'Būtiniai Sąlygotiniai',
        ua: 'Умовні Способи', 
        sp: 'Condicionales',
    },
    description: {
        eng: 'Understanding conditionals and their outcomes',
        pl: 'Zrozumienie trybów warunkowych i ich skutków',
        ar: 'فهم الشروط ونتائجها',
        ger: 'Verstehen von Konditionalen und ihren Ergebnissen',
        lt: 'Sąlygotinių būdų ir jų rezultatų supratimas',
        ua: 'Розуміння умовних способів та їх наслідків', 
        sp: 'Entender los condicionales y sus resultados',
    },
    link: 'Exc5x4x1',
    key: 4,
    requiresPro: true
   },
    {
    title: {
        eng: 'Indirect Speech',
        pl: 'Mowa Zależna',
        ar: 'الكلام غير المباشر',
        ger: 'Indirekte Rede',
        lt: 'Netiesioginė Kalba',
        ua: 'Непряма Мова', 
        sp: 'Discurso Indirecto',
    },
    description: {
        eng: 'Master the art of reported speech',
        pl: 'Opanuj sztukę mowy zależnej',
        ar: 'اتقن فن الخطاب المُبلغ عنه',
        ger: 'Meistere die Kunst der indirekten Rede',
        lt: 'Įvaldykite netiesioginės kalbos meną',
        ua: 'Освойте мистецтво непрямої мови', 
        sp: 'Domina el arte del discurso reportado',
    },
    link: 'Exc5x5x1',
    key: 5,
    requiresPro: true
   },
   {
    title: {
        eng: 'Total Knowledge Test',
        pl: 'Test Całkowitej Wiedzy',
        ar: 'اختبار المعرفة الشامل',
        ger: 'Gesamtwissenstest',
        lt: 'Visapusiškas Žinių Testas',
        ua: 'Тест на Загальні Знання', 
        sp: 'Prueba de Conocimiento Total',
    },
    description: {
        eng: 'Check your understanding across all areas',
        pl: 'Sprawdź swoje zrozumienie we wszystkich dziedzinach',
        ar: 'تحقق من فهمك في جميع المجالات',
        ger: 'Überprüfe dein Verständnis in allen Bereichen',
        lt: 'Patikrink savo supratimą visose srityse',
        ua: 'Перевір своє розуміння у всіх аспектах', 
        sp: 'Comprueba tu entendimiento en todas las áreas',
    },
    link: 'Exc5x6x1',
    key: 6,
    requiresPro: true
   },
];