export default dataObj = [
    {
    title: {
        eng: 'Sentence Sorting',
        pl: 'Sortowanie Zdań',
        ar: 'ترتيب الجمل',
        ger: 'Satzsortierung',
        lt: 'Sakinių Rūšiavimas',
        ua: 'Сортування Речень', 
        sp: 'Ordenación de Frases',
    },
    description: {
        eng: 'Listen and reconstruct the order',
        pl: 'Słuchaj i odtwarzaj kolejność',
        ar: 'استمع وأعد ترتيب الكلمات',
        ger: 'Hören und die Reihenfolge rekonstruieren',
        lt: 'Klausyk ir atkurk eilę',
        ua: 'Слухайте та відновлюйте порядок', 
        sp: 'Escucha y reconstruye el orden',
    },
    link: 'Exc3x1x1',
    key: 1,
    requiresPro: true
    },
    {
    title: {
        eng: 'Past Tense',
        pl: 'Czas Przeszły',
        ar: 'الزمن الماضي',
        ger: 'Vergangenheit',
        lt: 'Būtasis Laikas',
        ua: 'Минулий Час', 
        sp: 'Tiempo Pasado',
    },
    description: {
        eng: 'Journey through time, master the past',
        pl: 'Podróż przez czas, opanuj przeszłość',
        ar: 'رحلة عبر الزمن، أتقن الماضي',
        ger: 'Reise durch die Zeit, meistere die Vergangenheit',
        lt: 'Kelionė per laiką, įvaldyk praeitį',
        ua: 'Подорож у часі, оволодій минулим', 
        sp: 'Viaje a través del tiempo, domina el pasado',
    },
    link: 'Exc3x2x1',
    key: 2,
    requiresPro: true
   },
    {
    title: {
        eng: 'Present Perfect Tense',
        pl: 'Czas Przeszły Dokonany',
        ar: 'زمن المضارع التام',
        ger: 'Perfekt',
        lt: 'Esamasis Tobulinasis Laikas',
        ua: 'Доконаний Теперішній Час', 
        sp: 'Tiempo Pretérito Perfecto',
    },
    description: {
        eng: 'Bridge past and present, refine your skills',
        pl: 'Łącz przeszłość z teraźniejszością, doskonal swoje umiejętności',
        ar: 'جسر بين الماضي والحاضر، صقل مهاراتك',
        ger: 'Brücke zwischen Vergangenheit und Gegenwart, verfeinere deine Fähigkeiten',
        lt: 'Sujunk praeitį ir dabartį, tobulink savo įgūdžius',
        ua: 'Поєднай минуле і теперішнє, вдосконалюй свої навички', 
        sp: 'Une pasado y presente, perfecciona tus habilidades',
    },
    link: 'Exc3x3x1',
    key: 3,
    requiresPro: true
   },
    {
    title: {
        eng: 'Degrees of Comparison',
        pl: 'Stopnie Porównania',
        ar: 'درجات المقارنة',
        ger: 'Vergleichsgrade',
        lt: 'Lyginamoji Laipsnių',
        ua: 'Ступені Порівняння', 
        sp: 'Grados de Comparación',
    },
    description: {
        eng: 'Scale the heights of comparison, enhance your expression',
        pl: 'Zmierz się ze stopniami porównania, wzbogać swoją ekspresję',
        ar: 'تسلق مراتب المقارنة، غنِّ تعبيرك',
        ger: 'Erklimme die Stufen des Vergleichs, bereichere deinen Ausdruck',
        lt: 'Išnagrinėk lyginamuosius laipsnius, praturtink savo išraišką',
        ua: 'Досліджуй ступені порівняння, покращуй свій вираз', 
        sp: 'Escala las alturas de la comparación, enriquece tu expresión',
    },
    link: 'Exc3x4x1',
    key: 4,
    requiresPro: true
   },
    {
    title: {
        eng: 'Grammar Agreement',
        pl: 'Zgoda Gramatyczna',
        ar: 'الاتفاق النحوي',
        ger: 'Grammatikalische Übereinstimmung',
        lt: 'Gramatinė Sutartis',
        ua: 'Граматична Узгодженість', 
        sp: 'Concordancia Gramatical',
    },
    description: {
        eng: 'Harmonize words, perfect your sentences',
        pl: 'Harmonizuj słowa, udoskonal swoje zdania',
        ar: 'انسق الكلمات، كمّل جملك',
        ger: 'Harmonisiere Wörter, perfektioniere deine Sätze',
        lt: 'Derinkite žodžius, tobulinkite savo sakinius',
        ua: 'Гармонізуй слова, удосконалюй свої речення', 
        sp: 'Armoniza las palabras, perfecciona tus oraciones',
    },
    link: 'Exc3x5x1',
    key: 5,
    requiresPro: true
   },
   {
    title: {
        eng: 'Grammar Complete',
        pl: 'Gramatyka Kompletna',
        ar: 'القواعد الكاملة',
        ger: 'Grammatik Komplett',
        lt: 'Visapusiška Gramatika',
        ua: 'Повна Граматика', 
        sp: 'Gramática Completa',
    },
    description: {
        eng: 'Master the full spectrum of grammar',
        pl: 'Opanuj pełne spektrum gramatyki',
        ar: 'اتقن كامل طيف القواعد',
        ger: 'Beherrsche das gesamte Spektrum der Grammatik',
        lt: 'Įvaldyk visą gramatikos spektrą',
        ua: 'Оволодій повним спектром граматики', 
        sp: 'Domina el espectro completo de la gramática',
    },
    link: 'Exc3x6x1',
    key: 6,
    requiresPro: true
   }
];