export default dataObj = [
    {
        title: {
            eng: 'Listening & Sorting',
            pl: 'Słuchanie i Sortowanie',
            ar: 'الاستماع والترتيب',
            ger: 'Hören & Sortieren',
            lt: 'Klausymasis ir Rūšiavimas',
            ua: 'Слухання та Сортування', 
            sp: 'Escuchar y Ordenar',
        },
        description: {
            eng: 'Reconstruct sentences from what you hear',
            pl: 'Odtwórz zdania z tego, co słyszysz',
            ar: 'أعد تشكيل الجمل مما تسمع',
            ger: 'Rekonstruiere Sätze aus dem Gehörten',
            lt: 'Atkurkite sakinius iš to, ką girdite',
            ua: 'Відтворіть речення з того, що чуєте', 
            sp: 'Reconstruye oraciones de lo que escuchas',
        },
        link: 'Exc1x1x1',
        key: 1,
        requiresPro: false
       },
    {
    title: {
        eng: 'Present Tense',
        pl: 'Czas Teraźniejszy',
        ar: 'الزمن الحاضر',
        ger: 'Präsens',
        lt: 'Dabartinis Laikas',
        ua: 'Теперішній Час', 
        sp: 'Tiempo Presente',
    },
    description: {
        eng: 'Unveiling the dynamics of the present',
        pl: 'Odkrywanie dynamiki teraźniejszości',
        ar: 'كشف ديناميكيات الحاضر',
        ger: 'Die Dynamik der Gegenwart enthüllen',
        lt: 'Atskleidžiama dabarties dinamika',
        ua: 'Розкриваємо динаміку теперішнього', 
        sp: 'Desvelando la dinámica del presente',
    },
    link: 'Exc1x2x1',
    key: 2,
    requiresPro: false
   },
    {
    title: {
        eng: 'Adverbs & Adjectives',
        pl: 'Przysłówki i Przymiotniki',
        ar: 'الظروف والصفات',
        ger: 'Adverbien & Adjektive',
        lt: 'Prieveiksmiai ir Būdvardžiai',
        ua: 'Прислівники та Прикметники', 
        sp: 'Adverbios y Adjetivos',
    },
    description: {
        eng: 'Understanding and Using Adverbs & Adjectives',
        pl: 'Rozumienie i używanie przysłówków i przymiotników',
        ar: 'فهم واستخدام الظروف والصفات',
        ger: 'Verstehen und Verwenden von Adverbien und Adjektiven',
        lt: 'Prieveiksmių ir būdvardžių supratimas ir naudojimas',
        ua: 'Розуміння та використання прислівників і прикметників', 
        sp: 'Entender y usar adverbios y adjetivos',
    },
    link: 'Exc1x3x1',
    key: 3,
    requiresPro: false
   },
    {
    title: {
        eng: 'Pronouns',
        pl: 'Zaimki',
        ar: 'الضمائر',
        ger: 'Pronomen',
        lt: 'Įvardžiai',
        ua: 'Займенники', 
        sp: 'Pronombres',
    },
    description: {
        eng: 'Navigating pronoun usage effectively',
        pl: 'Efektywne korzystanie z zaimków',
        ar: 'التنقل الفعّال في استخدام الضمائر',
        ger: 'Effektiver Gebrauch von Pronomen',
        lt: 'Efektyvus įvardžių naudojimas',
        ua: 'Ефективне використання займенників', 
        sp: 'Navegando el uso de pronombres eficazmente',
    },
    link: 'Exc1x4x1',
    key: 4,
    requiresPro: false
   },
    {
    title: {
        eng: 'Sentence Structure',
        pl: 'Struktura Zdania',
        ar: 'بنية الجملة',
        ger: 'Satzstruktur',
        lt: 'Sakinio Struktūra',
        ua: 'Структура Речення', 
        sp: 'Estructura de la Oración',
    },
    description: {
        eng: 'Building sentences with precision',
        pl: 'Budowanie zdań z precyzją',
        ar: 'بناء الجمل بدقة',
        ger: 'Sätze präzise bauen',
        lt: 'Tikslių sakinių kūrimas',
        ua: 'Побудова речень з точністю', 
        sp: 'Construyendo oraciones con precisión',
    },
    link: 'Exc1x5x1',
    key: 5,
    requiresPro: false
   },
   {
    title: {
        eng: 'All-Encompassing Challenge',
        pl: 'Wszechstronne Wyzwanie',
        ar: 'التحدي الشامل',
        ger: 'Umfassende Herausforderung',
        lt: 'Visapusiškas Iššūkis',
        ua: 'Всеосяжний Виклик', 
        sp: 'Desafío Integral',
    },
    description: {
        eng: 'Test your skills across the board',
        pl: 'Przetestuj swoje umiejętności we wszystkich dziedzinach',
        ar: 'اختبر مهاراتك على كافة الأصعدة',
        ger: 'Teste deine Fähigkeiten in allen Bereichen',
        lt: 'Išbandykite savo įgūdžius visapusiškai',
        ua: 'Перевірте свої навички у всіх аспектах', 
        sp: 'Pon a prueba tus habilidades en todos los aspectos',
    },
    link: 'Exc1x6x1',
    key: 6,
    requiresPro: false
   },
//    {
//     title: {
//         eng: 'Test',
//         pl: 'Test',
//         ar: 'الاستماع والترتيب',
//         ger: 'Hören & Sortieren',
//         lt: 'Klausymasis ir Rūšiavimas',
//         ua: 'Слухання та Сортування', 
//         sp: 'Escuchar y Ordenar',
//     },
//     description: {
//         eng: 'Test',
//         pl: 'Test',
//         ar: 'أعد تشكيل الجمل مما تسمع',
//         ger: 'Rekonstruiere Sätze aus dem Gehörten',
//         lt: 'Atkurkite sakinius iš to, ką girdite',
//         ua: 'Відтворіть речення з того, що чуєте', 
//         sp: 'Reconstruye oraciones de lo que escuchas',
//     },
//     link: 'TestingOpeningScreen',
//     key: 7,
//     requiresPro: false
//    },
];