export default dataObj = [
    {
        title: {
            eng: 'Listen & Sort',
            pl: 'Słuchaj i sortuj',
            ar: 'استمع ورتب',
            ger: 'Hören & sortieren',
            lt: 'Klausykis ir rūšiuok',
            ua: 'Слухай і сортуй', 
            sp: 'Escucha y ordena',
        },
        description: {
            eng: 'Arrange the words in the right order',
            pl: 'Uporządkuj słowa we właściwej kolejności',
            ar: 'رتب الكلمات بالترتيب الصحيح',
            ger: 'Ordne die Wörter in der richtigen Reihenfolge',
            lt: 'Išdėstyk žodžius teisinga tvarka',
            ua: 'Розташуй слова у правильному порядку', 
            sp: 'Organiza las palabras en el orden correcto',
        },
        link: 'Exc1x1x1',
        key: 1,
       },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x2x1',
    key: 2,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x3x1',
    key: 3,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x4x1',
    key: 4,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x5x1',
    key: 5,
   },
   {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x6x1',
    key: 6,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x7x1',
    key: 7,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x8x1',
    key: 8,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x9x1',
    key: 9,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    link: 'Exc1x10x1',
    key: 10,
   },
];