export default dataObj = [
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x1x1',
    key: 1,
    },
    {
    title: {
        eng: 'Tense Mastery',
        pl: 'Opanowanie Czasów',
        ar: 'إتقان الأزمنة',
        ger: 'Zeitenbeherrschung',
        lt: 'Laikų Valdymas',
        ua: 'Володіння Часами', 
        sp: 'Dominio de los Tiempos',
    },
    description: {
        eng: 'Grasp the essence of all tenses',
        pl: 'Pojmij istotę wszystkich czasów',
        ar: 'استوعب جوهر جميع الأزمنة',
        ger: 'Erfasse das Wesen aller Zeitformen',
        lt: 'Suvaldykite visų laikų esmę',
        ua: 'Освойте суть усіх часів', 
        sp: 'Capta la esencia de todos los tiempos verbales',
    },
    link: 'Exc1x2x1',
    key: 2,
   },
    {
    title: {
        eng: 'Passive Voice',
        pl: 'Strona Bierna',
        ar: 'الصوت السلبي',
        ger: 'Passiv',
        lt: 'Pasiva',
        ua: 'Пасивний Стан', 
        sp: 'Voz Pasiva',
    },
    description: {
        eng: 'Unlock the subtleties of passive construction',
        pl: 'Odkryj subtelności konstrukcji biernej',
        ar: 'استكشف دقائق البناء السلبي',
        ger: 'Erschließe die Feinheiten der Passivkonstruktion',
        lt: 'Atskleisk pasyviosios konstrukcijos subtilybes',
        ua: 'Розкрийте тонкощі пасивної конструкції', 
        sp: 'Desbloquea las sutilezas de la construcción pasiva',
    },
    link: 'Exc1x3x1',
    key: 3,
   },
    {
    title: {
        eng: 'Conditionals',
        pl: 'Tryby Warunkowe',
        ar: 'الشرطية',
        ger: 'Konditionalsätze',
        lt: 'Būtiniai Sąlygotiniai',
        ua: 'Умовні Способи', 
        sp: 'Condicionales',
    },
    description: {
        eng: 'Understanding conditionals and their outcomes',
        pl: 'Zrozumienie trybów warunkowych i ich skutków',
        ar: 'فهم الشروط ونتائجها',
        ger: 'Verstehen von Konditionalen und ihren Ergebnissen',
        lt: 'Sąlygotinių būdų ir jų rezultatų supratimas',
        ua: 'Розуміння умовних способів та їх наслідків', 
        sp: 'Entender los condicionales y sus resultados',
    },
    link: 'Exc1x4x1',
    key: 4,
   },
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x5x1',
    key: 5,
   },
   {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x6x1',
    key: 6,
   },
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x7x1',
    key: 7,
   },
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x8x1',
    key: 8,
   },
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x9x1',
    key: 9,
   },
    {
    title: {
        eng: 'eng',
        pl: 'pol',
        ar: 'arab',
        ger: 'ger',
        lt: 'lit',
        ua: 'ukr', 
        sp: 'spa',
    },
    description: {
        eng: 'engDesc',
        pl: 'polDesc',
        ar: 'arabDesc',
        ger: 'gerDesc',
        lt: 'litDEsc',
        ua: 'ukrDesc', 
        sp: 'spaDesc',
    },
    link: 'Exc1x10x1',
    key: 10,
   },
];