export default dataObj = [
    {
    title: {
        eng: 'Listen & Sort',
        pl: 'Słuchaj i Sortuj',
        ar: 'استمع ورتب',
        ger: 'Hören & Sortieren',
        lt: 'Klausykis ir Rūšiuok',
        ua: 'Слухай і Сортуй', 
        sp: 'Escucha y Ordena',
    },
    description: {
        eng: 'Arrange the words in the right order',
        pl: 'Uporządkuj słowa we właściwej kolejności',
        ar: 'رتب الكلمات بالترتيب الصحيح',
        ger: 'Ordne die Wörter in der richtigen Reihenfolge',
        lt: 'Išdėstyk žodžius teisinga tvarka',
        ua: 'Розташуй слова у правильному порядку', 
        sp: 'Organiza las palabras en el orden correcto',
    },
    link: 'Exc2x1x1',
    key: 1,
   },
    {
    title: {
        eng: 'Future Tense',
        pl: 'Czas Przyszły',
        ar: 'الزمن المستقبلي',
        ger: 'Futur',
        lt: 'Būsimasis Laikas',
        ua: 'Майбутній Час', 
        sp: 'Futuro',
    },
    description: {
        eng: 'Master future tense today',
        pl: 'Opanuj czas przyszły dziś',
        ar: 'اتقن المستقبل اليوم',
        ger: 'Beherrsche das Futur heute',
        lt: 'Išmok būsimąjį laiką šiandien',
        ua: 'Оволодій майбутнім часом сьогодні', 
        sp: 'Domina el futuro hoy',
    },
    link: 'Exc2x2x1',
    key: 2,
   },
    {
    title: {
        eng: 'Modal Verbs',
        pl: 'Czasowniki Modalne',
        ar: 'الأفعال المساعدة',
        ger: 'Modale Verben',
        lt: 'Modaliniai Veiksmažodžiai',
        ua: 'Модальні дієслова', 
        sp: 'Verbos Modales',
    },
    description: {
        eng: 'Navigate nuances of modal verbs',
        pl: 'Odkryj niuanse czasowników modalnych',
        ar: 'استكشف دقائق الأفعال المساعدة',
        ger: 'Navigiere durch die Nuancen der Modalverben',
        lt: 'Naršyk modalinių veiksmažodžių niuansus',
        ua: 'Досліджуй нюанси модальних дієслів', 
        sp: 'Navega por las sutilezas de los verbos modales',
    },
    link: 'Exc2x3x1',
    key: 3,
   },
    {
    title: {
        eng: 'Nouns & Prepositions',
        pl: 'Rzeczowniki i Przyimki',
        ar: 'الأسماء والحروف الجر',
        ger: 'Nomen & Präpositionen',
        lt: 'Daiktavardžiai ir Prielinksniai',
        ua: 'Іменники та Прийменники', 
        sp: 'Sustantivos y Preposiciones',
    },
    description: {
        eng: 'Crafting connections, mastering meanings',
        pl: 'Tworzenie połączeń, opanowanie znaczeń',
        ar: 'صياغة العلاقات، إتقان المعاني',
        ger: 'Verbindungen schaffen, Bedeutungen meistern',
        lt: 'Kuriant ryšius, įvaldant reikšmes',
        ua: 'Створення зв\'язків, освоєння значень', 
        sp: 'Creando conexiones, dominando significados',
    },
    link: 'Exc2x4x1',
    key: 4,
   },
    {
    title: {
        eng: 'Adverbs & Adjectives',
        pl: 'Przysłówki i Przymiotniki',
        ar: 'الظروف والصفات',
        ger: 'Adverbien & Adjektive',
        lt: 'Prieveiksmiai ir Būdvardžiai',
        ua: 'Прислівники та Прикметники', 
        sp: 'Adverbios y Adjetivos',
    },
    description: {
        eng: 'Fine-tune your descriptions',
        pl: 'Dopracuj swoje opisy',
        ar: 'صقل وصفك',
        ger: 'Feinabstimme deine Beschreibungen',
        lt: 'Sudėkite savo aprašymus',
        ua: 'Вдоскональ свої описи', 
        sp: 'Afina tus descripciones',
    },
    link: 'Exc2x5x1',
    key: 5,
   },
   {
    title: {
        eng: 'Grammar Mastery',
        pl: 'Opanowanie Gramatyki',
        ar: 'إتقان القواعد',
        ger: 'Grammatikbeherrschung',
        lt: 'Gramatikos Meistriškumas',
        ua: 'Володіння Граматикою', 
        sp: 'Dominio de la Gramática',
    },
    description: {
        eng: 'Explore Every Aspect of Grammar',
        pl: 'Zbadaj każdy aspekt gramatyki',
        ar: 'استكشف كل جانب من جوانب القواعد',
        ger: 'Erkunde jeden Aspekt der Grammatik',
        lt: 'Tyrinėkite kiekvieną gramatikos aspektą',
        ua: 'Досліджуйте кожен аспект граматики', 
        sp: 'Explora cada aspecto de la gramática',
    },
    link: 'Exc2x6x1',
    key: 6,
   }
];