export default dataObj = [

    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Hun ', 'en bok.'],             
            ['Vi ', 'på skolen.'],           
            ['Han ', 'norsk.'],              
            ['Barna ', 'i parken.'],        
        ],
        correctAnswers: [['leser'], ['lærer'], ['snakker'], ['leker']],
        translations: {
            eng: ['reads', 'learn', 'speaks', 'play'],
            pl: ['czyta', 'uczą się', 'mówi', 'bawią się'],
            ar: ['تقرأ', 'يتعلمون', 'يتحدث', 'يلعبون'],
            ger: ['liest', 'lernen', 'spricht', 'spielen'],
            lt: ['skaito', 'mokosi', 'kalba', 'žaidžia'],
            ua: ['читає', 'вчаться', 'говорить', 'грають'],
            sp: ['lee', 'aprenden', 'habla', 'juegan'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Katten ', 'melk.'],         
            ['De ', 'i butikken.'],      
            ['Jeg ', 'til musikk.'],      
            ['Bilen ', 'raskt.'],   
        ],
        correctAnswers: [['drikker'], ['jobber'], ['lytter'], ['kjører']],
        translations: {
            eng: ['drinks', 'work', 'listen', 'drives'],
            pl: ['pije', 'pracują', 'słucha', 'jedzie'],
            ar: ['يشرب', 'يعملون', 'يستمع', 'يقود'],
            ger: ['trinkt', 'arbeiten', 'hört', 'fährt'],
            lt: ['geria', 'dirba', 'klauso', 'važiuoja'],
            ua: ['п’є', 'працюють', 'слухає', 'їде'],
            sp: ['bebe', 'trabajan', 'escucha', 'conduce'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Fuglene ', 'tidlig.'],        
            ['Hun ', 'en bok.'],             
            ['Barna ', 'på skolen.'],    
            ['Vi ', 'middag nå.'],         
        ],
        correctAnswers: [['synger'], ['leser'], ['leker'], ['lager']],
        translations: {
            eng: ['sing', 'read', 'play', 'make'],
            pl: ['śpiewają', 'czyta', 'bawią się', 'robią'],
            ar: ['يغنون', 'تقرأ', 'يلعبون', 'يصنعون'],
            ger: ['singen', 'liest', 'spielen', 'machen'],
            lt: ['dainuoja', 'skaito', 'žaidžia', 'ruošia'],
            ua: ['співають', 'читає', 'грають', 'готують'],
            sp: ['cantan', 'lee', 'juegan', 'hacen'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Jeg ', 'i Oslo.'],           
            ['Du ', 'norsk.'],             
            ['Hunden ', 'maten.'],         
            ['Læreren ', 'i klasserommet.'], 
        ],
        correctAnswers: [['bor'], ['snakker', 'prater'], ['spiser'], ['underviser']],
        translations: {
            eng: ['live', 'speak', 'eats', 'teaches'],
            pl: ['mieszka', 'mówi', 'je', 'uczy'],
            ar: ['يعيش', 'يتحدث', 'يأكل', 'يعلم'],
            ger: ['wohnt', 'spricht', 'isst', 'unterrichtet'],
            lt: ['gyvena', 'kalba', 'valgo', 'moko'],
            ua: ['живе', 'говорить', 'їсть', 'вчить'],
            sp: ['vive', 'habla', 'come', 'enseña'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Barnet ', 'med lekene.'],           
            ['Han ', 'på datamaskinen.'],        
            ['Vi ', 'på musikken.'],          
            ['Hun ', 'på treningsstudioet.'],  
        ],
        correctAnswers: [['leker'], ['jobber'], ['hører'], ['trener']],
        translations: {
            eng: ['plays', 'works', 'listens', 'exercises'],
            pl: ['bawi się', 'pracuje', 'słucha', 'ćwiczy'],
            ar: ['يلعب', 'يعمل', 'يستمع', 'يتمرن'],
            ger: ['spielt', 'arbeitet', 'hört zu', 'trainiert'],
            lt: ['žaidžia', 'dirba', 'klauso', 'treniruojasi'],
            ua: ['грається', 'працює', 'слухає', 'тренується'],
            sp: ['juega', 'trabaja', 'escucha', 'ejercita'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    }
    
];