export default dataObj = [
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description',
    link: 'Exc1x1x1',
    key: 1,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 2',
    link: 'Exc1x2x1',
    key: 2,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 3',
    link: 'Exc1x3x1',
    key: 3,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 4',
    link: 'Exc1x4x1',
    key: 4,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 5',
    link: 'Exc1x5x1',
    key: 5,
   },
   {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description',
    link: 'Exc1x6x1',
    key: 6,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 2',
    link: 'Exc1x7x1',
    key: 7,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 3',
    link: 'Exc1x8x1',
    key: 8,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'here is some description 4',
    link: 'Exc1x9x1',
    key: 9,
   },
    {
    title: {
        eng: 'eng title',
        pl: 'polskie tytul',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
    },
    description: 'Type 9 exe',
    link: 'Exc1x10x1',
    key: 10,
   },
];