export default dataObj = [
    {
        nor: 'å anerkjenne',
        eng: 'to acknowledge',
        pl: 'uznać',
        ar: 'الاعتراف',
        ger: 'anerkennen',
        lt: 'pripažinti',
        ua: 'визнавати',
        sp: 'reconocer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fanerkjenne.mp3?alt=media&token=7226adb7-4fe5-4bfc-ba21-a434600f7d35',
      },
      {
        nor: 'å antyde',
        eng: 'to imply',
        pl: 'sugerować',
        ar: 'يلمح',
        ger: 'andeuten',
        lt: 'užsiminti',
        ua: 'натякати',
        sp: 'insinuar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fantyde.mp3?alt=media&token=ada47b0f-fdb8-45b0-9bd0-939c21ef179e',
      },
      {
        nor: 'å avsløre',
        eng: 'to reveal',
        pl: 'ujawnić',
        ar: 'كشف',
        ger: 'aufdecken',
        lt: 'atskleisti',
        ua: 'розкривати',
        sp: 'revelar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Favsloore.mp3?alt=media&token=86bebc24-7f60-4c23-b6c7-9b36481e8bbb',
      },
      {
        nor: 'å generalisere',
        eng: 'to generalize',
        pl: 'generalizować',
        ar: 'تعميم',
        ger: 'verallgemeinern',
        lt: 'generalizuoti',
        ua: 'загальнувати',
        sp: 'generalizar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgeneralisere.mp3?alt=media&token=9acf71c8-4989-4dfd-98eb-7d6e663d7bc6',
      },
      {
        nor: 'å kompensere',
        eng: 'to compensate',
        pl: 'rekompensować',
        ar: 'تعويض',
        ger: 'kompensieren',
        lt: 'kompensuoti',
        ua: 'компенсувати',
        sp: 'compensar',
        soundLink: "https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkompensere.mp3?alt=media&token=11f2fe7d-07d2-4023-9406-b13cdccbdfae",
      },
      {
        nor: 'å bekrefte',
        eng: 'to confirm',
        pl: 'potwierdzić',
        ar: 'أكد',
        ger: 'bestätigen',
        lt: 'patvirtinti',
        ua: 'підтверджувати',
        sp: 'confirmar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbekrefte.mp3?alt=media&token=49dfc6e7-a624-4f09-8fc5-5e1aa609ac58',
      },
      {
        nor: 'å benekte',
        eng: 'to deny',
        pl: 'zaprzeczyć',
        ar: 'أنكر',
        ger: 'leugnen',
        lt: 'neigti',
        ua: 'заперечувати',
        sp: 'negar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbenekte.mp3?alt=media&token=0a72df72-4c07-4cfe-a453-5c0c57b65638',
      },
      {
        nor: 'å betvile',
        eng: 'to doubt',
        pl: 'wątpić',
        ar: 'شك',
        ger: 'bezweifeln',
        lt: 'abejoti',
        ua: 'сумніватися',
        sp: 'dudar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbetvile.mp3?alt=media&token=e41c78fa-766f-4f76-bdfd-c29c22cba045',
      },
      {
        nor: 'å dedikere',
        eng: 'to dedicate',
        pl: 'poświęcić',
        ar: 'كرّس',
        ger: 'widmen',
        lt: 'dedikuoti',
        ua: 'присвячувати',
        sp: 'dedicar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdedikere.mp3?alt=media&token=f394b66f-2cea-4910-8100-cc2f8085a699',
      },
      {
        nor: 'å fordype seg',
        eng: 'to immerse oneself',
        pl: 'zanurzyć się',
        ar: 'ينغمس',
        ger: 'sich vertiefen',
        lt: 'pasinerti',
        ua: 'занурюватися',
        sp: 'profundizar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffordypeseg.mp3?alt=media&token=577ec90d-7040-473c-92f8-199f7e9f80ab',
      },
      {
        nor: 'å motvirke',
        eng: 'to counteract',
        pl: 'przeciwdziałać',
        ar: 'عكس',
        ger: 'entgegenwirken',
        lt: 'priešgynimas',
        ua: 'протидіяти',
        sp: 'contrarrestar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmotvirke.mp3?alt=media&token=9427005d-3751-4b8a-bc39-ebf58c840cd5',
      },
      {
        nor: 'å omskrive',
        eng: 'to rewrite',
        pl: 'przepisać',
        ar: 'إعادة كتابة',
        ger: 'umschreiben',
        lt: 'perrašyti',
        ua: 'переписувати',
        sp: 'reescribir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fomskrive.mp3?alt=media&token=808952c1-4274-4523-a1d2-3dd80733266c',
      },
      {
        nor: 'å simulere',
        eng: 'to simulate',
        pl: 'symulować',
        ar: 'محاكاة',
        ger: 'simulieren',
        lt: 'simuliuoti',
        ua: 'симулювати',
        sp: 'simular',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsimulere.mp3?alt=media&token=e43dcdb3-3d25-4f26-8539-da735bc22653',
      },
      {
        nor: 'å spesifisere',
        eng: 'to specify',
        pl: 'określić',
        ar: 'تحديد',
        ger: 'spezifizieren',
        lt: 'nurodyti',
        ua: 'специфікувати',
        sp: 'especificar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspesifisere.mp3?alt=media&token=1e867e75-065d-486c-94ee-b85f80a0d53c',
      },
      {
        nor: 'å utforske',
        eng: 'to explore',
        pl: 'badać',
        ar: 'للاستكشاف',
        ger: 'erkunden',
        lt: 'tirti',
        ua: 'досліджувати',
        sp: 'explorar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futforske.mp3?alt=media&token=1da26c13-ae73-4b67-96f5-8de53364a5d1',
      },
      {
        nor: 'å beundre',
        eng: 'to admire',
        pl: 'podziwiać',
        ar: 'يعجب',
        ger: 'bewundern',
        lt: 'grožėtis',
        ua: 'захоплюватися',
        sp: 'admirar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeundre.mp3?alt=media&token=e22c749c-5215-4fb6-86c4-262ec5422098',
      },
      {
        nor: 'å gjenkjenne',
        eng: 'to recognize',
        pl: 'rozpoznać',
        ar: 'الاعتراف',
        ger: 'erkennen',
        lt: 'atpažinti',
        ua: 'впізнавати',
        sp: 'reconocer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgjenkjenne.mp3?alt=media&token=143bd69a-4800-4843-b458-7dcf01f5e7b2',
      },
      {
        nor: 'å gjenvinne',
        eng: 'to recover',
        pl: 'odzyskać',
        ar: 'استعادة',
        ger: 'wiederherstellen',
        lt: 'atgauti',
        ua: 'відновлювати',
        sp: 'recuperar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgjenvinne.mp3?alt=media&token=12ea4582-31b5-4025-9c79-e4e5c678cd22',
      },
      {
        nor: 'å implementere',
        eng: 'to implement',
        pl: 'wdrażać',
        ar: 'تنفيذ',
        ger: 'implementieren',
        lt: 'įgyvendinti',
        ua: 'впроваджувати',
        sp: 'implementar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fimplementere.mp3?alt=media&token=b6b39f9b-a414-4ddf-a31a-91389c1e9797',
      },
      {
        nor: 'å kritisere',
        eng: 'to criticize',
        pl: 'krytykować',
        ar: 'ينتقد',
        ger: 'kritisieren',
        lt: 'kritikuoti',
        ua: 'критикувати',
        sp: 'criticar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkritisere.mp3?alt=media&token=d1bef51b-3e7f-4018-ac16-1c125c930371',
      },
      {
        nor: 'å modifisere',
        eng: 'to modify',
        pl: 'modyfikować',
        ar: 'تعديل',
        ger: 'modifizieren',
        lt: 'modifikuoti',
        ua: 'модифікувати',
        sp: 'modificar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmodifisere.mp3?alt=media&token=237ed40a-70f8-44c5-9900-c5d117a175b3',
      },
      {
        nor: 'å overbevise',
        eng: 'to convince',
        pl: 'przekonać',
        ar: 'إقناع',
        ger: 'überzeugen',
        lt: 'įtikinti',
        ua: 'переконувати',
        sp: 'convencer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverbevise.mp3?alt=media&token=729df11d-d2fd-4e18-9f76-e4ffa1dd72a7',
      },
      {
        nor: 'å tilegne seg',
        eng: 'to acquire',
        pl: 'nabywać',
        ar: 'اكتساب',
        ger: 'erwerben',
        lt: 'įgyti',
        ua: 'освоювати',
        sp: 'adquirir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftilegneseg.mp3?alt=media&token=78840303-c8aa-4da2-ac07-a161fa62674b',
      },
      {
        nor: 'å sammenfatte',
        eng: 'to summarize',
        pl: 'podsumować',
        ar: 'لخص',
        ger: 'zusammenfassen',
        lt: 'apibendrinti',
        ua: 'підбивати підсумки',
        sp: 'resumir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsammenfatte.mp3?alt=media&token=1c7bf5a0-d5ed-4ca0-a4cf-831583c70905',
      },
      {
        nor: 'å grine',
        eng: 'to laugh',
        pl: 'śmiać się',
        ar: 'يضحك',
        ger: 'lachen',
        lt: 'juoktis',
        ua: 'сміятися',
        sp: 'reír',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrine.mp3?alt=media&token=573d6bd8-58c9-4f69-b11d-f8f9f6ae7d70',
      },
      {
        nor: 'å adaptere',
        eng: 'to adapt',
        pl: 'dostosować',
        ar: 'يتأقلم',
        ger: 'anpassen',
        lt: 'pritaikyti',
        ua: 'адаптувати',
        sp: 'adaptar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fadaptere.mp3?alt=media&token=3edf3b5b-c105-4716-a8b6-7c6617432a8a',
      },
      {
        nor: 'å integrere',
        eng: 'to integrate',
        pl: 'zintegrować',
        ar: 'يدمج',
        ger: 'integrieren',
        lt: 'integruoti',
        ua: 'інтегрувати',
        sp: 'integrar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fintegrere.mp3?alt=media&token=47b2cc4d-327d-4989-97d8-ee00b1a5d732',
      },
      {
        nor: 'å evaluere',
        eng: 'to evaluate',
        pl: 'oceniać',
        ar: 'تقييم',
        ger: 'bewerten',
        lt: 'vertinti',
        ua: 'оцінювати',
        sp: 'evaluar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fevaluere.mp3?alt=media&token=ed841c78-ee81-4e0c-87aa-c461f7c171c1',
      },
      {
        nor: 'å undergrave',
        eng: 'to undermine',
        pl: 'podważać',
        ar: 'تقويض',
        ger: 'untergraben',
        lt: 'kelti abejones',
        ua: 'підривати',
        sp: 'socavar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fundergrave.mp3?alt=media&token=7ae65861-0ac3-4405-933a-2be88fbc12f9',
      },
      {
        nor: 'å approbere',
        eng: 'to approve',
        pl: 'zatwierdzać',
        ar: 'يوافق',
        ger: 'zustimmen',
        lt: 'patvirtinti',
        ua: 'схвалювати',
        sp: 'aprobar',
        soundLink: "https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fapprobere.mp3?alt=media&token=0c0d3365-6d44-442c-9a64-33349f2d6937",
      },
      {
        nor: 'å arbitrere',
        eng: 'to arbitrate',
        pl: 'arbitrażować',
        ar: 'يحكم',
        ger: 'schlichten',
        lt: 'arbitruoti',
        ua: 'арбітрувати',
        sp: 'arbitrar',
        soundLink: "https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farbitrere.mp3?alt=media&token=f5b8d331-3914-4dd9-86ff-c1f0c2bcbe87",
      },
      {
        nor: 'å dekonstruere',
        eng: 'to deconstruct',
        pl: 'dekonstruować',
        ar: 'تفكيك',
        ger: 'dekonstruieren',
        lt: 'dekonstruoti',
        ua: 'деконструювати',
        sp: 'deconstruir',
        soundLink: "https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdekonstruere.mp3?alt=media&token=c6ff8f33-7088-4e93-8edc-7998632da30e",
      },
      {
        nor: 'å engasjere',
        eng: 'to engage',
        pl: 'angażować',
        ar: 'انخرط',
        ger: 'engagieren',
        lt: 'įtraukti',
        ua: 'залучати',
        sp: 'comprometer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fengasjere.mp3?alt=media&token=d36e3439-27f6-4b1c-b5db-32bbc2c4aeb8',
      },
      {
        nor: 'å omskolere',
        eng: 'to retrain',
        pl: 'przeszkolić',
        ar: 'إعادة تدريب',
        ger: 'umschulen',
        lt: 'perkvalifikuoti',
        ua: 'переосвіта',
        sp: 'recapacitar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fomskolere.mp3?alt=media&token=4b4e87b3-8f8a-4e24-a168-75f563d642b8',
      },
      {
        nor: 'å vekke',
        eng: 'to awaken',
        pl: 'obudzić',
        ar: 'أيقظ',
        ger: 'erwecken',
        lt: 'pažadinti',
        ua: 'будити',
        sp: 'despertar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvekke.mp3?alt=media&token=79b66ac7-3b13-4574-8023-2cd68bbdaed1',
      },
      {
        nor: 'å sammensmelte',
        eng: 'to merge',
        pl: 'połączyć',
        ar: 'دمج',
        ger: 'verschmelzen',
        lt: 'sujungti',
        ua: 'злиття',
        sp: 'fusionar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsammensmelte.mp3?alt=media&token=3dcf3ea3-faec-44ef-a57e-aa04a7312ffa',
      },
      {
        nor: 'å differensiere',
        eng: 'to differentiate',
        pl: 'rozróżnić',
        ar: 'ميّز',
        ger: 'differenzieren',
        lt: 'diferencijuoti',
        ua: 'диференціювати',
        sp: 'diferenciar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdifferensiere.mp3?alt=media&token=21740b35-1bb1-41fc-8c8d-6b76b092ca4f',
      },
      {
        nor: 'å ødelegge',
        eng: 'to destroy',
        pl: 'zniszczyć',
        ar: 'دمر',
        ger: 'zerstören',
        lt: 'sugriauti',
        ua: 'знищувати',
        sp: 'destruir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foodelegge.mp3?alt=media&token=bdd0e345-75bd-4d5b-bf65-422ca700f525',
      },
      {
        nor: 'å erverve',
        eng: 'to acquire',
        pl: 'nabyć',
        ar: 'اكتساب',
        ger: 'erwerben',
        lt: 'įsigyti',
        ua: 'набувати',
        sp: 'adquirir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ferverve.mp3?alt=media&token=ce2a8d7f-7010-40e0-b11e-43de5187f03c',
      },
      {
        nor: 'å redegjøre',
        eng: 'to explain',
        pl: 'wyjaśnić',
        ar: 'شرح',
        ger: 'erklären',
        lt: 'paaiškinti',
        ua: 'пояснити',
        sp: 'explicar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fredegjoore.mp3?alt=media&token=cff5e19a-f1e1-4efd-92ec-fbdb441c9b4d',
      },
      {
        nor: 'å samhandle',
        eng: 'to interact',
        pl: 'współdziałać',
        ar: 'تفاعل',
        ger: 'interagieren',
        lt: 'bendrauti',
        ua: 'взаємодіяти',
        sp: 'interactuar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsamhandle.mp3?alt=media&token=9d230d78-e5ab-499d-ab84-deb062eb9aea',
      },
      {
        nor: 'å skille',
        eng: 'to separate',
        pl: 'separować',
        ar: 'فصل',
        ger: 'trennen',
        lt: 'atskirti',
        ua: 'відокремлювати',
        sp: 'separar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskille.mp3?alt=media&token=3eb4f93e-cbfe-4513-8b3a-c5e1cf05c8e9',
      },
      {
        nor: 'å resonere',
        eng: 'to resonate',
        pl: 'rezonować',
        ar: 'يتردد',
        ger: 'resonieren',
        lt: 'rezonuoti',
        ua: 'резонувати',
        sp: 'razonar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fresonere.mp3?alt=media&token=83ea8b37-20e3-450d-bc2f-c060a51ea8f3',
      },
      {
        nor: 'å diversifisere',
        eng: 'to diversify',
        pl: 'dywersyfikować',
        ar: 'تنوع',
        ger: 'diversifizieren',
        lt: 'diversifikuoti',
        ua: 'диверсифікувати',
        sp: 'diversificar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdiversifisere.mp3?alt=media&token=91f91211-838b-4197-823f-9811af477eb2',
      },
      {
        nor: 'å reevaluere',
        eng: 'to reevaluate',
        pl: 'przeocenić',
        ar: 'إعادة التقييم',
        ger: 'neu bewerten',
        lt: 'pervertinti',
        ua: 'переоцінювати',
        sp: 'reevaluar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freevaluere.mp3?alt=media&token=c2b17e19-8f2a-4ae0-b8f8-17cea5c86b1c',
      },
      {
        nor: 'å frigjøre',
        eng: 'to liberate',
        pl: 'uwolnić',
        ar: 'تحرر',
        ger: 'befreien',
        lt: 'išlaisvinti',
        ua: 'звільняти',
        sp: 'liberar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrigjoore.mp3?alt=media&token=6ca11650-d2e3-42db-a037-578841e1b4bf',
      },
      {
        nor: 'å kontemplere',
        eng: 'to contemplate',
        pl: 'kontemplować',
        ar: 'تأمل',
        ger: 'kontemplieren',
        lt: 'kontempliuoti',
        ua: 'контемплювати',
        sp: 'contemplar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkontemplere.mp3?alt=media&token=5f785924-8cfd-41c0-a8ba-f82bf3b3eb36',
      },
      {
        nor: 'å besitte',
        eng: 'to possess',
        pl: 'posiadać',
        ar: 'امتلك',
        ger: 'besitzen',
        lt: 'turėti',
        ua: 'володіти',
        sp: 'poseer',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbesitte.mp3?alt=media&token=76ddaaac-3f1e-4ffe-8361-50fbf65f79ee',
      },
      {
        nor: 'å revidere',
        eng: 'to revise',
        pl: 'zrewidować',
        ar: 'تنقيح',
        ger: 'revidieren',
        lt: 'peržiūrėti',
        ua: 'ревізувати',
        sp: 'revisar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frevidere.mp3?alt=media&token=9b6b8288-81f2-464e-86fb-28dd74569fef',
      },
      {
        nor: 'å synkronisere',
        eng: 'to synchronize',
        pl: 'synchronizować',
        ar: 'مزامنة',
        ger: 'synchronisieren',
        lt: 'sinchronizuoti',
        ua: 'синхронізувати',
        sp: 'sincronizar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsynkronisere.mp3?alt=media&token=ca6d3b4d-f619-4841-baaa-0980513e8703',
      },
      {
        nor: 'å delegere',
        eng: 'to delegate',
        pl: 'delegować',
        ar: 'تفويض',
        ger: 'delegieren',
        lt: 'deleguoti',
        ua: 'делегувати',
        sp: 'delegar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdelegere.mp3?alt=media&token=7e0cf6b9-61d4-4105-a357-5ed3263efc9f',
      },
      {
        nor: 'å eliminere',
        eng: 'to eliminate',
        pl: 'eliminować',
        ar: 'استبعاد',
        ger: 'eliminieren',
        lt: 'eliminuoti',
        ua: 'елімінувати',
        sp: 'eliminar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feliminere.mp3?alt=media&token=3611425a-31b8-4d56-9462-5f5ac690f6ef',
      },
      {
        nor: 'å formulere',
        eng: 'to formulate',
        pl: 'sformułować',
        ar: 'صياغة',
        ger: 'formulieren',
        lt: 'formuluoti',
        ua: 'формулювати',
        sp: 'formular',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fformulere.mp3?alt=media&token=0ba3c5f8-40c5-40aa-9ffa-90051b6e40e0',
      },
      {
        nor: 'å fortolke',
        eng: 'to interpret',
        pl: 'interpretować',
        ar: 'تفسير',
        ger: 'interpretieren',
        lt: 'interpretuoti',
        ua: 'тлумачити',
        sp: 'interpretar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffortolke.mp3?alt=media&token=28c585fa-38f8-4236-bd25-b6ce9d05c3e2',
      },
      {
        nor: 'å innovere',
        eng: 'to innovate',
        pl: 'wprowadzać innowacje',
        ar: 'ابتكار',
        ger: 'innovieren',
        lt: 'inovuoti',
        ua: 'інновувати',
        sp: 'innovar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finnovere.mp3?alt=media&token=b2d1f5d8-6d6c-45b9-ae19-40b0fa53f754',
      },
      {
        nor: 'å verdsette',
        eng: 'to appreciate',
        pl: 'cenić',
        ar: 'قدر',
        ger: 'schätzen',
        lt: 'įvertinti',
        ua: 'цінувати',
        sp: 'valorar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fverdsette.mp3?alt=media&token=99e51d00-f392-4748-a673-9f12be74743b',
      },
      {
        nor: 'å betrakte',
        eng: 'to consider',
        pl: 'rozważać',
        ar: 'أعتبر',
        ger: 'betrachten',
        lt: 'laikyti',
        ua: 'розглядати',
        sp: 'considerar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbetrakte.mp3?alt=media&token=8a1b1289-e16c-4e50-bf27-03fb188c4a97',
      },
      {
        nor: 'å ydmyke',
        eng: 'to humble',
        pl: 'pokornić',
        ar: 'أذل',
        ger: 'demütigen',
        lt: 'pažeminti',
        ua: 'принижувати',
        sp: 'humillar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fydmyke.mp3?alt=media&token=8474d0bc-d8e2-4676-bd71-933adb9dd244',
      },
      {
        nor: 'å forhandle',
        eng: 'to negotiate',
        pl: 'negocjować',
        ar: 'تفاوض',
        ger: 'verhandeln',
        lt: 'derybuoti',
        ua: 'переговоряти',
        sp: 'negociar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforhandle.mp3?alt=media&token=daa0454e-403a-480f-8093-8843a753e991',
      },
      {
        nor: 'å formidle',
        eng: 'to convey',
        pl: 'przekazać',
        ar: 'نقل',
        ger: 'vermitteln',
        lt: 'perduoti',
        ua: 'посередничати',
        sp: 'transmitir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fformidle.mp3?alt=media&token=0f019504-471e-4439-9aa8-80e8b37a684e',
      },
      {
        nor: 'å forske',
        eng: 'to research',
        pl: 'prowadzić badania',
        ar: 'بحث',
        ger: 'forschen',
        lt: 'tyrinėti',
        ua: 'досліджувати',
        sp: 'investigar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforske.mp3?alt=media&token=6a939d52-ed92-4c3a-b698-4aaa9dd1babb',
      },
      {
        nor: 'å gruble',
        eng: 'to ponder',
        pl: 'rozmyślać',
        ar: 'تأمل',
        ger: 'grübeln',
        lt: 'svarstyti',
        ua: 'роздумувати',
        sp: 'reflexionar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgruble.mp3?alt=media&token=1117ddce-75f9-405e-ac84-d9bd03f14e6d',
      },
      {
        nor: 'å håndtere',
        eng: 'to handle',
        pl: 'zajmować się',
        ar: 'يتعامل',
        ger: 'handhaben',
        lt: 'tvarkyti',
        ua: 'керувати',
        sp: 'manejar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhaandtere.mp3?alt=media&token=eae96799-2cdd-4872-b35f-754567121537',
      },
      {
        nor: 'å instruere',
        eng: 'to instruct',
        pl: 'instruować',
        ar: 'أعلم',
        ger: 'instruieren',
        lt: 'instruktuoti',
        ua: 'інструктувати',
        sp: 'instruir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finstruere.mp3?alt=media&token=826d2121-59c2-4026-ab41-3bec31602aa7',
      },
      {
        nor: 'å klargjøre',
        eng: 'to clarify',
        pl: 'wyjaśnić',
        ar: 'أوضح',
        ger: 'klären',
        lt: 'paaiškinti',
        ua: 'уточнити',
        sp: 'aclarar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklargjoore.mp3?alt=media&token=157a8610-a88a-4e22-9756-7e93f482f0a1',
      },
      {
        nor: 'å konkludere',
        eng: 'to conclude',
        pl: 'wywnioskować',
        ar: 'خلص',
        ger: 'schließen',
        lt: 'baigti',
        ua: 'робити висновок',
        sp: 'concluir',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkonkludere.mp3?alt=media&token=b5fcc9c2-92d5-467d-ba2b-1d0e4a78fef6',
      },
      {
        nor: 'å oppmuntre',
        eng: 'to encourage',
        pl: 'zachęcić',
        ar: 'شجع',
        ger: 'ermutigen',
        lt: 'skatinti',
        ua: 'заохочувати',
        sp: 'animar',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foppmuntre.mp3?alt=media&token=caf72caa-13d7-40a6-bf9f-34d15f2809c6',
      },
      {
        nor: 'å opprettholde',
        eng: 'to maintain',
        pl: 'utrzymać',
        ar: 'حافظ على',
        ger: 'aufrechterhalten',
        lt: 'palaikyti',
        ua: 'підтримувати',
        sp: 'mantener',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fopprettholde.mp3?alt=media&token=27ca6ce2-f086-4373-a1a4-705a3a59617c',
      },
      {
        nor: 'å granske',
        eng: 'to scrutinize',
        pl: 'analizować',
        ua: 'ретельно вивчати',
        ger: 'genau untersuchen',
        lt: 'nuodugniai nagrinėti',
        sp: 'examinar detenidamente',
        ar: 'يفحص بدقة',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgranske2.mp3?alt=media&token=2c9d90ed-52a6-4590-9802-960e5d00eae9',
      },
      {
        nor: 'å hemme',
        eng: 'to hamper',
        pl: 'utrudniać',
        ua: 'перешкоджати',
        ger: 'behindern',
        lt: 'trukdyti',
        sp: 'obstaculizar',
        ar: 'يعيق',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhemme2.mp3?alt=media&token=7f614e5e-5d38-4dff-92fa-a0d71065f367',
      },
      {
        nor: 'å utbedre',
        eng: 'to rectify',
        pl: 'naprawić',
        ua: 'виправити',
        ger: 'beheben',
        lt: 'ištaisyti',
        sp: 'rectificar',
        ar: 'يُصلح',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futbedre2.mp3?alt=media&token=95588774-7d5d-4b76-9af8-7e38c830b183',
      },
      {
        nor: 'å blomstre',
        eng: 'to flourish',
        pl: 'rozkwitać',
        ua: 'процвітати',
        ger: 'aufblühen',
        lt: 'klestėti',
        sp: 'florecer',
        ar: 'يزدهر',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblomstre2.mp3?alt=media&token=dd713131-4ba2-4a76-a322-385d999d7251',
      },
      {
        nor: 'å fastslå',
        eng: 'to ascertain',
        pl: 'ustalić',
        ua: 'встановити',
        ger: 'feststellen',
        lt: 'nustatyti',
        sp: 'constatar',
        ar: 'يتحقق من',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffastslaa2.mp3?alt=media&token=b868253f-c930-4ef2-814d-113f07fa16d6',
      },
      {
        nor: 'å nøste opp i',
        eng: 'to unravel',
        pl: 'rozwiązać',
        ua: 'розплутати',
        ger: 'entwirren',
        lt: 'išnarplioti',
        sp: 'desenredar',
        ar: 'يفك اللغز',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2FnestOppI2.mp3?alt=media&token=27758753-c746-4825-b822-5dff633d69d6',
      },
      {
        nor: 'å utslette',
        eng: 'to wipe out',
        pl: 'unicestwić',
        ua: 'знищити',
        ger: 'auslöschen',
        lt: 'išnaikinti',
        sp: 'aniquilar',
        ar: 'يقضي على',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futslette2.mp3?alt=media&token=59c744d2-5b58-45e6-9069-53989cd78bd0',
      },
      {
        nor: 'å overskygge',
        eng: 'to overshadow',
        pl: 'przyćmić',
        ua: 'затьмарити',
        ger: 'überschatten',
        lt: 'užgožti',
        sp: 'eclipsar',
        ar: 'يلقي بظلاله على',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverskygge2.mp3?alt=media&token=7aa5be21-9e51-4eb9-b9ac-2957ff33513b',
      },
      {
        nor: 'å lengte',
        eng: 'to yearn',
        pl: 'tęsknić',
        ua: 'тужити',
        ger: 'sich sehnen',
        lt: 'ilgėtis',
        sp: 'anhelar',
        ar: 'يتوق إلى',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flengte2.mp3?alt=media&token=5c42ed33-4fae-4aff-b366-b4cd63449908',
      },
      {
        nor: 'å dvele (ved)',
        eng: 'to dwell (on)',
        pl: 'rozpamiętywać',
        ua: 'зупинятися (на чомусь)',
        ger: 'verweilen bei',
        lt: 'apsistoti (ties)',
        sp: 'detenerse (en)',
        ar: 'يُطيل التفكير في',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdvele2.mp3?alt=media&token=d0f121d2-27af-49d2-85e2-842b0879e3f8',
      },
      
]