export default dataObj = [

    {
        typeOfScreen: '4',
        nuberOfQuestions: 2,
        questions: [
            ['Vannet er ', 'kaldt.'],         
            ['De snakker ', 'norsk.'] 
        ],
        correctAnswers: [['veldig'], ['flytende']],
        translations: {
            eng: ['very', 'fluently'],
            pl: ['bardzo', 'płynnie'],
            ar: ['جداً', 'بطلاقة'],
            ger: ['sehr', 'fließend'],
            lt: ['labai', 'sklandžiai'],
            ua: ['дуже', 'вільно'],
            sp: ['muy', 'fluentemente'],
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 2,
        questions: [
            ['Han snakker ', ''],  
            ['Kaken smaker ', '']    
        ],
        correctAnswers: [['sakte'], ['deilig']],
        translations: {
            eng: ['slowly', 'deliciously'],
            pl: ['wolno', 'pysznie'],
            ar: ['ببطء', 'لذيذاً'],
            ger: ['langsam', 'köstlich'],
            lt: ['lėtai', 'skaniai'],
            ua: ['повільно', 'смачно'],
            sp: ['lentamente', 'deliciosamente'],
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 2,
        questions: [
            ['Månen skinner ', 'i natt.'],      
            ['Barnet sover ', 'nå.'],      
        ],
        correctAnswers: [['klart'], ['dypt']],
        translations: {
            eng: ['clearly', 'deeply'],
            pl: ['jasno', 'głęboko'],
            ar: ['بوضوح', 'بعمق'],
            ger: ['klar', 'tief'],
            lt: ['aiškiai', 'giliai'],
            ua: ['ясно', 'глибоко'],
            sp: ['claramente', 'profundamente'],
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Hun ', 'en bok.'],             
            ['Vi ', 'på skolen.'],           
            ['Han ', 'norsk.'],              
            ['Barna ', 'i parken.'],        
        ],
        correctAnswers: [['leser'], ['lærer'], ['snakker'], ['leker']],
        translations: {
            eng: ['reads', 'learn', 'speaks', 'play'],
            pl: ['czyta', 'uczą się', 'mówi', 'bawią się'],
            ar: ['تقرأ', 'يتعلمون', 'يتحدث', 'يلعبون'],
            ger: ['liest', 'lernen', 'spricht', 'spielen'],
            lt: ['skaito', 'mokosi', 'kalba', 'žaidžia'],
            ua: ['читає', 'вчаться', 'говорить', 'грають'],
            sp: ['lee', 'aprenden', 'habla', 'juegan'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Katten ', 'melk.'],         
            ['De ', 'i butikken.'],      
            ['Jeg ', 'til musikk.'],      
            ['Bilen ', 'raskt.'],   
        ],
        correctAnswers: [['drikker'], ['jobber'], ['lytter'], ['kjører']],
        translations: {
            eng: ['drinks', 'work', 'listen', 'drives'],
            pl: ['pije', 'pracują', 'słucha', 'jedzie'],
            ar: ['يشرب', 'يعملون', 'يستمع', 'يقود'],
            ger: ['trinkt', 'arbeiten', 'hört', 'fährt'],
            lt: ['geria', 'dirba', 'klauso', 'važiuoja'],
            ua: ['п’є', 'працюють', 'слухає', 'їде'],
            sp: ['bebe', 'trabajan', 'escucha', 'conduce'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Fuglene ', 'tidlig.'],        
            ['Hun ', 'en bok.'],             
            ['Barna ', 'på skolen.'],    
            ['Vi ', 'middag nå.'],         
        ],
        correctAnswers: [['synger'], ['leser'], ['leker'], ['lager']],
        translations: {
            eng: ['sing', 'read', 'play', 'make'],
            pl: ['śpiewają', 'czyta', 'bawią się', 'robią'],
            ar: ['يغنون', 'تقرأ', 'يلعبون', 'يصنعون'],
            ger: ['singen', 'liest', 'spielen', 'machen'],
            lt: ['dainuoja', 'skaito', 'žaidžia', 'ruošia'],
            ua: ['співають', 'читає', 'грають', 'готують'],
            sp: ['cantan', 'lee', 'juegan', 'hacen'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Jeg ', 'i Oslo.'],           
            ['Du ', 'norsk.'],             
            ['Hunden ', 'maten.'],         
            ['Læreren ', 'i klasserommet.'], 
        ],
        correctAnswers: [['bor'], ['snakker', 'prater'], ['spiser'], ['underviser']],
        translations: {
            eng: ['live', 'speak', 'eats', 'teaches'],
            pl: ['mieszka', 'mówi', 'je', 'uczy'],
            ar: ['يعيش', 'يتحدث', 'يأكل', 'يعلم'],
            ger: ['wohnt', 'spricht', 'isst', 'unterrichtet'],
            lt: ['gyvena', 'kalba', 'valgo', 'moko'],
            ua: ['живе', 'говорить', 'їсть', 'вчить'],
            sp: ['vive', 'habla', 'come', 'enseña'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Barnet ', 'med lekene.'],           
            ['Han ', 'på datamaskinen.'],        
            ['Vi ', 'på musikken.'],          
            ['Hun ', 'på treningsstudioet.'],  
        ],
        correctAnswers: [['leker'], ['jobber'], ['hører'], ['trener']],
        translations: {
            eng: ['plays', 'works', 'listens', 'exercises'],
            pl: ['bawi się', 'pracuje', 'słucha', 'ćwiczy'],
            ar: ['يلعب', 'يعمل', 'يستمع', 'يتمرن'],
            ger: ['spielt', 'arbeitet', 'hört zu', 'trainiert'],
            lt: ['žaidžia', 'dirba', 'klauso', 'treniruojasi'],
            ua: ['грається', 'працює', 'слухає', 'тренується'],
            sp: ['juega', 'trabaja', 'escucha', 'ejercita'],
        },
        instructions: {
            eng: 'Type the correct verb in present tense.',
            pl: 'Wpisz odpowiedni czasownik w czasie teraźniejszym.',
            ar: 'اكتب الفعل الصحيح في زمن المضارع',
            ger: 'Gib das richtige Verb im Präsens ein.',
            lt: 'Įvesk teisingą veiksmažodį esamuoju laiku.',
            ua: 'Введіть правильне дієслово у теперішньому часі.', 
            sp: 'Escribe el verbo correcto en tiempo presente.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['Han snakker om ', 'selv.'],     
            ['Vi må ta vare på ', 'selv.'],    
            ['Du må tro på ', 'selv.'],       
            ['Hun ser på ', 'i speilet.'],         
        ],
        correctAnswers: [['seg'], ['oss'], ['deg'], ['seg']],
        instructions: {
            eng: 'Type the correct reflexive pronoun',
            pl: 'Wpisz odpowiedni zaimek zwrotny.',
            ar: 'اكتب الضمير الانعكاسي الصحيح',
            ger: 'Gib das richtige Reflexivpronomen ein.',
            lt: 'Įvesk teisingą įvardžiūninį įvardį.',
            ua: 'Введіть правильний зворотний займенник.', 
            sp: 'Escribe el pronombre reflexivo correcto.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 2,
        questions: [
            ['Jeg gleder ', 'til festen.'],    
            ['Hun kjøpte en gave til ', 'selv.'],
        ],
        correctAnswers: [['meg'], ['seg']],
        instructions: {
            eng: 'Type the correct reflexive pronoun',
            pl: 'Wpisz odpowiedni zaimek zwrotny.',
            ar: 'اكتب الضمير الانعكاسي الصحيح',
            ger: 'Gib das richtige Reflexivpronomen ein.',
            lt: 'Įvesk teisingą įvardžiūninį įvardį.',
            ua: 'Введіть правильний зворотний займенник.', 
            sp: 'Escribe el pronombre reflexivo correcto.',
        },
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['', 'liker å lese bøker.'],    
            ['Kan ', 'hjelpe meg?'],        
            ['', 'bor i Norge.'],           
            ['', 'er på skolen.'],       
        ],
        correctAnswers: [['De'], ['du'], ['Vi'], ['Hun']],
        translations: {
            eng: ['They', 'you', 'We', 'She'],
            pl: ['Oni', 'ty', 'My', 'Ona'],
            ar: ['هم', 'أنت', 'نحن', 'هي'],
            ger: ['Sie', 'du', 'Wir', 'Sie'],
            lt: ['Jie', 'tu', 'Mes', 'Ji'],
            ua: ['Вони', 'ти', 'Ми', 'Вона'],
            sp: ['Ellos', 'tú', 'Nosotros', 'Ella'],
        },
        instructions: {
            eng: 'Type the correct personal pronoun.',
            pl: 'Wpisz odpowiedni zaimek osobowy.',
            ar: 'ااكتب الضمير الشخصي الصحيح',
            ger: 'Gib das richtige Personalpronomen ein.',
            lt: 'Įvesk teisingą asmens įvardį.',
            ua: 'Введіть правильний особовий займенник.', 
            sp: 'Escribe el pronombre personal correcto.',
        },
    
    },
    {
        typeOfScreen: '4',
        nuberOfQuestions: 4,
        questions: [
            ['', 'snakker norsk.'],    
            ['', 'går på tur sammen.'],     
            ['', 'har en katt.'],         
            ['', 'liker å svømme.'],     
        ],
        correctAnswers: [['Han'], ['De'], ['Jeg'], ['Du']],
        translations: {
            eng: ['He', 'They', 'I', 'You'],
            pl: ['On', 'Oni', 'Ja', 'Ty'],
            ar: ['هو', 'هم', 'أنا', 'أنت'],
            ger: ['Er', 'Sie', 'Ich', 'Du'],
            lt: ['Jis', 'Jie', 'Aš', 'Tu'],
            ua: ['Він', 'Вони', 'Я', 'Ти'],
            sp: ['Él', 'Ellos', 'Yo', 'Tú'],
        },
        instructions: {
            eng: 'Type the correct personal pronoun.',
            pl: 'Wpisz odpowiedni zaimek osobowy.',
            ar: 'ااكتب الضمير الشخصي الصحيح',
            ger: 'Gib das richtige Personalpronomen ein.',
            lt: 'Įvesk teisingą asmens įvardį.',
            ua: 'Введіть правильний особовий займенник.', 
            sp: 'Escribe el pronombre personal correcto.',
        },
    }
    
];