export default dataObj = [
    
  {
      nor: 'å forklare',
      eng: 'to explain',
      pl: 'wyjaśniać',
      ar: 'شرح',
      ger: 'erklären',
      lt: 'paaiškinti',
      ua: 'пояснювати',
      sp: 'explicar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforklare.mp3?alt=media&token=8f68d18f-5d74-401f-beaa-d896f5938eff',
  },
  {
      nor: 'å forsøke',
      eng: 'to attempt',
      pl: 'próbować',
      ar: 'محاولة',
      ger: 'versuchen',
      lt: 'bandyti',
      ua: 'намагатися',
      sp: 'intentar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforsooke.mp3?alt=media&token=b30f5ef4-22a8-48ed-a7c1-f04ebf13af53',
  },
  {
      nor: 'å godta',
      eng: 'to accept',
      pl: 'akceptować',
      ar: 'يقبل',
      ger: 'akzeptieren',
      lt: 'priimti',
      ua: 'приймати',
      sp: 'aceptar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgodta.mp3?alt=media&token=b42d089e-d21b-4ff5-8309-51630d0aa3a8',
  },
  {
      nor: 'å hjelpe',
      eng: 'to help',
      pl: 'pomagać',
      ar: 'مساعدة',
      ger: 'helfen',
      lt: 'padėti',
      ua: 'допомагати',
      sp: 'ayudar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhjelpe.mp3?alt=media&token=b88f5831-b259-4f15-8146-4514f77a83ac',
  },
  {
      nor: 'å invitere',
      eng: 'to invite',
      pl: 'zapraszać',
      ar: 'يدعو',
      ger: 'einladen',
      lt: 'pakviesti',
      ua: 'запрошувати',
      sp: 'invitar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finvitere.mp3?alt=media&token=e7118e87-6a73-4b0a-bb88-039b95bdf52d',
  },
  {
      nor: 'å klage',
      eng: 'to complain',
      pl: 'skarżyć się',
      ar: 'يتذمر',
      ger: 'sich beschweren',
      lt: 'skųstis',
      ua: 'скаржитися',
      sp: 'quejar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklage.mp3?alt=media&token=91b20990-f63d-4281-b0e9-b2d3419713f5',
  },
  {
      nor: 'å låse',
      eng: 'to lock',
      pl: 'zamykać na klucz',
      ar: 'قفل',
      ger: 'abschließen',
      lt: 'užrakinti',
      ua: 'замикати',
      sp: 'cerrar con llave',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flaase.mp3?alt=media&token=f4b89df4-5422-459c-87aa-6c2b7f30f34b',
  },
  {
      nor: 'å dra',
      eng: 'to pull',
      pl: 'ciągnąć',
      ar: 'يسحب',
      ger: 'ziehen',
      lt: 'traukti',
      ua: 'їхати',
      sp: 'ir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdra.mp3?alt=media&token=69107f6a-cf4d-4e22-8140-09f2af86a2ae',
  },
  {
      nor: 'å brenne',
      eng: 'to burn',
      pl: 'palić',
      ar: 'يحترق',
      ger: 'brennen',
      lt: 'degti',
      ua: 'горіти',
      sp: 'quemar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrenne.mp3?alt=media&token=cae53ee0-80ed-4e59-a9a8-63b3de058a74',
  },
  {
      nor: 'å falle',
      eng: 'to fall',
      pl: 'upadać',
      ar: 'يسقط',
      ger: 'fallen',
      lt: 'kristi',
      ua: 'падати',
      sp: 'caer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffalle.mp3?alt=media&token=b0a55019-4863-475a-9b4a-49e26afd9f17',
  },
  {
      nor: 'å klatre',
      eng: 'to climb',
      pl: 'wspinać się',
      ar: 'تسلق',
      ger: 'klettern',
      lt: 'lipti',
      ua: 'лазити',
      sp: 'escalar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklatre.mp3?alt=media&token=f4d24127-ba61-4af3-9b77-e050466e8e3c',
  },
  {
      nor: 'å vokse',
      eng: 'to grow',
      pl: 'rosnąć',
      ar: 'ينمو',
      ger: 'wachsen',
      lt: 'augti',
      ua: 'рости',
      sp: 'crecer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvokse.mp3?alt=media&token=a4dbf538-cfa0-4601-af00-50459756393f',
  },
  {
      nor: 'å lage',
      eng: 'to make',
      pl: 'robić',
      ar: 'يصنع',
      ger: 'machen',
      lt: 'daryti',
      ua: 'робити',
      sp: 'hacer',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flage.mp3?alt=media&token=8754ce1f-532f-43b2-92e7-2978d4f25017',
  },
  {
      nor: 'å låne',
      eng: 'to borrow',
      pl: 'pożyczyć',
      ar: 'اقتراض',
      ger: 'ausleihen',
      lt: 'pasiskolinti',
      ua: 'позичати',
      sp: 'prestar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flaane.mp3?alt=media&token=0b32cf74-f3bc-4876-ad4d-460e6c39c782',
  },
  {
      nor: 'å mene',
      eng: 'to think',
      pl: 'myśleć',
      ar: 'يظن',
      ger: 'meinen',
      lt: 'manyti',
      ua: 'вважати',
      sp: 'pensar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmene.mp3?alt=media&token=26123744-6154-436b-94ca-aad7c013e6a4',
  },
  {
      nor: 'å nekte',
      eng: 'to deny',
      pl: 'zaprzeczać',
      ar: 'ينكر',
      ger: 'verneinen',
      lt: 'neigti',
      ua: 'відмовляти',
      sp: 'negar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnekte.mp3?alt=media&token=dd5b783b-5249-4733-a370-8ec21523f29c',
  },
  {
      nor: 'å overraske',
      eng: 'to surprise',
      pl: 'zaskoczyć',
      ar: 'يفاجأ',
      ger: 'überraschen',
      lt: 'nustebinti',
      ua: 'здивувати',
      sp: 'sorprender',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverraske.mp3?alt=media&token=8920ee41-aaee-4c27-a968-ee9e3baf1741',
  },
  {
      nor: 'å regne',
      eng: 'to count',
      pl: 'liczyć',
      ar: 'يعد',
      ger: 'zählen',
      lt: 'skaičiuoti',
      ua: 'рахувати',
      sp: 'contar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fregne.mp3?alt=media&token=b0b63901-e554-4e5f-a52f-6c918e6cfcf1',
  },
  {
      nor: 'å skjønne',
      eng: 'to understand',
      pl: 'rozumieć',
      ar: 'أن يفهم',
      ger: 'verstehen',
      lt: 'suprasti',
      ua: 'розуміти',
      sp: 'entender',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjoonne.mp3?alt=media&token=94e1b9cc-a6a0-4807-8e7b-61d14ebbce6e',
  },
  {
      nor: 'å tillate',
      eng: 'to allow',
      pl: 'pozwalać',
      ar: 'السماح',
      ger: 'erlauben',
      lt: 'leisti',
      ua: 'дозволити',
      sp: 'permitir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftillate.mp3?alt=media&token=4e466c3d-dfbd-4267-b4b6-536a9b53294c',
  },
  {
      nor: 'å trenge',
      eng: 'to need',
      pl: 'potrzebować',
      ar: 'يحتاج',
      ger: 'brauchen',
      lt: 'reikėti',
      ua: 'потребувати',
      sp: 'necesitar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrenge.mp3?alt=media&token=bbec5f45-c3d1-4a6c-a377-00470dcde450',
  },
  {
      nor: 'å velge',
      eng: 'to choose',
      pl: 'wybierać',
      ar: 'اختيار',
      ger: 'wählen',
      lt: 'pasirinkti',
      ua: 'вибирати',
      sp: 'elegir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvelge.mp3?alt=media&token=872381ee-26de-49b8-9020-ff87c2b0fbb9',
  },
  {
      nor: 'å ønske',
      eng: 'to wish',
      pl: 'życzyć',
      ar: 'يتمنى',
      ger: 'wünschen',
      lt: 'norėti',
      ua: 'бажати',
      sp: 'desear',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foonske.mp3?alt=media&token=29551ed8-a1d1-4756-9e17-8645b664e51b',
  },
  {
      nor: 'å diskutere',
      eng: 'to discuss',
      pl: 'dyskutować',
      ar: 'يناقش',
      ger: 'diskutieren',
      lt: 'diskutuoti',
      ua: 'обговорювати',
      sp: 'discutir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdiskutere.mp3?alt=media&token=b6baa901-24a5-4d7a-9a18-3f5dbe0151a5',
  },
  {
      nor: 'å hente',
      eng: 'to fetch',
      pl: 'przynieść',
      ar: 'جلب',
      ger: 'holen',
      lt: 'atnešti',
      ua: 'забирати',
      sp: 'recoger',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhente.mp3?alt=media&token=330ef0dd-d570-4525-8598-54c1cdd92bec',
  },
  {
      nor: 'å fryse',
      eng: 'to freeze',
      pl: 'zamrażać',
      ar: 'يتجمد',
      ger: 'einfrieren',
      lt: 'šaldyti',
      ua: 'замерзати',
      sp: 'congelar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffryse.mp3?alt=media&token=4cd7d625-d85b-41a7-9b02-2badd29b0aec',
  },
  {
      nor: 'å varme',
      eng: 'to warm',
      pl: 'ogrzewać',
      ar: 'يدفئ',
      ger: 'erwärmen',
      lt: 'šildyti',
      ua: 'гріти',
      sp: 'calentar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvarme.mp3?alt=media&token=e054e240-8966-40e2-8c94-8552da5f543e',
  },
  {
      nor: 'å kaste',
      eng: 'to throw',
      pl: 'rzucać',
      ar: 'يلقي',
      ger: 'werfen',
      lt: 'mesti',
      ua: 'кидати',
      sp: 'lanzar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkaste.mp3?alt=media&token=45112afc-681a-4e9e-add1-2301c3b71206',
  },
  {
      nor: 'å smelte',
      eng: 'to melt',
      pl: 'topić',
      ar: 'يذوب',
      ger: 'schmelzen',
      lt: 'tirpinti',
      ua: 'танути',
      sp: 'derretir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsmelte.mp3?alt=media&token=ec175d6d-35d9-47dc-b0ea-386195e67424',
  },
  {
      nor: 'å slå',
      eng: 'to hit',
      pl: 'uderzać',
      ar: 'يضرب',
      ger: 'schlagen',
      lt: 'mušti',
      ua: 'бити',
      sp: 'golpear',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslaa.mp3?alt=media&token=6e7abc6d-b375-488c-994d-188b8a56e3a4',
  },
  {
      nor: 'å klemme',
      eng: 'to squeeze',
      pl: 'ściskać',
      ar: 'يعصر',
      ger: 'quetschen',
      lt: 'spausti',
      ua: 'обіймати',
      sp: 'abrazar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklemme.mp3?alt=media&token=009976ae-4653-4407-bceb-2f78e0d95e8e',
  },
  {
      nor: 'å tegne',
      eng: 'to draw',
      pl: 'rysować',
      ar: 'يرسم',
      ger: 'zeichnen',
      lt: 'piešti',
      ua: 'малювати',
      sp: 'dibujar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftegne.mp3?alt=media&token=a8024084-54c6-4483-9e4b-7df00d403a77',
  },
  {
      nor: 'å male',
      eng: 'to paint',
      pl: 'malować',
      ar: 'يدهن',
      ger: 'malen',
      lt: 'dažyti',
      ua: 'фарбувати',
      sp: 'pintar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmale.mp3?alt=media&token=ad998837-34fd-4802-941b-bfdd21f90eb6',
  },
  {
      nor: 'å dele',
      eng: 'to share',
      pl: 'dzielić',
      ar: 'مشاركة',
      ger: 'teilen',
      lt: 'dalytis',
      ua: 'ділити',
      sp: 'compartir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdele.mp3?alt=media&token=df44b9e7-8a1a-45e8-b662-c0e5caf627e4',
  },
  {
      nor: 'å telle',
      eng: 'to count',
      pl: 'liczyć',
      ar: 'يعد',
      ger: 'zählen',
      lt: 'skaičiuoti',
      ua: 'рахувати',
      sp: 'contar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftelle.mp3?alt=media&token=96392374-3905-4746-9775-1f5ad190eadf',
  },
  {
      nor: 'å bygge',
      eng: 'to build',
      pl: 'budować',
      ar: 'يبني',
      ger: 'bauen',
      lt: 'statyti',
      ua: 'будувати',
      sp: 'construir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbygge.mp3?alt=media&token=b5a76118-d96f-49a9-9f0b-b55c1da824db',
  },
  {
      nor: 'å skyve',
      eng: 'to push',
      pl: 'pchać',
      ar: 'يدفع',
      ger: 'schieben',
      lt: 'stumti',
      ua: 'штовхати',
      sp: 'empujar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskyve.mp3?alt=media&token=375a7313-029b-4e0f-ba83-1748a31ec214',
  },
  {
      nor: 'å tilbringe',
      eng: 'to spend (time)',
      pl: 'spędzać (czas)',
      ar: 'قضاء',
      ger: 'verbringen',
      lt: 'praleisti',
      ua: 'проводити (час)',
      sp: 'pasar (tiempo)',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftilbringe.mp3?alt=media&token=9535a0f7-c755-43ea-bcc1-1e1e9ab22baa',
  },
  {
      nor: 'å sende',
      eng: 'to send',
      pl: 'wysyłać',
      ar: 'إرسال',
      ger: 'senden',
      lt: 'siųsti',
      ua: 'надсилати',
      sp: 'enviar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsende.mp3?alt=media&token=2a9d988e-29ed-4911-bfa2-feb0ed88b301',
  },
  {
      nor: 'å miste',
      eng: 'to lose',
      pl: 'tracić',
      ar: 'تفقد',
      ger: 'verlieren',
      lt: 'prarasti',
      ua: 'губити',
      sp: 'perder',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmiste.mp3?alt=media&token=a12846bf-20d1-41cf-8a2e-7c70c796e780',
  },
  {
      nor: 'å krympe',
      eng: 'to shrink',
      pl: 'kurczyć się',
      ar: 'تقلص',
      ger: 'schrumpfen',
      lt: 'traukti',
      ua: 'скорочувати',
      sp: 'encoger',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkrympe.mp3?alt=media&token=3ec5eba9-7749-443d-ae6d-b86672c351db',
  },
  {
      nor: 'å bli kvitt',
      eng: 'to get rid of',
      pl: 'pozbyć się',
      ar: 'التخلص من',
      ger: 'loswerden',
      lt: 'atbristi',
      ua: 'позбутися',
      sp: 'deshacerse',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblikvitt.mp3?alt=media&token=d9cc0af5-b2d7-4d31-bcbf-c9e0fe8e4601',
  },
  {
      nor: 'å blande',
      eng: 'to mix',
      pl: 'mieszać',
      ar: 'خلط',
      ger: 'mischen',
      lt: 'maišyti',
      ua: 'змішувати',
      sp: 'mezclar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblande.mp3?alt=media&token=e73249ee-b2b1-4e9d-95bd-6ac7070ecfcf',
  },
  {
      nor: 'å bade',
      eng: 'to bathe',
      pl: 'kąpać się',
      ar: 'الاستحمام',
      ger: 'baden',
      lt: 'maudytis',
      ua: 'купатися',
      sp: 'bañar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbade.mp3?alt=media&token=53bdc581-7da3-4d9b-9e6e-295980120faf',
  },
  {
      nor: 'å vaske',
      eng: 'to wash',
      pl: 'myć',
      ar: 'غسل',
      ger: 'waschen',
      lt: 'plauti',
      ua: 'мити',
      sp: 'lavar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaske2.mp3?alt=media&token=4b2a9b1f-e640-4dae-8944-5c72679a360a',
  },
  {
      nor: 'å tørke',
      eng: 'to dry',
      pl: 'suszyć',
      ar: 'يجف',
      ger: 'trocknen',
      lt: 'džiovinti',
      ua: 'сушити',
      sp: 'secar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftoorke.mp3?alt=media&token=892da2c3-16bb-4db1-bfbb-92712b11d023',
  },
  {
      nor: 'å dekke',
      eng: 'to cover',
      pl: 'pokrywać',
      ar: 'يغطي',
      ger: 'abdecken',
      lt: 'dengti',
      ua: 'покривати',
      sp: 'cubrir',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdekke.mp3?alt=media&token=1046b9ad-57bd-46f5-92ba-82ac86a73508',
  },
  {
      nor: 'å grave',
      eng: 'to dig',
      pl: 'kopać',
      ar: 'يحفر',
      ger: 'graben',
      lt: 'kasti',
      ua: 'копати',
      sp: 'excavar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrave.mp3?alt=media&token=c4c3fa74-9799-4e06-b6c3-337a7ac2ccad',
  },
  {
    nor: 'å akseptere',
    eng: 'to accept',
    pl: 'akceptować',
    ar: 'يقبل',
    ger: 'akzeptieren',
    lt: 'priimti',
    ua: 'приймати',
    sp: 'aceptar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fakseptere.mp3?alt=media&token=29979882-e139-4f14-bf8c-87e40019d521',
  },
  {
    nor: 'å analysere',
    eng: 'to analyze',
    pl: 'analizować',
    ar: 'تحليل',
    ger: 'analysieren',
    lt: 'analizuoti',
    ua: 'аналізувати',
    sp: 'analizar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fanalysere.mp3?alt=media&token=226ca6f8-8ade-4a52-9205-8aac89fd42af',
  },
  {
    nor: 'å endre',
    eng: 'to change',
    pl: 'zmieniać',
    ar: 'تغيير',
    ger: 'ändern',
    lt: 'keisti',
    ua: 'змінювати',
    sp: 'cambiar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fendre.mp3?alt=media&token=f601eb55-cf16-4327-9261-61da3e4ad510',
  },
  {
    nor: 'å etablere',
    eng: 'to establish',
    pl: 'ustanowić',
    ar: 'تأسيس',
    ger: 'etablieren',
    lt: 'įkurti',
    ua: 'встановлювати',
    sp: 'establecer',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fetablere.mp3?alt=media&token=e0563700-a86a-49ea-995e-2411ceaf3ddc',
  },
  {
    nor: 'å forbedre',
    eng: 'to improve',
    pl: 'poprawić',
    ar: 'تحسين',
    ger: 'verbessern',
    lt: 'pagerinti',
    ua: 'покращувати',
    sp: 'mejorar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforbedre.mp3?alt=media&token=95adac3a-4707-4fab-979e-be1d944d0e78',
  },
  {
    nor: 'å banke',
    eng: 'to knock',
    pl: 'pukać',
    ar: 'يطرق',
    ger: 'klopfen',
    lt: 'belsti',
    ua: 'стукати',
    sp: 'golpear',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbanke.mp3?alt=media&token=80e02f4c-67af-4fba-9e36-82bad3ad6a22',
  },
  {
    nor: 'å forvente',
    eng: 'to expect',
    pl: 'oczekiwać',
    ar: 'يتوقع',
    ger: 'erwarten',
    lt: 'tikėtis',
    ua: 'очікувати',
    sp: 'esperar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforvente.mp3?alt=media&token=ac50c6f2-3707-41b8-bbb8-f05d0137c5ff',
  },
  {
    nor: 'å fremme',
    eng: 'to promote',
    pl: 'promować',
    ar: 'تعزيز',
    ger: 'fördern',
    lt: 'skatinti',
    ua: 'сприяти',
    sp: 'promover',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffremme.mp3?alt=media&token=dd4806f4-15f7-489b-af4f-3857d5a13ae1',
  },
  {
    nor: 'å hindre',
    eng: 'prevent',
    pl: 'zapobiegać',
    ar: 'منع',
    ger: 'verhindern',
    lt: 'užkirsti kelią',
    ua: 'перешкоджати',
    sp: 'impedir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhindre.mp3?alt=media&token=cc4e7e4c-4a3f-4351-85f8-e89059fe75c0',
  },
  {
    nor: 'å lykkes',
    eng: 'succeed',
    pl: 'odnieść sukces',
    ar: 'ينجح',
    ger: 'Erfolg haben',
    lt: 'pasisekti',
    ua: 'досягати успіху',
    sp: 'tener éxito',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flykkes.mp3?alt=media&token=2df234e0-d6d8-4205-a545-d6d47da986c7',
  },
  {
    nor: 'å nøle',
    eng: 'hesitate',
    pl: 'wahać się',
    ar: 'تردد',
    ger: 'zögern',
    lt: 'nedrąsoti',
    ua: 'вагатися',
    sp: 'dudar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnoole.mp3?alt=media&token=18198d30-33ff-45b0-ae47-65c7e91ec18e',
  },
  {
    nor: 'å beskrive',
    eng: 'to describe',
    pl: 'opisywać',
    ar: 'لوصف',
    ger: 'beschreiben',
    lt: 'apibūdinti',
    ua: 'описувати',
    sp: 'describir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbeskrive.mp3?alt=media&token=57f99fa7-d551-4a69-a8a2-4c6abf8c853a',
  },
  {
    nor: 'å bestemme',
    eng: 'to decide',
    pl: 'zdecydować',
    ar: 'للتحديد',
    ger: 'entscheiden',
    lt: 'nuspręsti',
    ua: 'визначати',
    sp: 'decidir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbestemme.mp3?alt=media&token=e4ccd26e-e7ea-446c-bb58-9731f7821c2b',
  },
  {
    nor: 'å observere',
    eng: 'observe',
    pl: 'obserwować',
    ar: 'ملاحظة',
    ger: 'beobachten',
    lt: 'stebėti',
    ua: 'спостерігати',
    sp: 'observar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fobservere.mp3?alt=media&token=79d6793c-1971-42cf-b2cc-69e17174969a',
  },
  {
    nor: 'å redusere',
    eng: 'reduce',
    pl: 'redukować',
    ar: 'تخفيض',
    ger: 'reduzieren',
    lt: 'sumažinti',
    ua: 'зменшувати',
    sp: 'reducir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fredusere.mp3?alt=media&token=5729a94e-037e-41a4-8bd9-c0581ea3fba6',
  },
  {
    nor: 'å reflektere',
    eng: 'reflect',
    pl: 'rozważać',
    ar: 'تفكير',
    ger: 'nachdenken',
    lt: 'atsispindėti',
    ua: 'роздумувати',
    sp: 'reflexionar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freflektere.mp3?alt=media&token=75bdcd90-df15-4ebf-a3a3-185a70c6b8bb',
  },
  {
    nor: 'å sette pris på',
    eng: 'to appreciate',
    pl: 'doceniać',
    ar: 'يقدر',
    ger: 'schätzen',
    lt: 'įvertinti',
    ua: 'цінувати',
    sp: 'apreciar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsetteprispaa.mp3?alt=media&token=37393ac4-8c96-4dda-ae4a-9aba5045c393',
  },
  {
    nor: 'å skuffe',
    eng: 'to disappoint',
    pl: 'rozczarować',
    ar: 'يخيب الامل',
    ger: 'enttäuschen',
    lt: 'nuvilti',
    ua: 'розчаровувати',
    sp: 'decepcionar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskuffe.mp3?alt=media&token=0f3ccbd6-3f9e-46b6-9444-a02937a584eb',
  },
  {
    nor: 'å tolerere',
    eng: 'to tolerate',
    pl: 'tolerować',
    ar: 'يتسامح',
    ger: 'tolerieren',
    lt: 'toleruoti',
    ua: 'толерувати',
    sp: 'tolerar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftolerere.mp3?alt=media&token=0f54065e-290b-4e04-a5d8-9a1f3f42e9cf',
  },
  {
    nor: 'å utvikle',
    eng: 'to develop',
    pl: 'rozwijać',
    ar: 'يطور',
    ger: 'entwickeln',
    lt: 'plėtoti',
    ua: 'розвивати',
    sp: 'desarrollar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futvikle.mp3?alt=media&token=33f11601-6235-40ba-8f73-378d4d565c79',
  },
  {
    nor: 'å vedta',
    eng: 'to adopt',
    pl: 'przyjąć',
    ar: 'تبنى',
    ger: 'annehmen',
    lt: 'priimti',
    ua: 'приймати',
    sp: 'adoptar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvedta.mp3?alt=media&token=9b6517a5-014f-4a20-9afe-01320b6eff62',
  },
  {
    nor: 'å være enig',
    eng: 'to agree',
    pl: 'zgadzać się',
    ar: 'يوافق',
    ger: 'zustimmen',
    lt: 'sutikti',
    ua: 'погоджуватися',
    sp: 'estar de acuerdo',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fveereenig.mp3?alt=media&token=2a03f0dc-dcd6-47fd-a72f-996dde1ba9e4',
  },
  {
    nor: 'å oppdage',
    eng: 'to discover',
    pl: 'odkryć',
    ar: 'اكتشاف',
    ger: 'entdecken',
    lt: 'atrasti',
    ua: 'відкривати',
    sp: 'descubrir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foppdage.mp3?alt=media&token=3e929ddb-97f7-456f-9c7a-ef19549540ca',
  },
  {
    nor: 'å bevare',
    eng: 'to preserve',
    pl: 'zachować',
    ar: 'للحفاظ على',
    ger: 'erhalten',
    lt: 'išsaugoti',
    ua: 'зберігати',
    sp: 'conservar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbevare.mp3?alt=media&token=5cf3f5cb-0a4e-47d3-baad-6a7b0dfe6aa3',
  },
  {
    nor: 'å delta',
    eng: 'to participate',
    pl: 'uczestniczyć',
    ar: 'المشاركة',
    ger: 'teilnehmen',
    lt: 'dalyvauti',
    ua: 'брати участь',
    sp: 'participar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdelta.mp3?alt=media&token=0792b325-f071-4a26-9926-187678b9f105',
  },
  {
    nor: 'å uttrykke',
    eng: 'to express',
    pl: 'wyrażać',
    ar: 'للتعبير',
    ger: 'ausdrücken',
    lt: 'išreikšti',
    ua: 'виражати',
    sp: 'expresar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futtrykke.mp3?alt=media&token=42ac5f9e-7cdf-4900-83a4-abd9935854d8',
  },
  {
    nor: 'å vurdere',
    eng: 'to assess',
    pl: 'oceniać',
    ar: 'تقييم',
    ger: 'bewerten',
    lt: 'įvertinti',
    ua: 'оцінювати',
    sp: 'evaluar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvurdere.mp3?alt=media&token=37fad857-8b21-48af-b789-adb086000d7a',
  },
  {
    nor: 'å sammenligne',
    eng: 'to compare',
    pl: 'porównywać',
    ar: 'للمقارنة',
    ger: 'vergleichen',
    lt: 'palyginti',
    ua: 'порівнювати',
    sp: 'comparar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsammenligne.mp3?alt=media&token=4e20c141-a387-4867-bce4-6d0d7a971d46',
  },
  {
    nor: 'å anbefale',
    eng: 'to recommend',
    pl: 'polecać',
    ar: 'للتوصية',
    ger: 'empfehlen',
    lt: 'rekomenduoti',
    ua: 'рекомендувати',
    sp: 'recomendar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fanbefale.mp3?alt=media&token=23da80de-58a2-4f56-a371-525371b0cbaa',
  },
  {
    nor: 'å avhenge',
    eng: 'to depend',
    pl: 'zależeć',
    ar: 'يعتمد على',
    ger: 'abhängen',
    lt: 'priklauso',
    ua: 'залежати',
    sp: 'depender',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Favhenge.mp3?alt=media&token=788d175a-387a-4a59-848b-ab53ad1e5928',
  },
  {
    nor: 'å bevise',
    eng: 'to prove',
    pl: 'udowodnić',
    ar: 'أثبت',
    ger: 'beweisen',
    lt: 'įrodyti',
    ua: 'доводити',
    sp: 'probar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbevise.mp3?alt=media&token=5e1d253e-c1ee-48c8-8b15-0d41fbd67008',
  },
  {
    nor: 'å styrke',
    eng: 'to strengthen',
    pl: 'wzmocnić',
    ar: 'عزز',
    ger: 'stärken',
    lt: 'sustiprinti',
    ua: 'зміцнювати',
    sp: 'fortalecer',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstyrke.mp3?alt=media&token=f13613f8-0469-4115-90be-d6acf3099dda',
  },
  {
    nor: 'å vandre',
    eng: 'to wander',
    pl: 'włóczyć się',
    ar: 'تجول',
    ger: 'wandern',
    lt: 'klajoti',
    ua: 'блукати',
    sp: 'vagar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvandre.mp3?alt=media&token=f7e9873e-15da-406c-bd9c-b0a9a6a8d333',
  },
  {
    nor: 'å riste',
    eng: 'to shake',
    pl: 'potrząsać',
    ar: 'هز',
    ger: 'schütteln',
    lt: 'kratyti',
    ua: 'трясти',
    sp: 'sacudir',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Friste.mp3?alt=media&token=9dc82054-15bb-4225-8a45-4af4a8007cb2',
  },
  {
    nor: 'å bekymre',
    eng: 'to worry',
    pl: 'martwić się',
    ar: 'القلق',
    ger: 'sich sorgen',
    lt: 'nerimauti',
    ua: 'турбувати',
    sp: 'preocupar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbekymre.mp3?alt=media&token=85b922c6-450d-4287-8f3e-7e4a7b23ec44',
  },
  {
    nor: 'å forlate',
    eng: 'to leave',
    pl: 'opuścić',
    ar: 'ترك',
    ger: 'verlassen',
    lt: 'palikti',
    ua: 'залишати',
    sp: 'abandonar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforlate.mp3?alt=media&token=14a6707a-ac19-475f-bc12-87ced5721a36',
  },
  {
    nor: 'å sukke',
    eng: 'to sigh',
    pl: 'wzdychać',
    ar: 'تنهد',
    ger: 'seufzen',
    lt: 'atsidegti',
    ua: 'зітхати',
    sp: 'suspirar',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsukke.mp3?alt=media&token=fc5cbfa7-8085-44d3-b5f5-d9b8d7ee1465',
  },
  {
    nor: 'å ignorere',
    eng: 'to ignore',
    pl: 'ignorować',
    ua: 'ігнорувати',
    ger: 'ignorieren',
    lt: 'ignoruoti',
    sp: 'ignorar',
    ar: 'يتجاهل',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fignorere2.mp3?alt=media&token=fa7d0be6-3607-4b15-9f4b-01d48960e6ae',
  },
  {
    nor: 'å foreslå',
    eng: 'to suggest',
    pl: 'sugerować',
    ua: 'запропонувати',
    ger: 'vorschlagen',
    lt: 'pasiūlyti',
    sp: 'sugerir',
    ar: 'يقترح',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforeslaa2.mp3?alt=media&token=6b361645-33b8-424c-9ccf-c11f7aee712e',
  },
  {
    nor: 'å kreve',
    eng: 'to require',
    pl: 'wymagać',
    ua: 'вимагати',
    ger: 'erfordern',
    lt: 'reikalauti',
    sp: 'requerir',
    ar: 'يتطلب',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkreve2.mp3?alt=media&token=fe67a0fc-e965-4dc9-a6f5-3b0f957102b6',
  },
  {
    nor: 'å forsyne',
    eng: 'to provide',
    pl: 'dostarczać',
    ua: 'забезпечувати',
    ger: 'versorgen',
    lt: 'aprūpinti',
    sp: 'proporcionar',
    ar: 'يزود',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforsyne2.mp3?alt=media&token=a0747591-bd96-4001-8394-25ff65ce58c8',
  },
  {
    nor: 'å arrangere',
    eng: 'to arrange',
    pl: 'zorganizować',
    ua: 'організувати',
    ger: 'arrangieren',
    lt: 'surengti',
    sp: 'organizar',
    ar: 'ينظم',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farrangere2.mp3?alt=media&token=980c92d9-f95e-4168-9472-8b6d7b691a1f',
  },
  {
    nor: 'å konsentrere',
    eng: 'to concentrate',
    pl: 'skupić się',
    ua: 'зосередитися',
    ger: 'sich konzentrieren',
    lt: 'susikoncentruoti',
    sp: 'concentrarse',
    ar: 'يركز',
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkonsentrere2.mp3?alt=media&token=09f60744-1937-412c-b112-7e4e3071fd31',
  },
  
]