export default dataObj = [

    {
        typeOfScreen: '3',
        correctAnswers: ['I går', 'hadde', 'vi', 'en interessant', 'diskusjon', 'i', 'klassen', 'om', 'historie.', 'Før', 'jeg', 'begynte', 'på', 'universitetet', 'har', 'jeg', 'aldri', 'tenkt', 'så', 'mye', 'på', 'dette', 'emnet.', 'Men', 'siden', 'jeg', 'startet', 'her', 'har', 'jeg', 'lært', 'utrolig', 'mye.'],
        wordsWithGaps: ['I går', '            ', 'vi', 'en interessant', 'diskusjon', 'i', 'klassen', 'om', 'historie.', 'Før', 'jeg', '            ', 'på', 'universitetet', 'har', 'jeg', '            ', 'tenkt', 'så', 'mye', 'på', 'dette', 'emnet.', 'Men', 'siden', 'jeg', 'startet', 'her', '            ', 'jeg', 'lært', 'utrolig', 'mye.', '!!!', 'har', 'aldri', 'hadde', 'begynte'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Forrige', 'uke', 'hadde', 'vi', 'en', 'test', 'og', 'jeg', 'fant', 'ut', 'at', 'jeg', 'hadde', 'forstått', 'mer', 'enn', 'jeg', 'trodde.', 'I dag', 'har', 'jeg', 'lest', 'flere', 'kapitler', 'i', 'læreboken', 'og', 'føler', 'meg', 'enda', 'bedre', 'forberedt', 'for', 'neste', 'forelesning.'],
        wordsWithGaps: ['Forrige', 'uke', '            ', 'vi', 'en', 'test', 'og', 'jeg', '            ', 'ut', 'at', 'jeg', 'hadde', '            ', 'mer', 'enn', 'jeg', 'trodde.', 'I dag', '            ', 'jeg', 'lest', 'flere', 'kapitler', 'i', 'læreboken', 'og', 'føler', 'meg', 'enda', 'bedre', '            ', 'for', 'neste', 'forelesning.', '!!!', 'har', 'forberedt', 'forstått', 'hadde', 'fant'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Da', 'jeg', 'var', 'yngre', 'hadde', 'jeg', 'ikke', 'så', 'mange', 'interesser.', 'Men', 'de', 'siste', 'årene', 'har', 'jeg', 'utviklet', 'en', 'lidenskap', 'for', 'fotografering.', 'I', 'sommer', 'reiste', 'jeg', 'rundt', 'i', 'Norge', 'og', 'tok', 'mange', 'flotte', 'bilder.', 'Siden', 'den', 'gangen', 'har', 'jeg', 'deltatt', 'i', 'flere', 'fotokonkurranser.'],
        wordsWithGaps: ['Da', 'jeg', '            ', 'yngre', '            ', 'jeg', 'ikke', 'så', 'mange', 'interesser.', 'Men', 'de', 'siste', 'årene', 'har', 'jeg', '            ', 'en', 'lidenskap', 'for', 'fotografering.', 'I', 'sommer', '            ', 'jeg', 'rundt', 'i', 'Norge', 'og', 'tok', 'mange', 'flotte', 'bilder.', 'Siden', 'den', 'gangen', '            ', 'jeg', 'deltatt', 'i', 'flere', 'fotokonkurranser.', '!!!', 'utviklet', 'reiste', 'hadde vært', 'har', 'var', 'hadde'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Før', 'jeg', 'flyttet', 'til', 'denne', 'byen', 'har', 'jeg', 'bodd', 'i', 'en', 'liten', 'landsby.', 'Livet', 'der', 'var', 'veldig', 'annerledes', 'enn', 'det', 'jeg', 'opplever', 'nå.', 'Siden', 'jeg', 'kom', 'hit', 'har', 'jeg', 'møtt', 'så', 'mange', 'nye', 'mennesker', 'og', 'hadde', 'mange', 'nye', 'opplevelser.'],
        wordsWithGaps: ['Før', 'jeg', '            ', 'til', 'denne', 'byen', 'har', 'jeg', '            ', 'i', 'en', 'liten', 'landsby.', 'Livet', 'der', '            ', 'veldig', 'annerledes', 'enn', 'det', 'jeg', 'opplever', 'nå.', 'Siden', 'jeg', 'kom', 'hit', '            ', 'jeg', 'møtt', 'så', 'mange', 'nye', 'mennesker', 'og', 'hadde', 'mange', '            ', 'opplevelser.', '!!!', 'har', 'nye', 'flyttet', 'kommet', 'var', 'bodd'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hvis', 'jeg', 'hadde', 'visst', 'om', 'din', 'ankomst', 'ville', 'jeg', 'ha', 'forberedt', 'en', 'varm', 'velkomst.', 'lineBreaker', 'Om', 'du', 'kunne', 'velge', 'å', 'bo', 'hvor', 'som', 'helst', 'i', 'verden', 'hvor', 'ville', 'det', 'være?'],
        wordsWithGaps: ['            ', 'jeg', '            ', 'visst', 'om', 'din', 'ankomst', 'ville', 'jeg', 'ha', '            ', 'en', 'varm', 'velkomst.', 'lineBreaker', 'Om', 'du', '            ', 'velge', 'å', 'bo', '            ', 'som', 'helst', 'i', 'verden', 'hvor', '            ', 'det', 'være?', '!!!', 'ville', 'Hvis', 'hvor', 'hadde', 'kunne', 'forberedt'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hadde', 'vi', 'visst', 'om', 'endringene', 'tidligere', 'skulle', 'vi', 'ha', 'informert', 'alle', 'interessentene.', 'lineBreaker', 'Dersom', 'du', 'hadde', 'fulgt', 'instruksjonene', 'nøye', 'ville', 'du', 'ikke', 'ha', 'opplevd', 'problemer.'],
        wordsWithGaps: ['            ', 'vi', '            ', 'om', 'endringene', 'tidligere', 'skulle', 'vi', 'ha', '            ', 'alle', 'interessentene.', 'lineBreaker', 'Dersom', 'du',  'hadde', 'fulgt', '            ', 'nøye', 'ville', 'du', 'ikke', 'ha', '            ', 'problemer.' , '!!!', 'opplevd', 'visst', 'instruksjonene', 'Hadde', 'informert'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Om', 'været', 'blir', 'bra', 'i', 'morgen', 'skal', 'vi', 'gå', 'på', 'tur.', 'lineBreaker', 'Hvis', 'jeg', 'hadde', 'hatt', 'mer', 'tid', 'ville', 'jeg', 'ha', 'studert', 'fransk.', 'lineBreaker', 'Skulle', 'du', 'ha', 'vunnet', 'i', 'lotteriet', 'hva', 'ville', 'du', 'ha', 'gjort', 'med', 'pengene?'],
        wordsWithGaps: ['Om', 'været', '            ', 'bra', 'i', 'morgen', '            ', 'vi', 'gå', 'på', 'tur.', 'lineBreaker', 'Hvis', 'jeg', '            ', 'hatt', 'mer', 'tid', 'ville', 'jeg', 'ha', '            ', 'fransk.', 'lineBreaker', 'Skulle', 'du', 'ha', '            ', 'i', 'lotteriet', '            ', 'ville', 'du', 'ha', 'gjort', 'med', 'pengene?', '!!!', 'studert', 'hva', 'blir', 'vunnet', 'hadde', 'skal'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Om', 'jeg', 'kunne', 'gjøre', 'alt', 'om', 'igjen', 'ville', 'jeg', 'valgt', 'en', 'annen', 'vei.', 'lineBreaker', 'Dersom', 'teknologien', 'fortsetter', 'å', 'utvikle', 'seg', 'med', 'dette', 'tempoet', 'vil', 'vår', 'hverdag', 'se', 'veldig', 'annerledes', 'ut.'],
        wordsWithGaps: ['Om', 'jeg', '            ', 'gjøre', 'alt', 'om', 'igjen', 'ville', 'jeg', '            ', 'en', '            ', 'vei.', 'lineBreaker', 'Dersom', 'teknologien', 'fortsetter', 'å', '            ', 'seg', 'med', 'dette', 'tempoet', 'vil', 'vår', '            ', 'se', 'veldig', 'annerledes', 'ut.', '!!!', 'utvikle', 'kunne', 'annen', 'valgt', 'hverdag'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['I går', 'hadde', 'vi', 'en interessant', 'diskusjon', 'i', 'klassen', 'om', 'historie.', 'Før', 'jeg', 'begynte', 'på', 'universitetet', 'har', 'jeg', 'aldri', 'tenkt', 'så', 'mye', 'på', 'dette', 'emnet.', 'Men', 'siden', 'jeg', 'startet', 'her', 'har', 'jeg', 'lært', 'utrolig', 'mye.'],
        wordsWithGaps: ['I går', '            ', 'vi', 'en interessant', 'diskusjon', 'i', 'klassen', 'om', 'historie.', 'Før', 'jeg', '            ', 'på', 'universitetet', 'har', 'jeg', '            ', 'tenkt', 'så', 'mye', 'på', 'dette', 'emnet.', 'Men', 'siden', 'jeg', 'startet', 'her', '            ', 'jeg', 'lært', 'utrolig', 'mye.', '!!!', 'har', 'aldri', 'hadde', 'begynte'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Forrige', 'uke', 'hadde', 'vi', 'en', 'test', 'og', 'jeg', 'fant', 'ut', 'at', 'jeg', 'hadde', 'forstått', 'mer', 'enn', 'jeg', 'trodde.', 'I dag', 'har', 'jeg', 'lest', 'flere', 'kapitler', 'i', 'læreboken', 'og', 'føler', 'meg', 'enda', 'bedre', 'forberedt', 'for', 'neste', 'forelesning.'],
        wordsWithGaps: ['Forrige', 'uke', '            ', 'vi', 'en', 'test', 'og', 'jeg', '            ', 'ut', 'at', 'jeg', 'hadde', '            ', 'mer', 'enn', 'jeg', 'trodde.', 'I dag', '            ', 'jeg', 'lest', 'flere', 'kapitler', 'i', 'læreboken', 'og', 'føler', 'meg', 'enda', 'bedre', '            ', 'for', 'neste', 'forelesning.', '!!!', 'har', 'forberedt', 'forstått', 'hadde', 'fant'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Da', 'jeg', 'var', 'yngre', 'hadde', 'jeg', 'ikke', 'så', 'mange', 'interesser.', 'Men', 'de', 'siste', 'årene', 'har', 'jeg', 'utviklet', 'en', 'lidenskap', 'for', 'fotografering.', 'I', 'sommer', 'reiste', 'jeg', 'rundt', 'i', 'Norge', 'og', 'tok', 'mange', 'flotte', 'bilder.', 'Siden', 'den', 'gangen', 'har', 'jeg', 'deltatt', 'i', 'flere', 'fotokonkurranser.'],
        wordsWithGaps: ['Da', 'jeg', '            ', 'yngre', '            ', 'jeg', 'ikke', 'så', 'mange', 'interesser.', 'Men', 'de', 'siste', 'årene', 'har', 'jeg', '            ', 'en', 'lidenskap', 'for', 'fotografering.', 'I', 'sommer', '            ', 'jeg', 'rundt', 'i', 'Norge', 'og', 'tok', 'mange', 'flotte', 'bilder.', 'Siden', 'den', 'gangen', '            ', 'jeg', 'deltatt', 'i', 'flere', 'fotokonkurranser.', '!!!', 'utviklet', 'reiste', 'hadde vært', 'har', 'var', 'hadde'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Før', 'jeg', 'flyttet', 'til', 'denne', 'byen', 'har', 'jeg', 'bodd', 'i', 'en', 'liten', 'landsby.', 'Livet', 'der', 'var', 'veldig', 'annerledes', 'enn', 'det', 'jeg', 'opplever', 'nå.', 'Siden', 'jeg', 'kom', 'hit', 'har', 'jeg', 'møtt', 'så', 'mange', 'nye', 'mennesker', 'og', 'hadde', 'mange', 'nye', 'opplevelser.'],
        wordsWithGaps: ['Før', 'jeg', '            ', 'til', 'denne', 'byen', 'har', 'jeg', '            ', 'i', 'en', 'liten', 'landsby.', 'Livet', 'der', '            ', 'veldig', 'annerledes', 'enn', 'det', 'jeg', 'opplever', 'nå.', 'Siden', 'jeg', 'kom', 'hit', '            ', 'jeg', 'møtt', 'så', 'mange', 'nye', 'mennesker', 'og', 'hadde', 'mange', '            ', 'opplevelser.', '!!!', 'har', 'nye', 'flyttet', 'kommet', 'var', 'bodd'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    }
];