export default dataObj = [
    {
        typeOfScreen: '3',
        correctAnswers: ['Mia', 'går', 'sakte', 'i', 'parken.', 'Hun', 'ser', 'ofte', 'på', 'blomstene', 'og', 'lytter', 'alltid', 'til', 'fuglene.', 'I', 'dag', 'finner', 'hun', 'en', 'katt', 'som', 'spinner', 'rolig', 'ved', 'et', 'tre.'],
        wordsWithGaps: ['Mia', '            ', 'sakte', 'i', 'parken.', 'Hun', 'ser', '            ', 'på', 'blomstene', 'og', '            ', 'alltid', 'til', 'fuglene.', 'I', 'dag', 'finner', 'hun', 'en', 'katt', 'som', 'spinner', '            ', 'ved', 'et', 'tre.', '!!!', 'lytter', 'rolig', 'går', 'ofte'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Petter', 'jobber', 'vanligvis', 'i', 'en', 'butikk', 'men', 'idag', 'er', 'han', 'syk.', 'Han', 'ligger', 'stille', 'i', 'sengen', 'og', 'ser', 'på', 'TV.', 'Han', 'drikker', 'te', 'og', 'håper', 'å', 'føle', 'seg', 'bedre', 'snart.', 'Utenfor', 'snør', 'det', 'rolig', 'og', 'barna', 'leker', 'lykkelig', 'i', 'snøen.'],
        wordsWithGaps: ['Petter', 'jobber', '            ', 'i', 'en', 'butikk', 'men', 'idag', 'er', 'han', 'syk.', 'Han', 'ligger', '            ', 'i', 'sengen', 'og', 'ser', 'på', 'TV.', 'Han', 'drikker', 'te', 'og', 'håper', 'å', 'føle', 'seg', '            ', 'snart.', 'Utenfor', 'snør', 'det', 'rolig', 'og', 'barna', 'leker', '            ', 'i', 'snøen.', '!!!', 'bedre', 'stille', 'vanligvis', 'lykkelig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Lars', 'står', 'tidlig', 'opp', 'hver', 'morgen', 'og', 'spiser', 'fort', 'frokost.', 'Han', 'jobber', 'hardt', 'på', 'kontoret', 'og', 'kommer', 'sent', 'hjem.', 'Om', 'kvelden', 'leker', 'han', 'ofte', 'med', 'sin', 'hund', 'og', 'leser', 'stille', 'før', 'han', 'sover.'],
        wordsWithGaps: ['Lars', 'står', '            ', 'opp', 'hver', 'morgen', 'og', 'spiser', 'fort', 'frokost.', 'Han', 'jobber', '            ', 'på', 'kontoret', 'og', 'kommer', '            ', 'hjem.', 'Om', 'kvelden', 'leker', 'han', '            ', 'med', 'sin', 'hund', 'og', 'leser', 'stille', 'før', 'han', 'sover.', '!!!', 'sent', 'ofte', 'hardt', 'raskt', 'tidlig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Anna', 'studerer', 'på', 'biblioteket.', 'Hun', 'snakker', 'sjelden', 'høyt', 'og', 'går', 'alltid', 'forsiktig', 'med', 'bøkene.', 'Hver', 'ettermiddag', 'spaserer', 'hun', 'langsomt', 'hjem', 'og', 'tenker', 'ofte', 'på', 'dagen.', 'Hun', 'sover', 'alltid', 'godt', 'etter', 'en', 'produktiv', 'dag.'],
        wordsWithGaps: ['Anna', 'studerer', 'på', 'biblioteket.', 'Hun', 'snakker', '            ', 'høyt', 'og', 'går', '            ', 'forsiktig', 'med', 'bøkene.', 'Hver', 'ettermiddag', 'spaserer', 'hun', '            ', 'hjem', 'og', 'tenker', 'ofte', 'på', 'dagen.', 'Hun', 'sover', 'alltid', 'godt', 'etter', 'en', '            ', 'dag.', '!!!', 'produktiv', 'sjelden', 'langsomt', 'alltid',],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Ole', 'går', 'vanligvis', 'til', 'skolen', 'men', 'idag', 'sykler', 'han', 'raskt', 'fordi', 'han', 'våknet', 'sent', '.', 'På', 'skolen', 'svarer', 'han', 'alltid', 'nøye', 'på', 'lærerens', 'spørsmål.', 'Etter', 'skolen', 'spiller', 'han', 'fotball', 'med', 'vennene', 'sine.', 'Hjemme', 'hjelper', 'han', 'gjerne','med', 'middagen.'],
        wordsWithGaps: ['Ole', 'går', '            ', 'til', 'skolen', 'men', 'idag', 'sykler', 'han', '            ', 'fordi', 'han', 'våknet', '            ', '.', 'På', 'skolen', 'svarer', 'han', 'alltid', '            ', 'på', 'lærerens', 'spørsmål.', 'Etter', 'skolen', 'spiller', 'han', 'fotball', 'med', 'vennene', 'sine.', 'Hjemme', 'hjelper', 'han', '            ', 'med', 'middagen.', '!!!', 'sent', 'gjerne', 'raskt', 'vanligvis', 'nøye'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Kari', 'leser', 'stille', 'på', 'biblioteket.', 'Hun', 'skriver', 'alltid', 'nøye', 'notater.', 'Etter', 'timene', 'snakker', 'hun', 'ofte', 'med', 'vennene', 'sine', 'om', 'lekser.', 'Hun', 'går', 'raskt', 'hjem', 'og', 'spiser', 'middag', 'tidlig', 'med', 'familien', 'sin.'],
        wordsWithGaps: ['Kari', 'leser', 'stille', 'på', 'biblioteket.', 'Hun', 'skriver', 'alltid', '            ', 'notater.', 'Etter', 'timene', 'snakker', 'hun', '            ', 'med', 'vennene', 'sine', 'om', 'lekser.', 'Hun', 'går', '            ', 'hjem', 'og', 'spiser', 'middag', '            ', 'med', 'familien', 'sin.', '!!!', 'ofte', 'nøye', 'tidlig', 'raskt'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Magnus', 'spiser', 'frokost', 'på', 'kjøkkenet', 'hver', 'morgen.', 'I', 'dag', 'går', 'han', 'til', 'jobben', 'under', 'den', 'klare', 'himmelen.', 'Han', 'jobber', 'effektivt', 'og', 'fullfører', 'oppgavene', 'før', 'lunsj.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'på', 'en', 'kafé', 'i', 'byen.', 'De', 'diskuterer', 'ofte', 'politikk', 'og', 'sport', '.'],
        wordsWithGaps: ['Magnus', 'spiser', 'frokost', 'på', 'kjøkkenet', '            ', 'morgen.', 'I', 'dag', 'går', 'han', 'til', 'jobben', '            ', 'den', 'klare', 'himmelen.', 'Han', 'jobber', '            ', 'og', 'fullfører', 'oppgavene', '            ', 'lunsj.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'på', 'en', 'kafé', 'i', 'byen.', 'De', 'diskuterer', '            ', 'politikk', 'og', 'sport', '.', '!!!', 'sjelden', 'hver', 'før', 'ofte', 'effektivt', 'under'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Lars', 'bor', 'i', 'en', 'liten', 'by', 'ved', 'havet.', 'Hver', 'morgen', 'ser', 'han', 'den', 'fantastiske', 'soloppgangen', 'mens', 'han', 'drikker', 'sin', 'kaffe.', 'Han', 'jobber', 'som', 'fisker', 'og', 'drar', 'tidlig', 'ut', 'med', 'sin', 'gamle', 'båt.', 'På', 'kveldene', 'går', 'han', 'ofte', 'lange', 'turer', 'langs', 'den', 'sanddekte', 'stranden.'],
        wordsWithGaps: ['Lars', 'bor', 'i', 'en', 'liten', 'by', '            ', 'havet.', 'Hver', 'morgen', 'ser', 'han', 'den', 'fantastiske', 'soloppgangen', '            ', 'han', 'drikker', 'sin', 'kaffe.', 'Han', 'jobber', 'som', 'fisker', 'og', 'drar', '            ', 'ut', 'med', 'sin', '            ', 'båt.', 'På', 'kveldene', 'går', 'han', 'ofte', '            ', 'turer', 'langs', 'den', 'sanddekte', 'stranden.', '!!!',  'gamle', 'mens', 'ved', 'lange', 'tidlig'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Jeg', 'går', 'til', 'butikken', 'og', 'kjøper', 'brød.', 'På', 'veien', 'hjem', 'ser', 'jeg', 'en', 'katt', 'som', 'leker', 'i', 'parken.', 'Når', 'jeg', 'kommer', 'hjem', 'lager', 'jeg', 'kaffe', 'og', 'leser', 'avisen.'],
        wordsWithGaps: ['Jeg', '            ', 'til', 'butikken', 'og', '            ', 'brød.', 'På', 'veien', 'hjem', '            ', 'jeg', 'en', 'katt', 'som', '            ', 'i', 'parken.', 'Når', 'jeg', 'kommer', 'hjem', '            ', 'jeg', 'kaffe', 'og', '            ', 'avisen.', '!!!', 'leser', 'ser', 'leker', 'går', 'lager', 'kjøper'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Marius', 'bor', 'i', 'Oslo', 'og', 'jobber', 'som', 'lærer.', 'Hver', 'dag', 'går', 'han', 'til', 'skolen', 'og', 'underviser', 'barna.', 'Etter', 'jobb', 'møter', 'han', 'venner', 'eller', 'trener', 'i', 'gymmen.'],
        wordsWithGaps: ['Marius', '            ', 'i', 'Oslo', 'og', '            ', 'som', 'lærer.', 'Hver', 'dag', '            ', 'han', 'til', 'skolen', 'og', '            ', 'barna.', 'Etter', 'jobb', '            ', 'han', 'venner', 'eller', '            ', 'i', 'gymmen.', '!!!', 'trener', 'jobber', 'underviser',  'bor', 'møter', 'går'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Emma', 'reiser', 'til', 'jobben', 'med', 'buss.', 'Hun', 'elsker', 'å', 'lytte', 'til', 'musikk', 'mens', 'hun', 'venter.', 'På', 'kontoret', 'snakker', 'hun', 'med', 'kollegaer', 'og', 'drikker', 'kaffe.'],
        wordsWithGaps: ['Emma', '            ', 'til', 'jobben', 'med', 'buss.', 'Hun', '            ', 'å', 'lytte', 'til', 'musikk', 'mens', 'hun', 'venter.', 'På', 'kontoret', '            ', 'hun', 'med', 'kollegaer', 'og', '            ', 'kaffe.', '!!!', 'snakker', 'spiser', 'elsker', 'drikker', 'reiser'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Lars', 'står', 'opp', 'tidlig', 'og', 'lager', 'frokost.', 'Han', 'leser', 'avisen', 'og', 'drikker', 'te.', 'Etterpå', 'går', 'han', 'ut', 'med', 'hunden', 'sin.', 'Om', 'kvelden', 'ser', 'han', 'på', 'TV', 'eller', 'leser', 'en', 'bok.'],
        wordsWithGaps: ['Lars', '            ', 'opp', 'tidlig', 'og', '            ', 'frokost.', 'Han', 'leser', 'avisen', 'og', '            ', 'te.', 'Etterpå', '            ', 'han', 'ut', 'med', 'hunden', 'sin.', 'Om', 'kvelden', '            ', 'han', 'på', 'TV', 'eller', '            ', 'en', 'bok.', '!!!', 'ser', 'drikker', 'lager', 'leser', 'går', 'står'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Sofia', 'jobber', 'som', 'grafisk', 'designer', 'og', 'skaper', 'reklamer.', 'Hun', 'bruker', 'mange', 'timer', 'på', 'datamaskinen', 'hver', 'dag.', 'I', 'pausene', 'snakker', 'hun', 'med', 'venner', 'på', 'telefonen', 'og', 'spiser', 'lunsj.'],
        wordsWithGaps: ['Sofia', '            ', 'som', 'grafisk', 'designer', 'og', '            ', 'reklamer.', 'Hun', '            ', 'mange', 'timer', 'på', 'datamaskinen', 'hver', 'dag.', 'I', 'pausene', '            ', 'hun', 'med', 'venner', 'på', 'telefonen', 'og', '            ', 'lunsj.', '!!!', 'snakker', 'jobber', 'tenker', 'bruker', 'spiser', 'skaper'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Erik', 'reiser', 'med', 'tog', 'til', 'arbeidet', 'hver', 'morgen.', 'Han', 'nyter', 'utsikten', 'og', 'lytter', 'til', 'podcaster.', 'På', 'ettermiddagen', 'går', 'han', 'på', 'kafé', 'og', 'møter', 'venner.'],
        wordsWithGaps: ['Erik', '            ', 'med', 'tog', 'til', 'arbeidet', 'hver', 'morgen.', 'Han', '            ', 'utsikten', 'og', '            ', 'til', 'podcaster.', 'På', 'ettermiddagen', '            ', 'han', 'på', 'kafé', 'og', '            ', 'venner.', '!!!', 'lytter', 'får', 'går' , 'møter', 'nyter', 'reiser'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Anna', 'studerer', 'biologi.', 'Hun', 'deltar', 'i', 'forskjellige', 'prosjekter', 'og', 'skriver', 'rapporter.', 'Etter', 'forelesninger', 'treffer', 'hun', 'vennene', 'sine', 'på', 'biblioteket', 'for', 'å', 'lese', 'sammen.'],
        wordsWithGaps: ['Anna', '            ', 'biologi.', 'Hun', '            ', 'i', 'forskjellige', 'prosjekter', 'og', '            ', 'rapporter.', 'Etter', 'forelesninger', '            ', 'hun', 'vennene', 'sine', 'på', 'biblioteket', 'for', 'å', '            ', 'sammen.', '!!!', 'treffer', 'lese', 'bor', 'deltar', 'skriver', 'studerer'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: [
            'En', 'dag', 'gikk', 'en', 'katt', 'i', 'skogen.', 
            'Denne', 'katten', 'så', 'et', 'tre.', 
            'På', 'treet', 'var', 'det', 'en', 'fugl.', 
            'Fuglen', 'sang', 'en', 'vakker', 'melodi.', 
            'Katten', 'lyttet', 'og', 'smilte.'
        ],
        wordsWithGaps: [
            'En', 'dag', 'gikk', '            ', 'katt', 'i', 'skogen.', 
            '            ',  'katten', 'så', '            ', 'tre.', 
            'På', 'treet', 'var', 'det', 'en', 'fugl.', 
            'Fuglen', 'sang', '            ', 'vakker', 'melodi.', 
            'Katten', 'lyttet', '            ', 'smilte.', '!!!', 'og', 'et', 'en', 'Denne', 'en'
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Mina', 'og', 'broren', 'hennes', 'gikk', 'til', 'butikken.', 'Hun', 'ville', 'kjøpe', 'epler,', 'men', 'han', 'ønsket', 'å', 'kjøpe', 'appelsiner.', 'Da', 'de', 'kom', 'tilbake', 'hjem,', 'mor', 'deres', 'sa', 'at', 'de', 'hadde', 'glemt', 'å', 'kjøpe', 'melk.', 'De', 'lo', 'og', 'bestemte', 'seg', 'for', 'å', 'gå', 'tilbake', 'sammen.'],
        wordsWithGaps: ['Mina', 'og', 'broren', '            ', 'gikk', 'til', 'butikken.', 'Hun', 'ville', 'kjøpe', 'epler,', 'men', '            ', 'ønsket', 'å', 'kjøpe', 'appelsiner.', 'Da', '            ', 'kom', 'tilbake', 'hjem,', 'mor', '            ', 'sa', 'at', '            ', 'hadde', 'glemt', 'å', 'kjøpe', 'melk.', 'De', 'lo', 'og', 'bestemte', '            ', 'for', 'å', 'gå', 'tilbake', 'sammen.', '!!!', 'de', 'seg', 'hennes', 'de', 'deres', 'han'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: [
            'Maria', 'og', 'hennes', 'venn', 'Petter', 'gikk', 'til', 'butikken.', 
            'Hun', 'kjøpte', 'et', 'eple', 'og', 'han', 'kjøpte', 'en', 'banan.', 
            'Da', 'de', 'var', 'på', 'vei', 'hjem,', 'møtte', 'de', 'deres', 'lærer.', 
            'Han', 'hilst', 'på', 'dem', 'og', 'spurte', 'hvordan', 'det', 'gikk.', 
            'De', 'svarte', 'at', 'alt', 'var', 'bra', 'og', 'fortsatte', 'hjemturen.'
        ],
        wordsWithGaps: [
            'Maria', 'og', '            ', 'venn', 'Petter', 'gikk', 'til', 'butikken.', 
            'Hun','kjøpte', 'et', 'eple', 'og', '            ', 'kjøpte', 'en', 'banan.', 
            'Da', 'de', 'var', 'på', 'vei', 'hjem,', 'møtte', 'de', '            ', 'lærer.', 
            'Han', 'hilst', 'på', 'dem', 'og', 'spurte', 'hvordan', 'det', 'gikk.', 
            '            ', 'svarte', 'at', 'alt', 'var', 'bra', 'og', 'fortsatte', 'hjemturen.',
            '!!!', 'deres', 'De', 'hennes', 'han', 'meg'
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Mia', 'spiser', 'ikke', 'frokost', 'fordi', 'hun', 'ikke', 'er', 'sulten.', 'lineBreaker', 'Hvorfor', 'går', 'hun', 'ikke', 'på', 'jobb?', 'lineBreaker', 'Fordi', 'hun', 'jobber', 'hjemmefra', 'i', 'dag.'],
        wordsWithGaps: ['Mia', '            ', 'ikke', 'frokost', 'fordi', 'hun', '            ', 'er', 'sulten.', 'lineBreaker', '            ', 'går', 'hun', '            ', 'på', 'jobb?', 'lineBreaker', '            ', 'hun', 'jobber', '            ', 'i', 'dag.', '!!!', 'hjemmefra', 'ikke', 'spiser', 'Hvorfor', 'ikke', 'Fordi'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hvor', 'bor', 'du?', 'Jeg', 'bor', 'i', 'Oslo', '.', 'lineBreaker', 'Jobber', 'du', 'i', 'dag?', 'Nei', ',', 'jeg', 'jobber', 'ikke', 'i', 'dag', 'fordi', 'jeg', 'er', 'syk', '.'],
        wordsWithGaps: ['            ', 'bor', 'du?', 'Jeg', 'bor', 'i', '            ', '.', 'lineBreaker', '            ', 'du', 'i', 'dag?', '            ', ',', 'jeg', 'jobber', '            ', 'i', 'dag', 'fordi', 'jeg', 'er', '            ', '.', '!!!', 'Oslo', 'Nei', 'ikke', 'syk', 'Hvor', 'Jobber'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Liker', 'du', 'å', 'lese', 'bøker?', 'Ja,', 'jeg', 'liker', 'å', 'lese.', 'lineBreaker', 'Spiser', 'du', 'ofte', 'frokost?', 'Nei,', 'jeg', 'spiser', 'ikke', 'frokost', 'fordi', 'jeg', 'er', 'aldri', 'sulten', 'om', 'morgenen.'],
        wordsWithGaps: ['            ', 'du', 'å', 'lese', 'bøker?', 'Ja,', 'jeg', 'liker', 'å', 'lese.', 'lineBreaker', 'Spiser', 'du', '            ', 'frokost?', 'Nei,', 'jeg', 'spiser', '            ', 'frokost', 'fordi', 'jeg', 'er', 'aldri', 'sulten', '            ', 'morgenen.', '!!!', 'ofte', 'om', 'ikke', 'Liker', 'drikker'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hvorfor', 'kommer', 'du', 'sent', 'til', 'møtet', '?', 'Jeg', 'kommer', 'sent', 'fordi', 'bussen', 'min', 'var', 'forsinket', '.', 'Tror', 'du', 'vi', 'vil', 'rekke', 'å', 'diskutere', 'alt', 'i', 'dag', '?', 'Kanskje', 'ikke', ',', 'men', 'vi', 'skal', 'prøve', 'å', 'være', 'effektive', '.'],
        wordsWithGaps: ['            ', 'kommer', 'du', 'sent', 'til', '            ', '?', 'Jeg', '            ', 'sent', 'fordi', 'bussen', 'min', 'var', '            ', '.', '            ', 'du', 'vi', 'vil', '            ', 'å', 'diskutere', 'alt', 'i', 'dag', '?', '            ', 'ikke', ',', 'men', 'vi', 'skal', '            ', 'å', 'være', 'effektive', '.', '!!!', 'Kanskje', 'prøve', 'Hvorfor', 'forsinket', 'møtet', 'rekke', 'kommer', 'Tror'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hvordan', 'kan', 'jeg', 'hjelpe', 'deg', 'i', 'dag', '?', 'Kan', 'du', 'hjelpe', 'meg', 'med', 'leksene', 'mine', '?', 'Selvfølgelig', ',', 'jeg', 'vil', 'gjerne', 'hjelpe', '.', 'lineBreaker', 'Har', 'du', 'noen', 'planer', 'for', 'helgen', '?', 'Nei', ',', 'jeg', 'har', 'ikke', 'noen', 'spesielle', 'planer', '.'],
        wordsWithGaps: ['            ', 'kan', 'jeg', 'hjelpe', 'deg', 'i', '            ', '?', 'Kan', 'du', 'hjelpe', 'meg', '            ', 'leksene', 'mine', '?', '            ', ',', 'jeg', 'vil', 'gjerne', 'hjelpe', '.', 'lineBreaker', '            ', 'du', 'noen', 'planer', 'for', 'helgen', '?', 'Nei', ',', 'jeg', 'har', '            ', 'noen', '            ', 'planer', '.', '!!!', 'ikke', 'dag', 'spesielle', 'Hvordan',  'Selvfølgelig', 'med',  'Har'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Hvor', 'lært', 'du', 'norsk?', 'Jeg', 'lærer', 'norsk', 'på', 'et', 'språkskole.', 'Synes', 'du', 'det', 'er', 'vanskelig?', 'Til', 'tider,', 'men', 'jeg', 'synes', 'det', 'er', 'gøy.', 'Går', 'du', 'på', 'kurs', 'hver', 'dag?', 'Nei,', 'jeg', 'går', 'ikke', 'hver', 'dag,', 'bare', 'tre', 'ganger', 'i', 'uken.'],
        wordsWithGaps: ['            ', 'lært', 'du', 'norsk?', 'Jeg', '            ', 'norsk', 'på', 'et', 'språkskole.', '            ', 'du', 'det', 'er', 'vanskelig?', 'Til', 'tider,', 'men', 'jeg', 'synes', 'det', 'er', 'gøy.', 'Går', 'du', 'på', '            ', 'hver', 'dag?', 'Nei,', 'jeg', 'går', '            ', 'hver', 'dag,', '            ', 'tre', 'ganger', 'i', 'uken.', '!!!', 'ikke', 'lærer', 'kurs', 'Synes', 'bare', 'Hvor'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    }
];