export default dataObj = [

    {
        typeOfScreen: '3',
        correctAnswers: ['Erik', 'og', 'Ingrid', 'reiser', 'snart', 'til', 'Spania.', 'De', 'pakker', 'nøye', 'sine', 'kofferter', 'og', 'planlegger', 'reisen', 'grundig.', 'De', 'reiser', 'vanligvis', 'lett', 'men', 'denne', 'gangen', 'tar', 'de', 'med', 'mer', '.', 'På', 'flyplassen', 'sjekker', 'de', 'inn', 'raskt', 'og', 'venter', 'tålmodig', 'på', 'avgang.'],
        wordsWithGaps: ['Erik', 'og', 'Ingrid', 'reiser', '            ', 'til', 'Spania.', 'De', 'pakker',  'nøye', 'sine', 'kofferter', 'og', 'planlegger', 'reisen', 'grundig.', 'De', 'reiser', '            ', 'lett', 'men', 'denne', 'gangen', 'tar', 'de', 'med', '            ',  '.', 'På', 'flyplassen', 'sjekker', 'de', 'inn', '            ', 'og', 'venter', '            ', 'på', 'avgang.', '!!!', 'mer', 'snart', 'tålmodig', 'vanligvis', 'raskt'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3', 
        correctAnswers: ['Sofia', 'våkner', 'tidlig', 'på', 'morgenen', 'og', 'ser', 'ut', 'av', 'vinduet', 'mot', 'den', 'nye', 'dagen.', 'Hun', 'spiser', 'frokost', 'alene', 'i', 'stua.', 'På', 'skolen', 'lærer', 'hun', 'og', 'deltar', 'aktivt', 'i', 'timene.', 'Etter', 'skoletid', 'går', 'hun', 'til', 'biblioteket', 'for', 'å', 'lese', 'eller', 'studere.', 'Hjemme', 'snakker', 'hun', 'med', 'foreldrene', 'sine', 'om', 'dagen.'],
        wordsWithGaps: ['Sofia', 'våkner', '            ', 'på', 'morgenen', 'og', 'ser', 'ut', 'av', 'vinduet', 'mot', 'den', '            ', 'dagen.', 'Hun', 'spiser', 'frokost', 'alene', 'i', 'stua.', 'På', 'skolen', 'lærer', 'hun', 'og', 'deltar', '            ', 'i', 'timene.', 'Etter', 'skoletid', 'går', 'hun', 'til', 'biblioteket', '            ', 'å', 'lese', 'eller', 'studere.', 'Hjemme', 'snakker', 'hun', '            ', 'foreldrene', 'sine', 'om', 'dagen.', '!!!', 'for', 'nye', 'tidlig', 'med', 'rundt', 'aktivt'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3', 
        correctAnswers: ['Henrik', 'går', 'vanligvis', 'til', 'jobb', 'gjennom', 'parken.', 'På', 'kontoret', 'jobber', 'han', 'fokusert', 'og', 'snakker', 'sjelden', 'i', 'telefonen.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'i', 'byen', 'til', 'en', 'middag', 'ute', '.', 'De', 'diskuterer', 'samfunnsspørsmål', 'intenst', 'og', 'nyter', 'kvelden.'],
        wordsWithGaps: ['Henrik', 'går', '            ', 'til', 'jobb', '            ', 'parken.', 'På', 'kontoret', 'jobber', 'han', '            ', 'og', 'snakker', '            ', 'i', 'telefonen.', 'Etter', 'arbeid', 'møter', 'han', 'venner', 'i', 'byen', 'til', 'en', 'middag', '            ', '.', 'De', 'diskuterer', 'samfunnsspørsmål', '            ', 'og', 'nyter', 'kvelden.', '!!!', 'ute', 'vanligvis', 'sjelden', 'gjennom', 'intenst', 'fokusert'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3', 
        correctAnswers: ['Martin', 'studerer', 'på', 'universitetet', 'hver', 'dag.', 'Vanligvis', 'tar', 'han', 'bussen', 'men', 'i', 'dag', 'går', 'han', 'på', 'grunn', 'av', 'streik.', 'I', 'biblioteket', 'jobber', 'han', 'konsentrert', 'og', 'holder', 'seg', 'unna', 'telefonen.', 'Etter', 'studier', 'møtes', 'han', 'og', 'vennene', 'i', 'parken', 'og', 'spiser', 'lunsj', 'sammen', '.', 'Hjemme', 'om', 'kvelden', 'ser', 'han', 'på', 'film', 'med', 'familien.'],
        wordsWithGaps: ['Martin', 'studerer', 'på', 'universitetet', '            ', 'dag.', 'Vanligvis', 'tar', 'han', 'bussen', 'men', 'i', 'dag', 'går', 'han', 'på', 'grunn', 'av', 'streik.', 'I', 'biblioteket', 'jobber', 'han', '            ', 'og', 'holder', 'seg', '            ', 'telefonen.', 'Etter', 'studier', 'møtes', 'han', 'og', 'vennene', 'i', 'parken', 'og', 'spiser', 'lunsj', '            ', '.', 'Hjemme', '            ', 'kvelden', 'ser', 'han', 'på', 'film', 'med', 'familien.', '!!!', 'hver', 'til', 'konsentrert', 'unna', 'sammen', 'om'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3', 
        correctAnswers: ['Eva', 'jobber', 'hjemmefra', 'i', 'dag', 'på', 'grunn', 'av', 'en', 'forkjølelse.', 'Hun', 'starter', 'tidlig', 'og', 'arbeider', 'effektivt', 'gjennom', 'morgenen.', 'Til', 'lunsj', 'spiser', 'hun', 'lett', 'mat', 'ute', 'på', 'balkongen.', 'Ettermiddagen', 'bruker', 'hun', 'til', 'å', 'svare', 'på', 'e-poster', 'og', 'planlegger', 'prosjekter', 'nøye', '.'],
        wordsWithGaps: ['Eva', 'jobber', '            ', 'i', 'dag', 'på', 'grunn', 'av', 'en', 'forkjølelse.', 'Hun', 'starter', '            ', 'og', 'arbeider', '            ', 'gjennom', 'morgenen.', 'Til', 'lunsj', 'spiser', 'hun', 'lett', 'mat', '            ', 'på', 'balkongen.', 'Ettermiddagen', 'bruker', 'hun', 'til', 'å', 'svare', 'på', 'e-poster', 'og', 'planlegger', 'prosjekter', '            ', '.', '!!!','effektivt', 'tidlig', 'hjemmefra', 'nøye', 'ute'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3', 
        correctAnswers: ['Den', 'lille', 'hunden', 'Luna', 'løper', 'glad', 'i', 'den', 'store', 'parken', 'hver', 'morgen.', 'Hun', 'er', 'veldig', 'leken.', 'Eieren', 'hennes', 'en', 'vennlig', 'gammel', 'mann', 'ser', 'på', 'med', 'et', 'smil.', 'Plutselig', 'begynner', 'det', 'å', 'regne', 'kraftig', 'og', 'de', 'søker', 'ly', 'under', 'et', 'tre.', 'Etter', 'regnet', 'går', 'de', 'hjem', 'langs', 'den', 'våte', 'stien.'],
        wordsWithGaps: ['Den', 'lille', 'hunden', 'Luna', 'løper', '            ', 'i', 'den', 'store', 'parken', '            ', 'morgen.', 'Hun', 'er', '            ', 'leken.', 'Eieren', 'hennes', 'en', '            ', 'gammel', 'mann', 'ser', 'på', 'med', 'et', 'smil.', 'Plutselig', 'begynner', 'det', 'å', 'regne', '            ', 'og', 'de', 'søker', 'ly', '            ', 'et', 'tre.', 'Etter', 'regnet', 'går', 'de', 'hjem', 'langs', 'den', '            ', 'stien.', '!!!', 'vennlig', 'kraftig', 'hver', 'våte', 'veldig', 'glad', 'under'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['I', 'den', 'kalde', 'vinteren', 'går', 'Emma', 'til', 'skolen', 'hver', 'dag.', 'Hun', 'har', 'på', 'seg', 'en', 'varm', 'jakke', 'og', 'tjukke', 'hansker.', 'I', 'klasserommet', 'er', 'det', 'heldigvis', 'varmt', 'og', 'koselig.', 'Hun', 'lytter', 'til', 'læreren', 'og', 'deltar', 'ivrig', 'i', 'diskusjonene.', 'På', 'vei', 'hjem', 'ser', 'hun', 'på', 'solnedgangen', 'over', 'den', 'frosne', 'elven.'],
        wordsWithGaps: ['I', 'den', '            ', 'vinteren', 'går', 'Emma', 'til', 'skolen', '            ', 'dag.', 'Hun', 'har', 'på', 'seg', 'en', '            ', 'jakke', 'og', '            ', 'hansker.', 'I', 'klasserommet', 'er', 'det', '            ', 'varmt', 'og', 'koselig.', 'Hun', 'lytter', 'til', 'læreren', 'og', 'deltar', '            ', 'i', 'diskusjonene.', 'På', 'vei', 'hjem', 'ser', 'hun', 'på', 'solnedgangen', 'over', 'den', '            ', 'elven.', '!!!', 'tjukke','ivrig', 'kalde', 'hver', 'frosne', 'varm', 'heldigvis'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: [],
    },
    
];