export default dataObj = [
    
  {
      nor: 'nøyaktig',
      eng: 'accurate',
      pl: 'dokładny',
      ar: 'دقيق',
      ger: 'genau',
      lt: 'tikslus',
      ua: 'точний',
      sp: 'exacto',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnooyaktig.mp3?alt=media&token=7f6d18e3-b611-45fa-a1c1-315412e9d484',
  },
  {
      nor: 'unøyaktig',
      eng: 'inaccurate',
      pl: 'niedokładny',
      ar: 'غير دقيق',
      ger: 'ungenau',
      lt: 'netikslus',
      ua: 'неточний',
      sp: 'inexacto',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Funooyaktig.mp3?alt=media&token=a9e542f8-9c44-44dd-9727-ff902219d78e',
  },
  {
      nor: 'ambisiøs',
      eng: 'ambitious',
      pl: 'ambitny',
      ar: 'طموح',
      ger: 'ehrgeizig',
      lt: 'ambicingas',
      ua: 'амбітний',
      sp: 'ambicioso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fambisioos.mp3?alt=media&token=0ae7bafb-3f5b-4032-b5b5-ff33fab5afae',
  },
  {
      nor: 'overfladisk',
      eng: 'superficial',
      pl: 'powierzchowny',
      ar: 'سطحي',
      ger: 'oberflächlich',
      lt: 'paviršutiniškas',
      ua: 'поверхневий',
      sp: 'superficial',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Foverfladisk.mp3?alt=media&token=58b33775-8033-422d-9c4b-6344200faae1',
  },
  {
      nor: 'selvsikker',
      eng: 'confident',
      pl: 'pewny siebie',
      ar: 'واثق',
      ger: 'selbstbewusst',
      lt: 'pasitikintis',
      ua: 'впевнений у собі',
      sp: 'seguro de sí mismo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselvsikker.mp3?alt=media&token=b3bf08a5-63e2-4f40-af6d-7df5c934c973',
  },
  {
      nor: 'følsom',
      eng: 'sensitive',
      pl: 'wrażliwy',
      ar: 'حساس',
      ger: 'empfindlich',
      lt: 'jautrus',
      ua: 'чутливий',
      sp: 'sensible',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffoolsom.mp3?alt=media&token=bf589058-726c-41b6-b77b-ef5b45d51187',
  },
  {
      nor: 'ufølsom',
      eng: 'insensitive',
      pl: 'niewrażliwy',
      ar: 'غير حساس',
      ger: 'unempfindlich',
      lt: 'nejausmus',
      ua: 'нечутливий',
      sp: 'insensible',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fufoolsom.mp3?alt=media&token=85375818-acf1-4176-b2e3-3c0182e3eb79',
  },
  {
      nor: 'usikker',
      eng: 'uncertain',
      pl: 'niepewny',
      ar: 'غير مؤكد',
      ger: 'unsicher',
      lt: 'neaiškus',
      ua: 'невпевнений',
      sp: 'inseguro',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fusikker.mp3?alt=media&token=5127e8c9-f607-404b-8ca2-ef40259e4c99',
  },
  {
      nor: 'misfornøyd',
      eng: 'dissatisfied',
      pl: 'niezadowolony',
      ar: 'غير راض',
      ger: 'unzufrieden',
      lt: 'nepatenkintas',
      ua: 'незадоволений',
      sp: 'insatisfecho',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmisfornooyd.mp3?alt=media&token=97902a24-daf0-4c40-accf-8e3e3130f729',
  },
  {
      nor: 'sjalu',
      eng: 'jealous',
      pl: 'zazdrosny',
      ar: 'غيور',
      ger: 'eifersüchtig',
      lt: 'pavydus',
      ua: 'ревнивий',
      sp: 'celoso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjalu.mp3?alt=media&token=9498cfb8-88c6-4bb0-9909-3d165caa96a9',
  },
  {
      nor: 'falsk',
      eng: 'false',
      pl: 'fałszywy',
      ar: 'كاذب',
      ger: 'falsch',
      lt: 'netikras',
      ua: 'несправжній',
      sp: 'falso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffalsk.mp3?alt=media&token=f05d43d1-9726-440b-a0d7-d211fed47d67',
  },
  {
      nor: 'respektfull',
      eng: 'respectful',
      pl: 'pełen szacunku',
      ar: 'محترم',
      ger: 'respektvoll',
      lt: 'gerbiantis',
      ua: 'шанобливий',
      sp: 'respetuoso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frespektfull.mp3?alt=media&token=1bb86b6c-bd85-498f-84b1-470ae4983fde',
  },
  {
      nor: 'respektløs',
      eng: 'disrespectful',
      pl: 'lekceważący',
      ar: 'غير محترم',
      ger: 'respektlos',
      lt: 'nepagarbus',
      ua: 'нешанобливий',
      sp: 'irrespetuoso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frespektloos.mp3?alt=media&token=3dfc4157-0535-4fbc-a090-e20bda4e9ca0',
  },
  {
      nor: 'sjenerøs',
      eng: 'generous',
      pl: 'hojny',
      ar: 'كريم',
      ger: 'großzügig',
      lt: 'dosnus',
      ua: 'щедрий',
      sp: 'generoso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjeneroos.mp3?alt=media&token=5e4e178d-3387-42f7-aa39-a09d2c160245',
  },
  {
      nor: 'uvanlig',
      eng: 'unusual',
      pl: 'niezwykły',
      ar: 'غير عادي',
      ger: 'ungewöhnlich',
      lt: 'neįprastas',
      ua: 'незвичайний',
      sp: 'inusual',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuvanlig.mp3?alt=media&token=e5e4e61d-cad6-4381-b4ff-1f3beca5779b',
  },
  {
      nor: 'vanlig',
      eng: 'usual',
      pl: 'zwykły',
      ar: 'عادي',
      ger: 'üblich',
      lt: 'įprastas',
      ua: 'звичайний',
      sp: 'común',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvanlig.mp3?alt=media&token=de651bd9-1d43-4bde-b901-2f5ff86e7b14',
  },
  {
      nor: 'ansvarlig',
      eng: 'responsible',
      pl: 'odpowiedzialny',
      ar: 'مسؤول',
      ger: 'verantwortlich',
      lt: 'atsakingas',
      ua: 'відповідальний',
      sp: 'responsable',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fansvarlig.mp3?alt=media&token=7fea835e-d6e4-4fde-a9b2-afac3920084a',
  },
  {
      nor: 'uansvarlig',
      eng: 'irresponsible',
      pl: 'nieodpowiedzialny',
      ar: 'غير مسؤول',
      ger: 'unverantwortlich',
      lt: 'neatsakingas',
      ua: 'не відповідальний',
      sp: 'irresponsable',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fuansvarlig.mp3?alt=media&token=27775147-bb88-425d-b475-d4a9dc03e727',
  },
  {
      nor: 'tilfreds',
      eng: 'satisfied',
      pl: 'zadowolony',
      ar: 'راض',
      ger: 'zufrieden',
      lt: 'patenkintas',
      ua: 'задоволений',
      sp: 'satisfecho',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftilfreds.mp3?alt=media&token=0cbe55ed-0c10-44db-985e-8d916a86da55',
  },
  {
      nor: 'flat',
      eng: 'flat',
      pl: 'płaski',
      ar: 'مسطح',
      ger: 'flach',
      lt: 'plokščias',
      ua: 'плоский',
      sp: 'plano',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fflat.mp3?alt=media&token=93edf19e-da06-4b5a-97d4-2541b4c118ba',
  },
  {
      nor: 'rund',
      eng: 'round',
      pl: 'okrągły',
      ar: 'مستدير',
      ger: 'rund',
      lt: 'apvalus',
      ua: 'круглий',
      sp: 'redondo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Frund.mp3?alt=media&token=84424bbf-c372-46b4-a005-20d4caf1c3cc',
  },
  {
      nor: 'solid',
      eng: 'solid',
      pl: 'solidny',
      ar: 'صلب',
      ger: 'solide',
      lt: 'tvirtas',
      ua: 'міцний',
      sp: 'sólido',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsolid.mp3?alt=media&token=7732e352-7f20-45fc-b7d5-8206ffe7df71',
  },
  {
      nor: 'spontan',
      eng: 'spontaneous',
      pl: 'spontaniczny',
      ar: 'عفوي',
      ger: 'spontan',
      lt: 'spontaniškas',
      ua: 'спонтанний',
      sp: 'espontáneo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspontan.mp3?alt=media&token=993b6f0f-6639-4c55-8bec-4c82b565586b',
  },
  {
      nor: 'forutsigbar',
      eng: 'predictable',
      pl: 'przewidywalny',
      ar: 'يمكن التنبؤ به',
      ger: 'vorhersehbar',
      lt: 'numatomas',
      ua: 'передбачуваний',
      sp: 'predecible',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fforutsigbar.mp3?alt=media&token=520d5acf-09ee-4388-a585-5284daac3ece',
  },
  {
      nor: 'grundig',
      eng: 'thorough',
      pl: 'gruntowny',
      ar: 'دقيق',
      ger: 'gründlich',
      lt: 'išsamus',
      ua: 'грунтовний',
      sp: 'minucioso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrundig.mp3?alt=media&token=ca45dbe4-9184-4132-8fe3-bbfd90a4435c',
  },
  {
      nor: 'fleksibel',
      eng: 'flexible',
      pl: 'elastyczny',
      ar: 'مرن',
      ger: 'flexibel',
      lt: 'lankstus',
      ua: 'гнучкий',
      sp: 'flexible',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffleksibel.mp3?alt=media&token=9bfed043-b467-4da7-a0aa-4bb6354b1bd7',
  },
  {
      nor: 'stiv',
      eng: 'stiff',
      pl: 'sztywny',
      ar: 'جامد',
      ger: 'steif',
      lt: 'kietas',
      ua: 'жорсткий',
      sp: 'rígido',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstiv.mp3?alt=media&token=4f8836be-b61f-4107-a38d-0559e394a500',
  },
  {
      nor: 'åpen',
      eng: 'open',
      pl: 'otwarty',
      ar: 'مفتوح',
      ger: 'offen',
      lt: 'atviras',
      ua: 'відкритий',
      sp: 'abierto',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faapen.mp3?alt=media&token=0095f888-ff57-41b1-82fc-00fe86e8217a',
  },
  {
      nor: 'lukket',
      eng: 'closed',
      pl: 'zamknięty',
      ar: 'مغلق',
      ger: 'geschlossen',
      lt: 'uždarytas',
      ua: 'закритий',
      sp: 'cerrado',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flukket.mp3?alt=media&token=2b8541a0-30e8-4950-83d5-e03c2d0811a8',
  },
  {
      nor: 'misfornøyd',
      eng: 'dissatisfied',
      pl: 'niezadowolony',
      ar: 'غير راض',
      ger: 'unzufrieden',
      lt: 'nepatenkintas',
      ua: 'незадоволений',
      sp: 'insatisfecho',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmisfornooyd.mp3?alt=media&token=97902a24-daf0-4c40-accf-8e3e3130f729',
  },
  {
      nor: 'dum',
      eng: 'stupid',
      pl: 'głupi',
      ar: 'غبي',
      ger: 'dumm',
      lt: 'kvailas',
      ua: 'дурний',
      sp: 'tonto',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdum.mp3?alt=media&token=87d6235e-3a3d-4a93-aa38-9451ca3b6420',
  },
  {
      nor: 'ujevn',
      eng: 'uneven',
      pl: 'nierówny',
      ar: 'غير مستو',
      ger: 'unregelmäßig',
      lt: 'nelygus',
      ua: 'нерівний',
      sp: 'desigual',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fujevn.mp3?alt=media&token=a6c8189e-1d9b-46c2-af68-2246206bb5e8',
  },
  {
      nor: 'lokal',
      eng: 'local',
      pl: 'lokalny',
      ar: 'محلي',
      ger: 'lokal',
      lt: 'vietinis',
      ua: 'місцевий',
      sp: 'local'
  },
  {
      nor: 'unødvendig',
      eng: 'unnecessary',
      pl: 'niepotrzebny',
      ar: 'غير ضروري',
      ger: 'unnötig',
      lt: 'nereikalingas',
      ua: 'непотрібний',
      sp: 'innecesario'
  },
  {
      nor: 'frisk',
      eng: 'fresh',
      pl: 'świeży',
      ar: 'طازج',
      ger: 'frisch',
      lt: 'šviežias',
      ua: 'свіжий',
      sp: 'fresco'
  },
  {
      nor: 'stille',
      eng: 'quiet',
      pl: 'cichy',
      ar: 'هادئ',
      ger: 'ruhig',
      lt: 'tylus',
      ua: 'тихо',
      sp: 'tranquilo'
  },
  {
    nor: 'gjerrig',
    eng: 'stingy',
    pl: 'skąpy',
    ar: 'بخيل',
    ger: 'geizig',
    lt: 'šykštus',
    ua: 'скупий',
    sp: 'tacaño'
  },
  {
    nor: 'ydmyk',
    eng: 'humble',
    pl: 'pokorny',
    ar: 'متواضع',
    ger: 'bescheiden',
    lt: 'nusižeminęs',
    ua: 'скромний',
    sp: 'humilde'
  },
  {
    nor: 'uoppmerksom',
    eng: 'inattentive',
    pl: 'nieuważny',
    ar: 'غير منتبه',
    ger: 'unaufmerksam',
    lt: 'neįdėmesingas',
    ua: 'неуважний',
    sp: 'inatento'
  },
  {
    nor: 'hjelpsom',
    eng: 'helpful',
    pl: 'pomocny',
    ar: 'مفيد',
    ger: 'hilfreich',
    lt: 'pagalbinis',
    ua: 'допоможний',
    sp: 'útil'
  },
  {
    nor: 'egoistisk',
    eng: 'selfish',
    pl: 'samolubny',
    ar: 'أناني',
    ger: 'egoistisch',
    lt: 'saviškas',
    ua: 'егоїстичний',
    sp: 'egoísta'
  },
  {
    nor: 'flittig',
    eng: 'diligent',
    pl: 'pracowity',
    ar: 'مجتهد',
    ger: 'fleißig',
    lt: 'diligentas',
    ua: 'прилежний',
    sp: 'diligente'
  },
  {
    nor: 'fornuftig',
    eng: 'sensible',
    pl: 'rozsądny',
    ar: 'عاقل',
    ger: 'vernünftig',
    lt: 'protingas',
    ua: 'розумний',
    sp: 'sensato'
  },
  {
    nor: 'frekk',
    eng: 'cheeky',
    pl: 'bezczelny',
    ar: 'وقح',
    ger: 'frech',
    lt: 'drąsus',
    ua: 'нахабний',
    sp: 'descarado'
  },
  {
    nor: 'frivillig',
    eng: 'voluntary',
    pl: 'dobrowolny',
    ar: 'طوعي',
    ger: 'freiwillig',
    lt: 'savaiminis',
    ua: 'добровільний',
    sp: 'voluntario'
  },
  {
    nor: 'oppmerksom',
    eng: 'attentive',
    pl: 'uważny',
    ar: 'منتبه',
    ger: 'aufmerksam',
    lt: 'dėmesingas',
    ua: 'уважний',
    sp: 'atento'
  },
  {
    nor: 'selvkritisk',
    eng: 'self-critical',
    pl: 'samokrytyczny',
    ar: 'نقدي للنفس',
    ger: 'selbstkritisch',
    lt: 'saviškas',
    ua: 'самокритичний',
    sp: 'autocrítico'
  },
  {
    nor: 'selvgod',
    eng: 'smug',
    pl: 'próżny',
    ar: 'مغرور',
    ger: 'selbstgefällig',
    lt: 'pasipūtęs',
    ua: 'самовдоволений',
    sp: 'complaciente'
  },
  {
    nor: 'inkompetent',
    eng: 'incompetent',
    pl: 'niekompetentny',
    ar: 'غير كفء',
    ger: 'inkompetent',
    lt: 'nekvalifikuotas',
    ua: 'некомпетентний',
    sp: 'incompetente'
  },
  {
    nor: 'intellektuell',
    eng: 'intellectual',
    pl: 'intelektualny',
    ar: 'فكري',
    ger: 'intellektuell',
    lt: 'intelektualus',
    ua: 'інтелектуальний',
    sp: 'intelectual'
  },
  {
    nor: 'naiv',
    eng: 'naive',
    pl: 'naiwny',
    ar: 'ساذج',
    ger: 'naiv',
    lt: 'naivus',
    ua: 'наївний',
    sp: 'ingenuo'
  },
  {
    nor: 'nøysom',
    eng: 'frugal',
    pl: 'oszczędny',
    ar: 'مقتصد',
    ger: 'genügsam',
    lt: 'tausus',
    ua: 'скромний',
    sp: 'frugal'
  },
  {
    nor: 'snill',
    eng: 'kind',
    pl: 'uprzejmy',
    ar: 'طيب',
    ger: 'liebenswürdig',
    lt: 'malonus',
    ua: 'добрий',
    sp: 'amable'
  },
  {
    nor: 'klok',
    eng: 'wise',
    pl: 'mądry',
    ar: 'حكيم',
    ger: 'weise',
    lt: 'išmintingas',
    ua: 'розумний',
    sp: 'sabio'
  },
  {
    nor: 'sliten',
    eng: 'tired',
    pl: 'zmęczony',
    ar: 'متعب',
    ger: 'müde',
    lt: 'pavargęs',
    ua: 'втомлений',
    sp: 'agotado'
  },
  {
    nor: 'spennende',
    eng: 'exciting',
    pl: 'ekscytujący',
    ar: 'مثير',
    ger: 'aufregend',
    lt: 'įdomus',
    ua: 'захоплюючий',
    sp: 'emocionante'
  },
  {
    nor: 'provoserende',
    eng: 'provocative',
    pl: 'prowokacyjny',
    ar: 'مستفز',
    ger: 'provokativ',
    lt: 'provokuojantis',
    ua: 'провокуючий',
    sp: 'provocativo'
  },
  {
    nor: 'uavhengig',
    eng: 'independent',
    pl: 'niezależny',
    ar: 'مستقل',
    ger: 'unabhängig',
    lt: 'nepriklausomas',
    ua: 'незалежний',
    sp: 'independiente'
  },
  {
    nor: 'underdanig',
    eng: 'submissive',
    pl: 'pokorny',
    ar: 'خاضع',
    ger: 'unterwürfig',
    lt: 'paklusnus',
    ua: 'покірний',
    sp: 'sumiso'
  },
  {
    nor: 'unik',
    eng: 'unique',
    pl: 'unikalny',
    ar: 'فريد',
    ger: 'einzigartig',
    lt: 'unikalus',
    ua: 'унікальний',
    sp: 'único'
  },
  {
    nor: 'matt',
    eng: 'matte',
    pl: 'matowy',
    ar: 'غير لامع',
    ger: 'matt',
    lt: 'matinis',
    ua: 'матовий',
    sp: 'mate'
  },
  {
    nor: 'gjennomsiktig',
    eng: 'transparent',
    pl: 'przezroczysty',
    ar: 'شفاف',
    ger: 'transparent',
    lt: 'permatomas',
    ua: 'прозорий',
    sp: 'transparente'
  },
  {
    nor: 'ugjennomsiktig',
    eng: 'opaque',
    pl: 'nieprzezroczysty',
    ar: 'غير شفاف',
    ger: 'undurchsichtig',
    lt: 'nepermatomas',
    ua: 'непрозорий',
    sp: 'opaco'
  },
  {
    nor: 'fargerik',
    eng: 'colorful',
    pl: 'kolorowy',
    ar: 'ملون',
    ger: 'farbenfroh',
    lt: 'spalvingas',
    ua: 'кольоровий',
    sp: 'colorido'
  }
]