export default dataObj = [
    {
    typeOfScreen: '3',
    correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', '?'],
    wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ', '?', '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
    gapsIndex: [],
    textIndex: [],
    translations: {
        eng: 'Choose good anwer out of two from data base type 3',
        pl: 'polskie instrukcje baza danych type 3',
        ar: 'سيارة',
        ger: 'ein Auto type 3',
        lt: 'automobilis type 3',
        ua: 'автомобіль type 3', 
        sp: 'un coche type 3',
    },
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
    translations: {
        eng: 'Tap on the gap and type the correct personal pronoun',
        pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
        ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
        ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
        lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
        ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
        sp: 'Toca el espacio y escribe el pronombre personal correcto.',
    },
    key: 0
   },
   {
    typeOfScreen: '3',
    correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'over'],
    wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'over'],
    gapsIndex: [],
    textIndex: [],
    translations: {
        eng: 'Choose good anwer out of two from data base type 3',
        pl: 'polskie instrukcje baza danych type 3',
        ar: 'سيارة',
        ger: 'ein Auto type 3',
        lt: 'automobilis type 3',
        ua: 'автомобіль type 3', 
        sp: 'un coche type 3',
    },
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
    translations: {
        eng: 'Tap on the gap and type the correct personal pronoun',
        pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
        ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
        ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
        lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
        ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
        sp: 'Toca el espacio y escribe el pronombre personal correcto.',
    },
    key: 1
   },
   {
    typeOfScreen: '3',
    correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
    wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why'],
    gapsIndex: [],
    textIndex: [],
    translations: {
        eng: 'Choose good anwer out of two from data base type 3',
        pl: 'polskie instrukcje baza danych type 3',
        ar: 'سيارة',
        ger: 'ein Auto type 3',
        lt: 'automobilis type 3',
        ua: 'автомобіль type 3', 
        sp: 'un coche type 3',
    },
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
    translations: {
        eng: 'Tap on the gap and type the correct personal pronoun',
        pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
        ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
        ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
        lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
        ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
        sp: 'Toca el espacio y escribe el pronombre personal correcto.',
    },
    key: 2
   },
   {
    typeOfScreen: '3',
    correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
    wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why'],
    gapsIndex: [],
    textIndex: [],
    translations: {
        eng: 'Choose good anwer out of two from data base type 3',
        pl: 'polskie instrukcje baza danych type 3',
        ar: 'سيارة',
        ger: 'ein Auto type 3',
        lt: 'automobilis type 3',
        ua: 'автомобіль type 3', 
        sp: 'un coche type 3',
    },
    soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
    translations: {
        eng: 'Tap on the gap and type the correct personal pronoun',
        pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
        ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
        ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
        lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
        ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
        sp: 'Toca el espacio y escribe el pronombre personal correcto.',
    },
    key: 3
   },
//    {
//     typeOfScreen: '3',
//     correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
//     wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why'],
//     gapsIndex: [],
//     textIndex: [],
//     translations: {
//         eng: 'Choose good anwer out of two from data base type 3',
//         pl: 'polskie instrukcje baza danych type 3',
//         ar: 'سيارة',
//         ger: 'ein Auto type 3',
//         lt: 'automobilis type 3',
//         ua: 'автомобіль type 3', 
//         sp: 'un coche type 3',
//     },
//     soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
//     translations: {
//         eng: 'Tap on the gap and type the correct personal pronoun',
//         pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
//         ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
//         ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
//         lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
//         ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
//         sp: 'Toca el espacio y escribe el pronombre personal correcto.',
//     },
//     key: 4
//    },
//    {
//     typeOfScreen: '3',
//     correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
//     wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why'],
//     gapsIndex: [],
//     textIndex: [],
//     translations: {
//         eng: 'Choose good anwer out of two from data base type 3',
//         pl: 'polskie instrukcje baza danych type 3',
//         ar: 'سيارة',
//         ger: 'ein Auto type 3',
//         lt: 'automobilis type 3',
//         ua: 'автомобіль type 3', 
//         sp: 'un coche type 3',
//     },
//     soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
//     translations: {
//         eng: 'Tap on the gap and type the correct personal pronoun',
//         pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
//         ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
//         ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
//         lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
//         ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
//         sp: 'Toca el espacio y escribe el pronombre personal correcto.',
//     },
//     key: 5
//    },
//    {
//     typeOfScreen: '3',
//     correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
//     wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why'],
//     gapsIndex: [],
//     textIndex: [],
//     translations: {
//         eng: 'Choose good anwer out of two from data base type 3',
//         pl: 'polskie instrukcje baza danych type 3',
//         ar: 'سيارة',
//         ger: 'ein Auto type 3',
//         lt: 'automobilis type 3',
//         ua: 'автомобіль type 3', 
//         sp: 'un coche type 3',
//     },
//     soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
//     translations: {
//         eng: 'Tap on the gap and type the correct personal pronoun',
//         pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
//         ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
//         ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
//         lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
//         ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
//         sp: 'Toca el espacio y escribe el pronombre personal correcto.',
//     },
//     key: 6
//    },
//    {
//     typeOfScreen: '3',
//     correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
//     wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why'],
//     gapsIndex: [],
//     textIndex: [],
//     translations: {
//         eng: 'Choose good anwer out of two from data base type 3',
//         pl: 'polskie instrukcje baza danych type 3',
//         ar: 'سيارة',
//         ger: 'ein Auto type 3',
//         lt: 'automobilis type 3',
//         ua: 'автомобіль type 3', 
//         sp: 'un coche type 3',
//     },
//     soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
//     translations: {
//         eng: 'Tap on the gap and type the correct personal pronoun',
//         pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
//         ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
//         ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
//         lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
//         ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
//         sp: 'Toca el espacio y escribe el pronombre personal correcto.',
//     },
//     key: 7
//    },
//    {
//     typeOfScreen: '3',
//     correctAnswers: ['Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og'],
//     wordsWithGaps: ['          ', '          ', '          ', '          ', '          ', '          ', '          ',  '!!!' , 'var', 'Over', '80%', 'av', 'befolkningen', 'i Norge','bor i', 'byer og', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why', 'when', 'why'],
//     gapsIndex: [],
//     textIndex: [],
//     translations: {
//         eng: 'Choose good anwer out of two from data base type 3',
//         pl: 'polskie instrukcje baza danych type 3',
//         ar: 'سيارة',
//         ger: 'ein Auto type 3',
//         lt: 'automobilis type 3',
//         ua: 'автомобіль type 3', 
//         sp: 'un coche type 3',
//     },
//     soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Faa.mp3?alt=media&token=6dee1799-ea0e-4360-b17c-da923f358f01',
//     translations: {
//         eng: 'Tap on the gap and type the correct personal pronoun',
//         pl: 'Dotknij luki i wpisz odpowiedni zaimek osobowy.',
//         ar: 'اضغط على الفراغ واكتب الضمير الشخصي الصحيح',
//         ger: 'Tippe auf die Lücke und gib das richtige Personalpronomen ein.',
//         lt: 'Paliesk tarpą ir įvesk teisingą asmens įvardį.',
//         ua: 'Торкніться пропуску і введіть правильний особовий займенник.', 
//         sp: 'Toca el espacio y escribe el pronombre personal correcto.',
//     },
//     key: 8
//    },

];




