export default dataObj = [
    {
        typeOfScreen: '3',
        correctAnswers: [
          "Peter", "er", "syk.", "Han", "må", "spise", "frokost", "klokken", "sju", 
          "for", "å", "ta", "medisinen", "riktig.", "Han", "kan", "ikke", "sove", "for", 
          "lenge,", "fordi", "han", "våkner", "av", "smerter.", "Foreldrene", "sier", 
          "at", "han", "skal", "være", "hjemme", "om", "kvelden,", "fordi", "legen", 
          "har", "gitt", "klare", "instrukser.", "Peter", "bør", "også", "unngå", "junk", 
          "food", "hvis", "han", "vil", "bli", "bedre.", "Noen", "ganger", "vil", "han", 
          "absolutt", "smake", "litt", "is,", "selv", "om", "foreldrene", "fraråder", "det."
        ],
        wordsWithGaps: [
          "Peter", "er", "syk.", "Han", 
          "            ", 
          "spise", "frokost", "klokken", "sju", 
          "for", "å", "ta", "medisinen", "riktig.", "Han", 
          "            ", 
          "ikke", "sove", "for", "lenge,", "fordi", "han", 
          "våkner", "av", "smerter.", "Foreldrene", "sier", 
          "at", "han", 
          "            ", 
          "være", "hjemme", "om", "kvelden,", "fordi", "legen", 
          "har", "gitt", "klare", "instrukser.", "Peter", 
          "            ", 
          "også", "unngå", "junk", "food", "hvis", "han", "vil", 
          "bli", "bedre.", "Noen", "ganger", 
          "            ", 
          "han", "absolutt", "smake", "litt", "is,", "selv", 
          "om", "foreldrene", "fraråder", "det.",
          "!!!",
          
          "ma", "vil", "bør", "kan", "skal", "trenger", "må"
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
      },
    {
        typeOfScreen: '3',
        correctAnswers: [
        "Kari", "er", "helt", "tom", "for", "penger,", "så", "hun", "må", 
        "finne", "en", "ekstra", "jobb", "raskt.", "Hun", "kan", "velge", 
        "om", "hun", "vil", "jobbe", "i", "en", "butikk", "eller", "på", 
        "et", "kontor.", "Sjefen", "sier", "at", "hun", "skal", "møte", 
        "presis", "hver", "dag,", "ellers", "blir", "hun", "trukket", 
        "i", "lønn.", "Hun", "bør", "nok", "vurdere", "å", "ta", "et", 
        "kveldskurs", "for", "å", "få", "nye", "ferdigheter.", "Men", 
        "av", "og", "til", "vil", "hun", "bare", "ta", "en", "fridag,", 
        "selv", "om", "hun", "egentlig", "ikke", "har", "råd."
        ],
        wordsWithGaps: [
        "Kari", "er", "helt", "tom", "for", "penger,", "så", "hun", 
        "            ", 
        "finne", "en", "ekstra", "jobb", "raskt.", "Hun", 
        "            ", 
        "velge", "om", "hun", "vil", "jobbe", "i", "en", "butikk", "eller", 
        "på", "et", "kontor.", "Sjefen", "sier", "at", "hun", 
        "            ", 
        "møte", "presis", "hver", "dag,", "ellers", "blir", "hun", 
        "trukket", "i", "lønn.", "Hun", 
        "            ", 
        "nok", "vurdere", "å", "ta", "et", "kveldskurs", "for", "å", 
        "få", "nye", "ferdigheter.", "Men", "av", "og", "til", 
        "            ", 
        "hun", "bare", "ta", "en", "fridag,", "selv", "om", "hun", 
        "egentlig", "ikke", "har", "råd.",
        "!!!",
        
        "bør", "får", "vil", "kan", "må", "ma", "skal", "bor"
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
    },
    {
        typeOfScreen: '3',
        correctAnswers: [
          "Trine", "bor", "på", "en", "øy", "i", "Nord-Norge.",
          "For", "å", "komme", "seg", "til", "skolen", "i", "tide,",
          "hun", "må", "lære", "seg", "å", "ro", "båt", "før", "sommeren.",
          "Hun", "kan", "også", "ta", "ferge", "om", "morgenen,", "men",
          "billetten", "koster", "mye", "penger.",
          "Faren", "sier", "at", "hun", "skal", "møte", "opp", "i", "naustet",
          "hver", "dag", "for", "å", "trene.",
          "For", "å", "lykkes", "med", "roingen,",
          "hun", "bør", "være", "mer", "disiplinert,", "men", "hun", "liker",
          "å", "sove", "lenge.",
          "Av", "og", "til", "vil", "hun", "absolutt", "lage", "frokost",
          "for", "familien,", "men", "hun", "glemmer", "ofte", "tiden."
        ],
        wordsWithGaps: [
          "Trine", "bor", "på", "en", "øy", "i", "Nord-Norge.",
          "For", "å", "komme", "seg", "til", "skolen", "i", "tide,",
          "hun",
          "            ", 
          "lære", "seg", "å", "ro", "båt", "før", "sommeren.",
          "Hun",
          "            ", 
          "også", "ta", "ferge", "om", "morgenen,", "men",
          "billetten", "koster", "mye", "penger.",
          "Faren", "sier", "at", "hun",
          "            ", 
          "møte", "opp", "i", "naustet",
          "hver", "dag", "for", "å", "trene.",
          "For", "å", "lykkes", "med", "roingen,",
          "hun",
          "            ", 
          "være", "mer", "disiplinert,", "men", "hun", "liker",
          "å", "sove", "lenge.",
          "Av", "og", "til",
          "            ", 
          "hun", "absolutt", "lage", "frokost",
          "for", "familien,", "men", "hun", "glemmer", "ofte", "tiden.",
          "!!!",
          "liker", "må", "vill", "kan", "bør", "vil", "skal", "får"
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
      },
      {
        typeOfScreen: '3',
        correctAnswers: [
          "Sara", "har", "akkurat", "flyttet", "til", "en", "ny", "by.",
          "Hun", "må", "registrere", "seg", "hos", "politiet", "før",
          "onsdag.",
          "Hun", "kan", "også", "sende", "inn", "dokumenter", "på",
          "nett,", "men", "er", "usikker", "på", "hvordan.",
          "Moren", "hennes", "sier", "at", "hun", "skal", "gå",
          "personlig", "for", "å", "unngå", "feil.",
          "Sara", "bør", "undersøke", "åpningstidene", "først,",
          "så", "hun", "ikke", "drar", "forgjeves.",
          "Noen", "dager", "vil", "hun", "bare", "bli", "hjemme,",
          "men", "da", "får", "hun", "kanskje", "ikke", "alt",
          "gjort", "i", "tide."
        ],
        wordsWithGaps: [
          "Sara", "har", "akkurat", "flyttet", "til", "en", "ny", "by.",
          "Hun",
          "            ", 
          "registrere", "seg", "hos", "politiet", "før",
          "onsdag.",
          "Hun",
          "            ", 
          "også", "sende", "inn", "dokumenter", "på",
          "nett,", "men", "er", "usikker", "på", "hvordan.",
          "Moren", "hennes", "sier", "at", "hun",
          "            ", 
          "gå", "personlig", "for", "å", "unngå", "feil.",
          "Sara",
          "            ", 
          "undersøke", "åpningstidene", "først,",
          "så", "hun", "ikke", "drar", "forgjeves.",
          "Noen", "dager",
          "            ", 
          "hun", "bare", "bli", "hjemme,",
          "men", "da", "får", "hun", "kanskje", "ikke", "alt",
          "gjort", "i", "tide.",
          "!!!",
          "bor", "kan", "må", "skal", "vil", "bør", "liker", "can"
        ],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
      },
    {
        typeOfScreen: '3',
        correctAnswers: ['De', 'må', 'reise', 'tidlig', 'hvis', 'de', 'vil', 'unngå', 'trafikken.', 'lineBreaker', 'Du', 'kan', 'lære', 'norsk', 'raskt', 'med', 'øvelse', 'og', 'tålmodighet.', 'lineBreaker', 'Han', 'tør', 'ikke', 'å', 'snakke', 'offentlig', 'uten', 'å', 'forberede', 'seg.'],
        wordsWithGaps: ['De', '            ', 'reise', 'tidlig', 'hvis', 'de', '            ', 'unngå', 'trafikken.', 'lineBreaker', 'Du', '            ', 'lære', 'norsk', 'raskt', 'med', 'øvelse', 'og', 'tålmodighet.', 'lineBreaker', 'Han', '            ', 'ikke', 'å', 'snakke', 'offentlig', 'uten', 'å', '            ', 'seg.', '!!!', 'tør', 'forberede', 'vil', 'kan', 'må'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Vi', 'bør', 'spise', 'sunnere', 'for', 'bedre', 'helse.', 'lineBreaker', 'Hun', 'ønsker', 'å', 'kjøpe', 'en', 'ny', 'bil', 'men', 'hun', 'trenger', 'å', 'spare', 'mer', 'penger.', 'lineBreaker', 'De', 'vil', 'se', 'den', 'nye', 'filmen', 'sammen', 'i', 'kveld.'],
        wordsWithGaps: ['Vi', '            ', 'spise', 'sunnere', 'for', 'bedre', 'helse.', 'lineBreaker', 'Hun', 'ønsker', 'å', 'kjøpe', 'en', 'ny', 'bil', 'men', 'hun', '            ', 'å', 'spare', 'mer', 'penger.', 'lineBreaker', 'De', '            ', 'se', 'den', 'nye', 'filmen', 'sammen', 'i', 'kveld.', '!!!', 'trenger', 'vil', 'bør'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
    },
    {
        typeOfScreen: '3',
        correctAnswers: ['Han', 'kan', 'ikke', 'komme', 'i', 'dag', 'fordi', 'han', 'er', 'syk.', 'lineBreaker', 'Hun', 'bør', 'studere', 'mer', 'før', 'eksamenen', 'neste', 'uke.', 'lineBreaker', 'Vi', 'må', 'huske', 'å', 'kjøpe', 'melk', 'når', 'vi', 'er', 'i', 'butikken.'],
        wordsWithGaps: ['Han', '            ', 'ikke', 'komme', 'i', 'dag', 'fordi', 'han', 'er', 'syk.', 'lineBreaker', 'Hun', '            ', 'studere', 'mer', 'før', 'eksamenen', 'neste', 'uke.', 'lineBreaker', 'Vi', '            ', 'huske', 'å', 'kjøpe', 'melk', 'når', 'vi', 'er', 'i', 'butikken.', '!!!', 'må', 'kan', 'bør'],
        gapsIndex: [],
        textIndex: [],
        lineBreaker: []
    }
];