export default dataObj = [
    {
        nor: 'en bil',
        eng: 'a car',
        pl: 'samochód',
        ar: 'سيارة',
        ger: 'ein Auto',
        lt: 'automobilis',
        ua: 'автомобіль', 
        sp: 'un coche',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbil.mp3?alt=media&token=994e0f46-bc52-411f-8614-ed11bea959c8',
      },
      {
        nor: 'et fjell',
        eng: 'a mountain',
        pl: 'góra',
        ar: 'جبل',
        ger: 'ein Berg',
        lt: 'kalnas',
        ua: 'гора', 
        sp: 'una montaña',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffjell.mp3?alt=media&token=ee408a00-a0e7-4d2f-8173-9b20bdefacb0',
      },
      {
        nor: 'en sofa',
        eng: 'a sofa',
        pl: 'sofa',
        ar: 'أريكة',
        ger: 'ein Sofa',
        lt: 'sofa',
        ua: 'диван', 
        sp: 'un sofá',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsofa.mp3?alt=media&token=8799ff44-f022-47d4-b7e8-9719589eb592',
      },
      {
        nor: 'en seng',
        eng: 'a bed',
        pl: 'łóżko',
        ar: 'سرير',
        ger: 'ein Bett',
        lt: 'lova',
        ua: 'ліжко', 
        sp: 'una cama',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fseng.mp3?alt=media&token=fd1d2f96-fdc8-4f56-bf02-c385776ba4b9',
      },
      {
        nor: 'et tre',
        eng: 'a tree',
        pl: 'drzewo',
        ar: 'شجرة',
        ger: 'ein Baum',
        lt: 'medis',
        ua: 'дерево', 
        sp: 'un árbol',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftre.mp3?alt=media&token=d213ef92-6bd5-49cd-8496-acda9ad2a8e3',
      },
      {
        nor: 'en blomst',
        eng: 'a flower',
        pl: 'kwiat',
        ar: 'زهرة',
        ger: 'eine Blume',
        lt: 'gėlė',
        ua: 'квітка', 
        sp: 'una flor',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblomst.mp3?alt=media&token=cc895940-29b4-41c1-8ac8-24b8c5face40',
      },
      {
        nor: 'en kake',
        eng: 'a cake',
        pl: 'ciasto',
        ar: 'كعكة',
        ger: 'ein Kuchen',
        lt: 'tortas',
        ua: 'торт', 
        sp: 'un pastel',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkake.mp3?alt=media&token=e9ccf858-92cd-44e9-acae-042826d58374',
      },
      {
        nor: 'en sykkel',
        eng: 'a bicycle',
        pl: 'rower',
        ar: 'دراجة',
        ger: 'ein Fahrrad',
        lt: 'dviratis',
        ua: 'велосипед', 
        sp: 'una bicicleta',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykkel.mp3?alt=media&token=618c4200-13cb-4745-80f3-12691892cb5f',
      },
      {
        nor: 'en båt',
        eng: 'a boat',
        pl: 'łódź',
        ar: 'قارب',
        ger: 'ein Boot',
        lt: 'valtis',
        ua: 'човен', 
        sp: 'un barco',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbaat.mp3?alt=media&token=6a8777b3-e15c-4b5a-a9c4-6dc26f062284',
      },
      {
        nor: 'en telefon',
        eng: 'a telephone',
        pl: 'telefon',
        ar: 'هاتف',
        ger: 'ein Telefon',
        lt: 'telefonas',
        ua: 'телефон', 
        sp: 'un teléfono',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftelefon.mp3?alt=media&token=4c5dcbeb-a30e-439c-829f-77191c8fb202',
      },
      {
        nor: 'en avis',
        eng: 'a newspaper',
        pl: 'gazeta',
        ar: 'جريدة',
        ger: 'eine Zeitung',
        lt: 'laikraštis',
        ua: 'газета', 
        sp: 'un periódico',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Favis.mp3?alt=media&token=a99c9bca-c128-4f30-ba97-fd90698ae65a',
      },
      {
        nor: 'et speil',
        eng: 'a mirror',
        pl: 'lustro',
        ar: 'مرآة',
        ger: 'ein Spiegel',
        lt: 'veidrodis',
        ua: 'дзеркало', 
        sp: 'un espejo',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fspeil.mp3?alt=media&token=860c19b1-9c72-44d9-8fc8-83076af5d7a5',
      },
      {
        nor: 'en venn',
        eng: 'a friend',
        pl: 'przyjaciel',
        ar: 'صديق',
        ger: 'ein Freund',
        lt: 'draugas',
        ua: 'друг', 
        sp: 'un amigo',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvenn.mp3?alt=media&token=177a17bc-3293-495a-b53f-e50e6a072f77',
      },
      {
        nor: 'en jente',
        eng: 'a girl',
        pl: 'dziewczyna',
        ar: 'فتاة',
        ger: 'ein Mädchen',
        lt: 'mergaitė',
        ua: 'дівчина', 
        sp: 'una chica',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjente.mp3?alt=media&token=2f35c7b7-c3dc-4210-b3fb-071e77f467c0',
      },
      {
        nor: 'en gutt',
        eng: 'a boy',
        pl: 'chłopiec',
        ar: 'ولد',
        ger: 'ein Junge',
        lt: 'berniukas',
        ua: 'хлопець', 
        sp: 'un chico',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgutt.mp3?alt=media&token=afc817af-2488-4810-adc9-ff8a0db1b2e0',
      },
      {
        nor: 'et barn',
        eng: 'a child',
        pl: 'dziecko',
        ar: 'طفل',
        ger: 'ein Kind',
        lt: 'vaikas',
        ua: 'дитина',
        sp: 'un niño',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbarn.mp3?alt=media&token=75e9e474-3305-4699-b276-8aa25abbbdc1',
      },
      {
        nor: 'en familie',
        eng: 'a family',
        pl: 'rodzina',
        ar: 'عائلة',
        ger: 'eine Familie',
        lt: 'šeima',
        ua: 'сім’я',
        sp: 'una familia',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffamilie.mp3?alt=media&token=456ee8d5-78fe-4967-a73f-f78165b03c68',
      },
      {
        nor: 'et hus',
        eng: 'a house',
        pl: 'dom',
        ar: 'بيت',
        ger: 'ein Haus',
        lt: 'namas',
        ua: 'будинок',
        sp: 'una casa',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhus.mp3?alt=media&token=f42d6cc4-2585-4498-90c9-00393910ee09',
      },
      {
        nor: 'en bok',
        eng: 'a book',
        pl: 'książka',
        ar: 'كتاب',
        ger: 'ein Buch',
        lt: 'knyga',
        ua: 'книга',
        sp: 'un libro',
        soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbok.mp3?alt=media&token=b72147af-c18b-4504-b421-9ae701b02c55',
      },
      {
          nor: 'en stol',
          eng: 'a chair',
          pl: 'krzesło',
          ar: 'كرسي',
          ger: 'ein Stuhl',
          lt: 'kėdė',
          ua: 'стілець',
          sp: 'una silla',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstol.mp3?alt=media&token=d689b1b0-d210-4106-924f-b3fbebd8ca6f',
      },
      {
          nor: 'et bord',
          eng: 'a table',
          pl: 'stół',
          ar: 'طاولة',
          ger: 'ein Tisch',
          lt: 'stalas',
          ua: 'стіл',
          sp: 'una mesa',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbord.mp3?alt=media&token=dc049ce7-478b-4910-bd8d-09ea9badabaf',
      },
      {
          nor: 'en skole',
          eng: 'a school',
          pl: 'szkoła',
          ar: 'مدرسة',
          ger: 'eine Schule',
          lt: 'mokykla',
          ua: 'школа',
          sp: 'una escuela',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskole.mp3?alt=media&token=26087d43-8fb9-465b-b615-b6c8ae9ad63f',
      },
      {
          nor: 'en lærer',
          eng: 'a teacher',
          pl: 'nauczyciel',
          ar: 'معلم',
          ger: 'ein Lehrer',
          lt: 'mokytojas',
          ua: 'вчитель',
          sp: 'un profesor',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fleerer.mp3?alt=media&token=2669dfa8-b1b0-49b6-9857-bb4baf3a8b21',
      },
      {
          nor: 'et eple',
          eng: 'an apple',
          pl: 'jabłko',
          ar: 'تفاحة',
          ger: 'ein Apfel',
          lt: 'obuolys',
          ua: 'яблуко',
          sp: 'una manzana',
          soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feple.mp3?alt=media&token=27062beb-9a12-44e1-9654-3d9ad143701e',
    },
    {
      nor: 'en dør',
      eng: 'a door',
      pl: 'drzwi',
      ar: 'باب',
      ger: 'eine Tür',
      lt: 'durys',
      ua: 'двері',
      sp: 'una puerta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdoor.mp3?alt=media&token=36df259e-d77b-4fbf-b54a-dc52f33b4109',
    },
    {
      nor: 'et vindu',
      eng: 'a window',
      pl: 'okno',
      ar: 'نافذة',
      ger: 'ein Fenster',
      lt: 'langas',
      ua: 'вікно',
      sp: 'una ventana',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvindu.mp3?alt=media&token=612490f2-e675-4a57-af64-66a44182d0ca',
    },
    {
      nor: 'en katt',
      eng: 'a cat',
      pl: 'kot',
      ar: 'قطة',
      ger: 'eine Katze',
      lt: 'katė',
      ua: 'кіт',
      sp: 'un gato',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkatt.mp3?alt=media&token=3193bfa2-904d-4dd8-bcbc-0b9988a5a92f',
    },
    {
      nor: 'en hund',
      eng: 'a dog',
      pl: 'pies',
      ar: 'كلب',
      ger: 'ein Hund',
      lt: 'šuo',
      ua: 'собака',
      sp: 'un perro',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhund.mp3?alt=media&token=6f48901c-fab9-42ba-9c9b-a03a7f38d4dc',
    },
    {
      nor: 'en kopp',
      eng: 'a cup',
      pl: 'filiżanka',
      ar: 'كوب',
      ger: 'eine Tasse',
      lt: 'puodelis',
      ua: 'чашка',
      sp: 'una taza',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkopp.mp3?alt=media&token=2ec52834-17f7-4190-9bc9-582a46032be8',
    },
    {
      nor: 'et glass',
      eng: 'a glass',
      pl: 'szklanka',
      ar: 'كأس',
      ger: 'ein Glas',
      lt: 'stiklinė',
      ua: 'склянка',
      sp: 'un vaso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fglass.mp3?alt=media&token=de4523b9-8065-4297-bfc1-0b220373f696',
    },
    {
      nor: 'en by',
      eng: 'a city',
      pl: 'miasto',
      ar: 'مدينة',
      ger: 'eine Stadt',
      lt: 'miestas',
      ua: 'місто',
      sp: 'una ciudad',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fby.mp3?alt=media&token=cb1c1625-6a96-49f7-9e7f-a382907b668a',
    },
    {
      nor: 'en koffert',
      eng: 'a suitcase',
      pl: 'walizka',
      ar: 'حقيبة',
      ger: 'ein Koffer',
      lt: 'lagaminas',
      ua: 'валіза',
      sp: 'una maleta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkoffert.mp3?alt=media&token=6fd79fb5-3a69-42ae-8cd3-f09d175dbadb',
    },
    {
      nor: 'et skjerf',
      eng: 'a scarf',
      pl: 'szalik',
      ar: 'وشاح',
      ger: 'ein Schal',
      lt: 'šalikas',
      ua: 'шарф',
      sp: 'una bufanda',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjerf.mp3?alt=media&token=d39e3ed2-ca48-4c3e-af0e-f04d78257884',
    },
    {
      nor: 'en jakke',
      eng: 'a jacket',
      pl: 'kurtka',
      ar: 'سترة',
      ger: 'eine Jacke',
      lt: 'striukė',
      ua: 'куртка',
      sp: 'una chaqueta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fjakke.mp3?alt=media&token=c036d7d1-dca5-4679-b925-7e263a098a3a',
    },
    {
      nor: 'et slips',
      eng: 'a tie',
      pl: 'krawat',
      ar: 'ربطة عنق',
      ger: 'eine Krawatte',
      lt: 'kaklaraištis',
      ua: 'краватка',
      sp: 'una corbata',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslips.mp3?alt=media&token=f9278413-be68-4945-8839-9c49788d30cf',
    },
    {
      nor: 'en paraply',
      eng: 'an umbrella',
      pl: 'parasolka',
      ar: 'مظلة',
      ger: 'ein Regenschirm',
      lt: 'skėtis',
      ua: 'парасолька',
      sp: 'un paraguas',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fparaply.mp3?alt=media&token=4db699c6-4d18-4330-b318-31b57bb862b0',
    },
    {
      nor: 'en stjerne',
      eng: 'a star',
      pl: 'gwiazda',
      ar: 'نجمة',
      ger: 'ein Stern',
      lt: 'žvaigždė',
      ua: 'зірка',
      sp: 'una estrella',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstjerne.mp3?alt=media&token=658afd58-c05a-46e6-a299-a39bc021286a',
    },
    {
      nor: 'en måne',
      eng: 'a moon',
      pl: 'księżyc',
      ar: 'قمر',
      ger: 'ein Mond',
      lt: 'mėnulis',
      ua: 'місяць',
      sp: 'una luna',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaane.mp3?alt=media&token=74bec971-f5c8-4874-b4d9-1b59be842758',
    },
    {
      nor: 'en sol',
      eng: 'a sun',
      pl: 'słońce',
      ar: 'شمس',
      ger: 'eine Sonne',
      lt: 'saulė',
      ua: 'сонце',
      sp: 'un sol',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsol.mp3?alt=media&token=7e481b41-b506-48f1-9237-329f137065b0',
    },
    {
      nor: 'et tårn',
      eng: 'a tower',
      pl: 'wieża',
      ar: 'برج',
      ger: 'ein Turm',
      lt: 'bokštas',
      ua: 'вежа',
      sp: 'una torre',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftaarn.mp3?alt=media&token=646012dd-7373-47b6-ac34-1eedfe9fa077',
    },
    {
      nor: 'en gate',
      eng: 'a street',
      pl: 'ulica',
      ar: 'شارع',
      ger: 'eine Straße',
      lt: 'gatvė',
      ua: 'вулиця',
      sp: 'una calle',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgate.mp3?alt=media&token=56414b0c-b540-4edc-bd11-e4870a89787d',
    },
    {
      nor: 'en bro',
      eng: 'a bridge',
      pl: 'most',
      ar: 'جسر',
      ger: 'eine Brücke',
      lt: 'tiltas',
      ua: 'міст',
      sp: 'un puente',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbro.mp3?alt=media&token=125c8f61-8e4e-43c6-b042-eb6fe562fe00',
    },
    {
      nor: 'et slott',
      eng: 'a castle',
      pl: 'zamek',
      ar: 'قلعة',
      ger: 'ein Schloss',
      lt: 'pilis',
      ua: 'замок',
      sp: 'un castillo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fslott.mp3?alt=media&token=419064cb-a84b-4352-8cd7-5b047b9dbd0b',
    },
    {
      nor: 'en skriver',
      eng: 'a printer',
      pl: 'drukarka',
      ar: 'طابعة',
      ger: 'ein Drucker',
      lt: 'spausdintuvas',
      ua: 'принтер',
      sp: 'una impresora',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskriver.mp3?alt=media&token=a55f6d91-50ab-4d39-82f6-0a70c2b2a33d',
    },
    {
      nor: 'en hatt',
      eng: 'a hat',
      pl: 'kapelusz',
      ar: 'قبعة',
      ger: 'ein Hut',
      lt: 'šešėlis',
      ua: 'капелюх',
      sp: 'un sombrero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhatt.mp3?alt=media&token=d64f2373-7f43-4de4-be5a-e548ac089742',
    },
    {
      nor: 'en lommebok',
      eng: 'a wallet',
      pl: 'portfel',
      ar: 'محفظة',
      ger: 'eine Brieftasche',
      lt: 'piniginė',
      ua: 'гаманець',
      sp: 'una cartera',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flommebok.mp3?alt=media&token=b9ce92b1-57b9-4190-b2bb-6c1d5a36efb6',
    },
    {
      nor: 'et belte',
      eng: 'a belt',
      pl: 'pasek',
      ar: 'حزام',
      ger: 'ein Gürtel',
      lt: 'diržas',
      ua: 'ремінь',
      sp: 'un cinturón',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbelte.mp3?alt=media&token=d8460c4a-2e10-450b-8d76-3f3a1a56296f',
    },
    {
      nor: 'en nøkkel',
      eng: 'a key',
      pl: 'klucz',
      ar: 'مفتاح',
      ger: 'ein Schlüssel',
      lt: 'raktas',
      ua: 'ключ',
      sp: 'una llave',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnookkel.mp3?alt=media&token=423ba0f5-35b7-4ac5-b6d6-ab0c3b1fb206',
    },
    {
      nor: 'et bilde',
      eng: 'a picture',
      pl: 'obraz',
      ar: 'صورة',
      ger: 'ein Bild',
      lt: 'nuotrauka',
      ua: 'зображення',
      sp: 'una imagen',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbilde.mp3?alt=media&token=ae5ba1d4-3036-4118-9b8a-45f01795bc95',
    },
    {
      nor: 'en klokke',
      eng: 'a watch',
      pl: 'zegarek',
      ar: 'ساعة',
      ger: 'eine Uhr',
      lt: 'laikrodis',
      ua: 'годинник',
      sp: 'un reloj',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fklokke.mp3?alt=media&token=67bbfa12-b0c8-49a2-995f-aff52101dbde',
    },
    {
      nor: 'et armbånd',
      eng: 'a bracelet',
      pl: 'bransoletka',
      ar: 'سوار',
      ger: 'ein Armband',
      lt: 'apyrankė',
      ua: 'браслет',
      sp: 'una pulsera',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Farmbaand.mp3?alt=media&token=1849789b-0965-4dd1-8867-727904578216',
    },
    {
      nor: 'en fisk',
      eng: 'a fish',
      pl: 'ryba',
      ar: 'سمكة',
      ger: 'ein Fisch',
      lt: 'žuvis',
      ua: 'риба',
      sp: 'un pez',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffisk.mp3?alt=media&token=85300cf5-9272-4509-8e18-f4b3063e7372',
    },
    {
      nor: 'en fugl',
      eng: 'a bird',
      pl: 'ptak',
      ar: 'طائر',
      ger: 'ein Vogel',
      lt: 'paukštis',
      ua: 'птах',
      sp: 'un pájaro',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffull.mp3?alt=media&token=857adffc-1615-43c2-8250-80ef4aaeb2bc',
    },
    {
      nor: 'en park',
      eng: 'a park',
      pl: 'park',
      ar: 'حديقة',
      ger: 'ein Park',
      lt: 'parkas',
      ua: 'парк',
      sp: 'un parque',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpark.mp3?alt=media&token=5bff62ee-6eca-402c-8169-297973de32c8',
    },
    {
      nor: 'en sko',
      eng: 'a shoe',
      pl: 'but',
      ar: 'حذاء',
      ger: 'ein Schuh',
      lt: 'batai',
      ua: 'взуття',
      sp: 'un zapato',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsko.mp3?alt=media&token=f0e60576-07a0-4b09-aa69-dd3ed55c6c68',
    },
    {
      nor: 'et tog',
      eng: 'a train',
      pl: 'pociąg',
      ar: 'قطار',
      ger: 'ein Zug',
      lt: 'traukinys',
      ua: 'потяг',
      sp: 'un tren',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftog.mp3?alt=media&token=c5c2a835-5bda-41f2-b538-ff9b9e81863a',
    },
    {
      nor: 'et fly',
      eng: 'a plane',
      pl: 'samolot',
      ar: 'طائرة',
      ger: 'ein Flugzeug',
      lt: 'lėktuvas',
      ua: 'літак',
      sp: 'un avión',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffly.mp3?alt=media&token=cf5367d8-d071-46d2-9bbd-589b44327020',
    },
    {
      nor: 'en mobiltelefon',
      eng: 'a mobile phone',
      pl: 'telefon komórkowy',
      ar: 'هاتف محمول',
      ger: 'ein Mobiltelefon',
      lt: 'mobilusis telefonas',
      ua: 'мобільний телефон',
      sp: 'un teléfono móvil',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmobiltelefon.mp3?alt=media&token=0801578c-dc8a-48aa-9afe-aaf6343423f2',
    },
    {
      nor: 'et nettbrett',
      eng: 'a tablet',
      pl: 'tablet',
      ar: 'جهاز لوحي',
      ger: 'ein Tablet',
      lt: 'planšetė',
      ua: 'планшет',
      sp: 'una tableta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnettbrett.mp3?alt=media&token=a311c65c-9b6b-4843-a72d-6fcc7dc86d05',
    },
    {
      nor: 'en øyeblikk',
      eng: 'a moment',
      pl: 'chwila',
      ar: 'لحظة',
      ger: 'ein Moment',
      lt: 'akimirka',
      ua: 'мить',
      sp: 'un momento',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fooyeblikk.mp3?alt=media&token=447599d6-9758-441f-b50b-c596873b9e4f',
    },
    {
      nor: 'en film',
      eng: 'a movie',
      pl: 'film',
      ar: 'فيلم',
      ger: 'ein Film',
      lt: 'filmas',
      ua: 'фільм',
      sp: 'una película',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffilm.mp3?alt=media&token=4fe25c9f-25fc-4710-aca5-b780587d83aa',
    },
    {
      nor: 'en øy',
      eng: 'an island',
      pl: 'wyspa',
      ar: 'جزيرة',
      ger: 'eine Insel',
      lt: 'sala',
      ua: 'острів',
      sp: 'una isla',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fooy.mp3?alt=media&token=f5529a4c-31bf-4265-ba5c-e9eff5f538b8',
    },
    {
      nor: 'en elv',
      eng: 'a river',
      pl: 'rzeka',
      ar: 'نهر',
      ger: 'ein Fluss',
      lt: 'upė',
      ua: 'ріка',
      sp: 'un río',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felv.mp3?alt=media&token=addbfe5e-741d-4ce3-8254-c0d249a63e94',
    },
    {
      nor: 'et hav',
      eng: 'a sea',
      pl: 'morze',
      ar: 'بحر',
      ger: 'ein Meer',
      lt: 'jūra',
      ua: 'море',
      sp: 'un mar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhav.mp3?alt=media&token=97566159-0e84-4a68-8cd8-b650a5b2e3c7',
    },
    {
      nor: 'en innsjø',
      eng: 'a lake',
      pl: 'jezioro',
      ar: 'بحيرة',
      ger: 'ein See',
      lt: 'ežeras',
      ua: 'озеро',
      sp: 'un lago',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finnsjoo.mp3?alt=media&token=afef4c5a-b44e-4fa4-8d49-04228e514a06',
    },
    {
      nor: 'en skog',
      eng: 'a forest',
      pl: 'las',
      ar: 'غابة',
      ger: 'ein Wald',
      lt: 'miškas',
      ua: 'ліс',
      sp: 'un bosque',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskog.mp3?alt=media&token=de379fd4-4115-4afc-9367-2d2dacc1cf83',
    },
    {
      nor: 'en dal',
      eng: 'a valley',
      pl: 'dolina',
      ar: 'وادي',
      ger: 'ein Tal',
      lt: 'slėnis',
      ua: 'долина',
      sp: 'un valle',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdal.mp3?alt=media&token=06d4fab4-101f-4a20-b71d-21a8cef54379',
    },
    {
      nor: 'en butikk',
      eng: 'a store',
      pl: 'sklep',
      ar: 'متجر',
      ger: 'ein Geschäft',
      lt: 'parduotuvė',
      ua: 'магазин',
      sp: 'una tienda',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbutikk.mp3?alt=media&token=876e75f1-f5a2-40c2-a7f0-c6325f4c2d05',
    },
    {
      nor: 'et tastatur',
      eng: 'a keyboard',
      pl: 'klawiatura',
      ar: 'لوحة المفاتيح',
      ger: 'eine Tastatur',
      lt: 'klaviatūra',
      ua: 'принтер',
      sp: 'una impresora',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftastatur.mp3?alt=media&token=1f3a0524-0107-49c0-94b8-330b61d8e773',
    },
    {
      nor: 'et sykehus',
      eng: 'a hospital',
      pl: 'szpital',
      ar: 'مستشفى',
      ger: 'ein Krankenhaus',
      lt: 'ligoninė',
      ua: 'лікарня',
      sp: 'un hospital',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykehus.mp3?alt=media&token=dcbf2629-08e6-4181-ad13-9e3a3b2e3086',
    },
    {
      nor: 'en brannstasjon',
      eng: 'a fire station',
      pl: 'straż pożarna',
      ar: 'محطة الإطفاء',
      ger: 'eine Feuerwache',
      lt: 'gaisrinė',
      ua: 'пожежна станція',
      sp: 'una estación de bomberos',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrannstasjon.mp3?alt=media&token=b744063e-2dde-4a7e-b217-1542389248d6',
    },
    {
      nor: 'en politistasjon',
      eng: 'a police station',
      pl: 'komisariat policji',
      ar: 'مركز شرطة',
      ger: 'eine Polizeistation',
      lt: 'policijos nuovada',
      ua: 'поліцейський відділок',
      sp: 'una estación de policía',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpolitistasjon.mp3?alt=media&token=02f571c3-0401-45fc-a01f-9dd43f0cfe7f',
    },
    {
      nor: 'et bibliotek',
      eng: 'a library',
      pl: 'biblioteka',
      ar: 'مكتبة',
      ger: 'eine Bibliothek',
      lt: 'biblioteka',
      ua: 'бібліотека',
      sp: 'una biblioteca',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbibliotek.mp3?alt=media&token=d49d6028-fd94-49c9-8b51-b9f522ef7076',
    },
    {
      nor: 'en bank',
      eng: 'a bank',
      pl: 'bank',
      ar: 'بنك',
      ger: 'eine Bank',
      lt: 'bankas',
      ua: 'банк',
      sp: 'un banco',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbank.mp3?alt=media&token=1abca584-a8a4-40d1-90a7-b7743e3b2a30',
    },
    {
      nor: 'en kirke',
      eng: 'a church',
      pl: 'kościół',
      ar: 'كنيسة',
      ger: 'eine Kirche',
      lt: 'bažnyčia',
      ua: 'церква',
      sp: 'una iglesia',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkirke.mp3?alt=media&token=eaae606f-9a2c-4e42-bf8a-78101c452a2d',
    },
    {
      nor: 'en blyant',
      eng: 'a pencil',
      pl: 'ołówek',
      ar: 'قلم رصاص',
      ger: 'ein Bleistift',
      lt: 'pieštukas',
      ua: 'олівець',
      sp: 'un lápiz',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fblyant.mp3?alt=media&token=9c4e80df-737e-40f3-bdcb-f0ea438c87a1',
    },
    {
      nor: 'et viskelær',
      eng: 'an eraser',
      pl: 'gumka do ścierania',
      ar: 'ممحاة',
      ger: 'ein Radiergummi',
      lt: 'trintukas',
      ua: 'гумка',
      sp: 'una goma de borrar',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fviskeleer.mp3?alt=media&token=e37a25a4-9061-4363-8073-2cd2aaaf7168',
    },
    {
      nor: 'en penn',
      eng: 'a pen',
      pl: 'długopis',
      ar: 'قلم',
      ger: 'ein Stift',
      lt: 'rašiklis',
      ua: 'ручка',
      sp: 'una pluma',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpenn.mp3?alt=media&token=f24e9bc5-e4b9-411b-b0cd-22fabc97b267',
    },
    {
      nor: 'en notatbok',
      eng: 'a notebook',
      pl: 'notes',
      ar: 'دفتر الملاحظات',
      ger: 'ein Notizbuch',
      lt: 'užrašų knyga',
      ua: 'зошит',
      sp: 'un cuaderno',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fnotatbok.mp3?alt=media&token=aba446aa-3845-4db4-949b-213994d42a2f',
    },
    {
      nor: 'en tegning',
      eng: 'a drawing',
      pl: 'rysunek',
      ar: 'رسم',
      ger: 'eine Zeichnung',
      lt: 'piešinys',
      ua: 'малюнок',
      sp: 'un dibujo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftegning.mp3?alt=media&token=6189a861-b4d4-4da4-a613-5999ef5151f0',
    },
    {
      nor: 'en maling',
      eng: 'a painting',
      pl: 'obraz',
      ar: 'لوحة',
      ger: 'ein Gemälde',
      lt: 'tapyba',
      ua: 'фарбування',
      sp: 'una pintura',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaling.mp3?alt=media&token=f8c690be-a208-4a00-889e-287c2ad808ad',
    },
    {
      nor: 'en matlaging',
      eng: 'cooking',
      pl: 'gotowanie',
      ar: 'طبخ',
      ger: 'Kochen',
      lt: 'virtuvė',
      ua: 'готування їжі',
      sp: 'una cocina',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmatlaging.mp3?alt=media&token=ac8f0968-c5c5-415f-a607-6d33d89bcb8e',
    },
    {
      nor: 'en vinter',
      eng: 'a winter',
      pl: 'zima',
      ar: 'شتاء',
      ger: 'ein Winter',
      lt: 'žiema',
      ua: 'зима',
      sp: 'un invierno',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvinter.mp3?alt=media&token=b50b1f6e-6fe8-4948-962b-5bdb3ebce6de',
    },
    {
      nor: 'en vår',
      eng: 'a spring',
      pl: 'wiosna',
      ar: 'ربيع',
      ger: 'ein Frühling',
      lt: 'pavasaris',
      ua: 'весна',
      sp: 'una primavera',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvaar.mp3?alt=media&token=7ebdbddf-eac2-4ca8-b83a-c969224d8f0b',
    },
    {
      nor: 'en sommer',
      eng: 'a summer',
      pl: 'lato',
      ar: 'صيف',
      ger: 'ein Sommer',
      lt: 'vasara',
      ua: 'літо',
      sp: 'un verano',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsommer.mp3?alt=media&token=7bfe5ef7-1580-49b0-afd7-11495c61adb3',
    },
    {
      nor: 'en utdanning',
      eng: 'an education',
      pl: 'edukacja',
      ar: 'تعليم',
      ger: 'eine Bildung',
      lt: 'švietimas',
      ua: 'освіта',
      sp: 'una educación',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futdanning.mp3?alt=media&token=f09fd3fb-0fff-47d9-9cae-53332ed0297d',
    },
    {
      nor: 'en karakter',
      eng: 'a character',
      pl: 'postać',
      ar: 'شخصية',
      ger: 'eine Figur',
      lt: 'personažas',
      ua: 'характер',
      sp: 'un personaje',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkarakter.mp3?alt=media&token=b9d2b16b-9d96-4015-abed-bc64b11f6ed9',
    },
    {
      nor: 'en elg',
      eng: 'a moose',
      pl: 'łoś',
      ar: 'موظ',
      ger: 'ein Elch',
      lt: 'briedis',
      ua: 'лось',
      sp: 'un alce',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felg.mp3?alt=media&token=0a9e420c-07b2-420a-8d8e-bc58fbffecad',
    },
    {
      nor: 'et brev',
      eng: 'a letter',
      pl: 'list',
      ar: 'خطاب',
      ger: 'ein Brief',
      lt: 'laiškas',
      ua: 'лист',
      sp: 'una carta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbrev.mp3?alt=media&token=00cf842f-99ad-4383-a0e2-6a3ee46e7eb3',
    },
    {
      nor: 'en krukke',
      eng: 'a jar',
      pl: 'słoik',
      ar: 'جرة',
      ger: 'ein Glas',
      lt: 'indelis',
      ua: 'горщик',
      sp: 'un tarro',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkrukke.mp3?alt=media&token=14482db3-ad89-462f-b637-fc009d0f4fcf',
    },
    {
      nor: 'en bensinstasjon',
      eng: 'a gas station',
      pl: 'stacja benzynowa',
      ar: 'محطة وقود',
      ger: 'eine Tankstelle',
      lt: 'degalinė',
      ua: 'бензозаправна станція',
      sp: 'una estación de gasolina',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbensinstasjon.mp3?alt=media&token=4b129f39-f17d-42f4-8efc-3f00119b885c',
    },
    {
      nor: 'en fabrikk',
      eng: 'a factory',
      pl: 'fabryka',
      ar: 'مصنع',
      ger: 'eine Fabrik',
      lt: 'fabrikas',
      ua: 'фабрика',
      sp: 'una fábrica',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffabrikk.mp3?alt=media&token=e0d536f4-ba0c-4e57-911b-54544a063446',
    },
    {
      nor: 'et bakeri',
      eng: 'a bakery',
      pl: 'piekarnia',
      ar: 'مخبز',
      ger: 'eine Bäckerei',
      lt: 'kepykla',
      ua: 'пекарня',
      sp: 'una panadería',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbakeri.mp3?alt=media&token=f298c058-5b84-44d8-b8cc-2a0403b2cd78',
    },
    {
      nor: 'en frisør',
      eng: 'a hairdresser',
      pl: 'fryzjer',
      ar: 'مصفف شعر',
      ger: 'ein Friseur',
      lt: 'kirpėjas',
      ua: 'перукар',
      sp: 'un peluquero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrisoor.mp3?alt=media&token=7e9c74e7-b260-4941-b7c6-645c957d1860',
    },
    {
      nor: 'en maler',
      eng: 'a painter',
      pl: 'malarz',
      ar: 'رسام',
      ger: 'ein Maler',
      lt: 'dažytojas',
      ua: 'художник',
      sp: 'un pintor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmaler.mp3?alt=media&token=8a7b2453-c831-46a7-9eed-6b83d9d3bea6',
    },
    {
      nor: 'en elektriker',
      eng: 'an electrician',
      pl: 'elektryk',
      ar: 'كهربائي',
      ger: 'ein Elektriker',
      lt: 'elektrikas',
      ua: 'електрик',
      sp: 'un electricista',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Felektriker.mp3?alt=media&token=c3ee37fd-f06c-4b18-8846-2960e10ba3c8',
    },
    {
      nor: 'en tunnel',
      eng: 'a tunnel',
      pl: 'tunel',
      ar: 'نفق',
      ger: 'ein Tunnel',
      lt: 'tunelis',
      ua: 'тунель',
      sp: 'un túnel',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftunnel.mp3?alt=media&token=b249e6f8-0ddf-4e9f-82b1-529482433c06',
    },
    {
      nor: 'en frukt',
      eng: 'a fruit',
      pl: 'owoc',
      ar: 'فاكهة',
      ger: 'eine Frucht',
      lt: 'vaisius',
      ua: 'фрукт',
      sp: 'una fruta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffrukt.mp3?alt=media&token=a005d771-67f5-438b-a05b-d96404e5b07e',
    },
    {
      nor: 'en grønnsak',
      eng: 'a vegetable',
      pl: 'warzywo',
      ar: 'خضروات',
      ger: 'ein Gemüse',
      lt: 'daržovė',
      ua: 'овоч',
      sp: 'una verdura',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgroonnsak.mp3?alt=media&token=6cfbe3dd-4ca8-4808-b478-817d318f1792',
    },
    {
      nor: 'en passasjer',
      eng: 'a passenger',
      pl: 'pasażer',
      ar: 'راكب',
      ger: 'ein Fahrgast',
      lt: 'keleivis',
      ua: 'пасажир',
      sp: 'un pasajero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpassasjer.mp3?alt=media&token=fcda55de-12e8-4caf-832f-40ed1bd28e08',
    },
    {
      nor: 'en sjåfør',
      eng: 'a driver',
      pl: 'kierowca',
      ar: 'سائق',
      ger: 'ein Fahrer',
      lt: 'vairuotojas',
      ua: 'водій',
      sp: 'un conductor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsjaafoor.mp3?alt=media&token=1e4540cd-5d3b-4ae4-b2d8-006619f3a165',
    },
    {
      nor: 'en servitør',
      eng: 'a waiter',
      pl: 'kelner',
      ar: 'نادل',
      ger: 'ein Kellner',
      lt: 'padavėjas',
      ua: 'офіціант',
      sp: 'un camarero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fservitoor.mp3?alt=media&token=3b27f8fb-c168-4f56-9c61-0824649626fb',
    },
    {
      nor: 'en selger',
      eng: 'a seller',
      pl: 'sprzedawca',
      ar: 'بائع',
      ger: 'ein Verkäufer',
      lt: 'pardavėjas',
      ua: 'продавець',
      sp: 'un vendedor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fselger.mp3?alt=media&token=d706ad63-6c30-4021-b0b2-00aa779ced54',
    },
    {
      nor: 'en direktør',
      eng: 'a director',
      pl: 'dyrektor',
      ar: 'مدير',
      ger: 'ein Direktor',
      lt: 'direktorius',
      ua: 'директор',
      sp: 'un director',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdirektoor.mp3?alt=media&token=f0851cc3-7e44-4461-8ec7-57260db61d56',
    },
    {
      nor: 'et skilt',
      eng: 'a sign',
      pl: 'znak',
      ar: 'إشارة',
      ger: 'ein Schild',
      lt: 'ženklas',
      ua: 'знак',
      sp: 'un letrero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskilt.mp3?alt=media&token=7d609bdb-dfe5-41aa-940f-ad21f6faf5b5',
    },
    {
      nor: 'en billett',
      eng: 'a ticket',
      pl: 'bilet',
      ar: 'تذكرة',
      ger: 'ein Ticket',
      lt: 'bilietas',
      ua: 'квиток',
      sp: 'un boleto',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbillett.mp3?alt=media&token=cd6f947a-decc-4fa7-9df6-d390d88040ff',
    },
    {
      nor: 'en lege',
      eng: 'a doctor',
      pl: 'lekarz',
      ar: 'طبيب',
      ger: 'ein Arzt',
      lt: 'gydytojas',
      ua: 'лікар',
      sp: 'un médico',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Flege.mp3?alt=media&token=03abe9fd-661c-425d-9901-b631e2913596',
    },
    {
      nor: 'en heis',
      eng: 'an elevator',
      pl: 'winda',
      ar: 'مصعد',
      ger: 'ein Aufzug',
      lt: 'liftas',
      ua: 'ліфт',
      sp: 'un ascensor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fheis.mp3?alt=media&token=d64fd778-3e97-4738-8445-f8b6285ac8d3',
    },
    {
      nor: 'en trapp',
      eng: 'a staircase',
      pl: 'schody',
      ar: 'درج',
      ger: 'eine Treppe',
      lt: 'laiptai',
      ua: 'сходи',
      sp: 'una escalera',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftrapp.mp3?alt=media&token=809c78f2-8a85-46e8-b608-f1a77d14c913',
    },
    // {
    //   nor: 'en venn',
    //   eng: 'a friend',
    //   pl: 'przyjaciel',
    //   ar: 'صديق',
    //   ger: 'ein Freund',
    //   lt: 'draugas',
    //   ua: 'друг',
    //   sp: 'un amigo'
    // },
    // {
    //   nor: 'en fiende',
    //   eng: 'an enemy',
    //   pl: 'wróg',
    //   ar: 'عدو',
    //   ger: 'ein Feind',
    //   lt: 'priešas',
    //   ua: 'ворог',
    //   sp: 'un enemigo'
    // },
    {
      nor: 'en musiker',
      eng: 'a musician',
      pl: 'muzyk',
      ar: 'موسيقي',
      ger: 'ein Musiker',
      lt: 'muzikantas',
      ua: 'музикант',
      sp: 'un músico',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmusiker.mp3?alt=media&token=f8909e66-25c4-4e33-bf09-c3a03f978254',
    },
    {
      nor: 'en danser',
      eng: 'a dancer',
      pl: 'tancerz',
      ar: 'راقص',
      ger: 'ein Tänzer',
      lt: 'šokėjas',
      ua: 'танцівник',
      sp: 'un bailarín',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdanser.mp3?alt=media&token=29a1d8fd-bdf5-4133-9e6c-9c76fcd97e4c',
    },
    {
      nor: 'en kunstner',
      eng: 'an artist',
      pl: 'artysta',
      ar: 'فنان',
      ger: 'ein Künstler',
      lt: 'menininkas',
      ua: 'художник',
      sp: 'un artista',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkunstner.mp3?alt=media&token=b0eeba0f-5924-4cfc-ade0-36c66d0b5eef',
    },
    {
      nor: 'en reporter',
      eng: 'a reporter',
      pl: 'reporter',
      ar: 'مراسل',
      ger: 'ein Reporter',
      lt: 'reporteris',
      ua: 'репортер',
      sp: 'un reportero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freporter.mp3?alt=media&token=3094ba5f-006b-4879-a7dd-1f98ceecc11b',
    },
    {
      nor: 'en advokat',
      eng: 'a lawyer',
      pl: 'adwokat',
      ar: 'محام',
      ger: 'ein Anwalt',
      lt: 'advokatas',
      ua: 'адвокат',
      sp: 'un abogado',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fadvokat.mp3?alt=media&token=b1e73101-34ae-4068-8f5c-e505a6ad6f35',
    },
    {
      nor: 'en kokk',
      eng: 'a cook',
      pl: 'kucharz',
      ar: 'طباخ',
      ger: 'ein Koch',
      lt: 'virtuvės šefas',
      ua: 'кухар',
      sp: 'un chef',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkokk.mp3?alt=media&token=9e756327-cf7c-49ac-9465-293bebad212b',
    },
    {
      nor: 'et instrument',
      eng: 'an instrument',
      pl: 'instrument',
      ar: 'آلة موسيقية',
      ger: 'ein Instrument',
      lt: 'instrumentas',
      ua: 'інструмент',
      sp: 'un instrumento',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finstrument.mp3?alt=media&token=1c296120-c51a-4045-ab2f-3244b0530f74',
    },
    {
      nor: 'en tromme',
      eng: 'a drum',
      pl: 'bęben',
      ar: 'طبل',
      ger: 'eine Trommel',
      lt: 'būgnas',
      ua: 'барабан',
      sp: 'un tambor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftromme.mp3?alt=media&token=d18193dd-3a54-42d6-a9e4-eea5f4f00d86',
    },
    {
      nor: 'en gitar',
      eng: 'a guitar',
      pl: 'gitara',
      ar: 'جيتار',
      ger: 'eine Gitarre',
      lt: 'gitara',
      ua: 'гітара',
      sp: 'una guitarra',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgitar.mp3?alt=media&token=afd0d9fd-e025-4217-96ad-8bc062f1cda5',
    },
    {
      nor: 'en reservasjon',
      eng: 'a reservation',
      pl: 'rezerwacja',
      ar: 'حجز',
      ger: 'eine Reservierung',
      lt: 'rezervacija',
      ua: 'резервація',
      sp: 'una reserva',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Freservasjon.mp3?alt=media&token=ec06718d-e2ce-4049-aa09-cf622e40589d',
    },
    {
      nor: 'en planet',
      eng: 'a planet',
      pl: 'planeta',
      ar: 'كوكب',
      ger: 'ein Planet',
      lt: 'planeta',
      ua: 'планета',
      sp: 'un planeta',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fplanet.mp3?alt=media&token=eedc4bf5-1839-4782-aa2c-bbfdbd30bb73',
    },
    {
      nor: 'en høst',
      eng: 'an autumn',
      pl: 'jesień',
      ar: 'خريف',
      ger: 'ein Herbst',
      lt: 'ruduo',
      ua: 'осінь',
      sp: 'un otoño',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhoost.mp3?alt=media&token=7570c172-c17b-4ef9-9023-a8c7dd32f95d',
    },
    {
      nor: 'en eksamen',
      eng: 'an exam',
      pl: 'egzamin',
      ar: 'امتحان',
      ger: 'eine Prüfung',
      lt: 'egzaminas',
      ua: 'екзамен',
      sp: 'un examen',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Feksamen.mp3?alt=media&token=b3cbae3c-d66a-4ba9-b3d7-ac33a422033a',
    },
    {
      nor: 'et emne',
      eng: 'a subject',
      pl: 'przedmiot',
      ar: 'موضوع',
      ger: 'ein Fach',
      lt: 'tema',
      ua: 'тема',
      sp: 'un tema',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Femne.mp3?alt=media&token=68cb6b57-62fd-428e-bf94-0e199d21f6fe',
    },
    {
      nor: 'en timeplan',
      eng: 'a schedule',
      pl: 'plan',
      ar: 'جدول',
      ger: 'ein Zeitplan',
      lt: 'tvarkaraštis',
      ua: 'розклад',
      sp: 'un horario',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftimeplan.mp3?alt=media&token=32ed01a5-aebc-4d7b-8eb3-3c947ed2e346',
    },
    {
      nor: 'en pause',
      eng: 'a break',
      pl: 'przerwa',
      ar: 'استراحة',
      ger: 'eine Pause',
      lt: 'pertrauka',
      ua: 'перерва',
      sp: 'un descanso',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fpause.mp3?alt=media&token=28485d18-c103-4eeb-b72a-9da5c9e7c732',
    },
    {
      nor: 'et hjørne',
      eng: 'a corner',
      pl: 'róg',
      ar: 'زاوية',
      ger: 'eine Ecke',
      lt: 'kampas',
      ua: 'кут',
      sp: 'una esquina',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhjoorne.mp3?alt=media&token=4c171ebb-c8c7-4037-844b-8be0a84c1a76',
    },
    {
      nor: 'en vegg',
      eng: 'a wall',
      pl: 'ściana',
      ar: 'جدار',
      ger: 'eine Wand',
      lt: 'siena',
      ua: 'стіна',
      sp: 'una pared',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fvegg.mp3?alt=media&token=ecc41604-29fe-464c-8c19-f9d0d894ad07',
    },
    {
      nor: 'en grense',
      eng: 'a border',
      pl: 'granica',
      ar: 'حدود',
      ger: 'eine Grenze',
      lt: 'siena',
      ua: 'кордон',
      sp: 'una frontera',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgrense.mp3?alt=media&token=6c72d17d-4101-44e7-910c-f701e278f837',
    },
    {
      nor: 'en inngang',
      eng: 'an entrance',
      pl: 'wejście',
      ar: 'مدخل',
      ger: 'ein Eingang',
      lt: 'įėjimas',
      ua: 'вхід',
      sp: 'una entrada',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Finngang.mp3?alt=media&token=7a4688c7-d1aa-4ed1-b9fa-d0f1480f8419',
    },
    {
      nor: 'en utgang',
      eng: 'an exit',
      pl: 'wyjście',
      ar: 'مخرج',
      ger: 'ein Ausgang',
      lt: 'išėjimas',
      ua: 'вихід',
      sp: 'una salida',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Futgang.mp3?alt=media&token=18cf54ef-e4c3-4171-9c3d-31f6453cacd9',
    },
    {
      nor: 'et marked',
      eng: 'a market',
      pl: 'rynek',
      ar: 'سوق',
      ger: 'ein Markt',
      lt: 'turgus',
      ua: 'ринок',
      sp: 'un mercado',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmarked.mp3?alt=media&token=f4f010cb-c29d-491a-a299-341c08c39f95',
    },
    {
      nor: 'en dyrehage',
      eng: 'a zoo',
      pl: 'ogród zoologiczny',
      ar: 'حديقة حيوان',
      ger: 'ein Zoo',
      lt: 'zoologijos sodas',
      ua: 'зоопарк',
      sp: 'un zoológico',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdyrehage.mp3?alt=media&token=967e011a-17e7-489b-917b-d6ae112ae3e4',
    },
    {
      nor: 'en hage',
      eng: 'a garden',
      pl: 'ogród',
      ar: 'حديقة',
      ger: 'ein Garten',
      lt: 'sodas',
      ua: 'сад',
      sp: 'un jardín',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhage.mp3?alt=media&token=eed1b8ec-d204-4c98-88c1-f87bf5ebb776',
    },
    {
      nor: 'en strand',
      eng: 'a beach',
      pl: 'plaża',
      ar: 'شاطئ',
      ger: 'ein Strand',
      lt: 'paplūdimys',
      ua: 'пляж',
      sp: 'una playa',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fstrand.mp3?alt=media&token=1c27bc04-b6d1-4504-8540-8ccefae0f350',
    },
    {
      nor: 'en tallerken',
      eng: 'a plate',
      pl: 'talerz',
      ar: 'طبق',
      ger: 'ein Teller',
      lt: 'lėkštė',
      ua: 'тарілка',
      sp: 'un plato',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftallerken.mp3?alt=media&token=a26013e6-7e97-4c50-8888-00f628ff828c',
    },
    {
      nor: 'en skje',
      eng: 'a spoon',
      pl: 'łyżka',
      ar: 'ملعقة',
      ger: 'ein Löffel',
      lt: 'šaukštas',
      ua: 'ложка',
      sp: 'una cuchara',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskje.mp3?alt=media&token=c920d99e-f2cc-4b3c-a2c7-57c5c8a9baba',
    },
    {
      nor: 'en gaffel',
      eng: 'a fork',
      pl: 'widelec',
      ar: 'شوكة',
      ger: 'eine Gabel',
      lt: 'šakutė',
      ua: 'виделка',
      sp: 'un tenedor',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fgaffel.mp3?alt=media&token=29fb93cc-265a-432a-87d0-f58f4c04ff63',
    },
    {
      nor: 'en kniv',
      eng: 'a knife',
      pl: 'nóż',
      ar: 'سكين',
      ger: 'ein Messer',
      lt: 'peilis',
      ua: 'ніж',
      sp: 'un cuchillo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkniv.mp3?alt=media&token=453abbc5-75bc-46ae-9c84-27f5da6f7f0c',
    },
    {
      nor: 'en regnbue',
      eng: 'a rainbow',
      pl: 'tęcza',
      ar: 'قوس قزح',
      ger: 'ein Regenbogen',
      lt: 'vaivorykštė',
      ua: 'веселка',
      sp: 'un arcoíris',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fregnbue.mp3?alt=media&token=c790d356-9481-43f4-a9ce-b094c7647fbe',
    },
    {
      nor: 'et kart',
      eng: 'a map',
      pl: 'mapa',
      ar: 'خريطة',
      ger: 'eine Karte',
      lt: 'žemėlapis',
      ua: 'карта',
      sp: 'un mapa',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkart.mp3?alt=media&token=352316f8-b198-4201-9aeb-0430f70f0b9e',
    },
    {
      nor: 'et skap',
      eng: 'a cabinet',
      pl: 'szafka',
      ar: 'خزانة',
      ger: 'ein Schrank',
      lt: 'spintelė',
      ua: 'шафа',
      sp: 'un armario',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskap.mp3?alt=media&token=4639e7c8-bb7e-4316-9a3f-a4cab9162346',
    },
    {
      nor: 'en bonde',
      eng: 'a farmer',
      pl: 'rolnik',
      ar: 'مزارع',
      ger: 'ein Bauer',
      lt: 'ūkininkas',
      ua: 'селянин',
      sp: 'un granjero',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbonde.mp3?alt=media&token=4275da58-ef16-4dbe-bf71-f90603eb524d',
    },
    {
      nor: 'en ferie',
      eng: 'a holiday',
      pl: 'wakacje',
      ar: 'عطلة',
      ger: 'ein Urlaub',
      lt: 'atostogos',
      ua: 'відпустка',
      sp: 'unas vacaciones',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fferie.mp3?alt=media&token=d52a232c-ab4a-4384-893e-872f9261c321',
    },
    {
      nor: 'en håndball',
      eng: 'a handball',
      pl: 'piłka ręczna',
      ar: 'كرة اليد',
      ger: 'ein Handball',
      lt: 'rankinis',
      ua: 'гандбол',
      sp: 'un balonmano',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fhaandball.mp3?alt=media&token=039aa2c9-f4b8-4802-a898-4bce896ada33',
    },
    {
      nor: 'en svømming',
      eng: 'a swimming',
      pl: 'pływanie',
      ar: 'سباحة',
      ger: 'ein Schwimmen',
      lt: 'plaukimas',
      ua: 'плавання',
      sp: 'la natación',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsvoomming.mp3?alt=media&token=708e5ff2-4cd8-419b-9294-9f24c20f9c71',
    },
    {
      nor: 'en ski',
      eng: 'a ski',
      pl: 'narta',
      ar: 'تزلج',
      ger: 'ein Ski',
      lt: 'slidinė',
      ua: 'лижі',
      sp: 'unos esquís',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fski.mp3?alt=media&token=ff5ed6c4-ce75-4934-ab40-423fa2fbad6a',
    },
    {
      nor: 'en ishockey',
      eng: 'ice hockey',
      pl: 'hokej na lodzie',
      ar: 'هوكي الجليد',
      ger: 'Eishockey',
      lt: 'ledoritulys',
      ua: 'хокей на льоду',
      sp: 'un hockey sobre hielo',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fishockey.mp3?alt=media&token=7a62965d-effe-4533-b99a-b132ac08425e',
    },
    {
      nor: 'en ryggsekk',
      eng: 'a backpack',
      pl: 'plecak',
      ar: 'حقيبة ظهر',
      ger: 'ein Rucksack',
      lt: 'kuprinė',
      ua: 'рюкзак',
      sp: 'una mochila',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fryggsekk.mp3?alt=media&token=121fc373-5874-4079-84a6-8c04f1ae981e',
    },
    {
      nor: 'et kamera',
      eng: 'a camera',
      pl: 'aparat fotograficzny',
      ar: 'كاميرا',
      ger: 'eine Kamera',
      lt: 'fotoaparatas',
      ua: 'камера',
      sp: 'una cámara',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fkamera.mp3?alt=media&token=2a185902-7054-4c38-a65c-b4d759a16114',
    },
    {
      nor: 'en datamaskin',
      eng: 'a computer',
      pl: 'komputer',
      ar: 'كمبيوتر',
      ger: 'ein Computer',
      lt: 'kompiuteris',
      ua: "комп'ютер",
      sp: 'una computadora',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fdatamaskin.mp3?alt=media&token=7d82bfe6-4c71-4ea3-8c09-9b248dadcae0',
    },
    {
      nor: 'en mus',
      eng: 'a mouse',
      pl: 'mysz',
      ar: 'فأر',
      ger: 'eine Maus',
      lt: 'pelė',
      ua: 'миша',
      sp: 'un ratón',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmus.mp3?alt=media&token=54c7751d-e3ea-4bfe-9bd6-418424172cf0',
    },
    {
      nor: 'en skjerm',
      eng: 'a monitor',
      pl: 'monitor',
      ar: 'شاشة',
      ger: 'ein Monitor',
      lt: 'monitorius',
      ua: 'екран',
      sp: 'una pantalla',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fskjerm.mp3?alt=media&token=b5be5282-a051-43c8-8cbb-04d577086cc8',
    },
    {
      nor: 'en sykepleier',
      eng: 'a nurse',
      pl: 'pielęgniarka',
      ua: 'медсестра',
      ger: 'eine Krankenschwester',
      lt: 'slaugytoja',
      sp: 'una enfermera',
      ar: 'ممرضة',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsykepleier2.mp3?alt=media&token=e3f49374-0be7-4f53-81a6-533605d2f995',
    },
    {
      nor: 'en mor',
      eng: 'a mother',
      pl: 'matka',
      ua: 'мати',
      ger: 'eine Mutter',
      lt: 'motina',
      sp: 'una madre',
      ar: 'أم',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fmoor2.mp3?alt=media&token=ce5dccbe-60a3-4d76-bd22-999e13d2d864',
    },
    {
      nor: 'en baby',
      eng: 'a baby',
      pl: 'niemowlę',
      ua: 'немовля',
      ger: 'ein Baby',
      lt: 'kūdikis',
      sp: 'un bebé',
      ar: 'طفل رضيع',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbaby2.mp3?alt=media&token=40aa865c-a9a9-4165-a24c-f699271531c3',
    },
    {
      nor: 'en bror',
      eng: 'a brother',
      pl: 'brat',
      ua: 'брат',
      ger: 'ein Bruder',
      lt: 'brolis',
      sp: 'un hermano',
      ar: 'أخ',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fbror2.mp3?alt=media&token=13a81c12-4bf4-453e-9d9b-b319fb85927d',
    },
    {
      nor: 'en søster',
      eng: 'a sister',
      pl: 'siostra',
      ua: 'сестра',
      ger: 'eine Schwester',
      lt: 'sesuo',
      sp: 'una hermana',
      ar: 'أخت',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fsooster2.mp3?alt=media&token=8272a241-e811-49db-b038-a5de07c8b34e',
    },
    {
      nor: 'en far',
      eng: 'a father',
      pl: 'ojciec',
      ua: 'батько',
      ger: 'ein Vater',
      lt: 'tėvas',
      sp: 'un padre',
      ar: 'أب',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffar2.mp3?alt=media&token=92491837-f3df-43ab-ae42-742853823459',
    },
    {
      nor: 'en onkel',
      eng: 'an uncle',
      pl: 'wujek',
      ua: 'дядько',
      ger: 'ein Onkel',
      lt: 'dėdė',
      sp: 'un tío',
      ar: 'عم',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Fonkel2.mp3?alt=media&token=dcb9c100-29a4-4d2b-a52a-146158004b1b',
    },
    {
      nor: 'en tante',
      eng: 'an aunt',
      pl: 'ciocia',
      ua: 'тітка',
      ger: 'eine Tante',
      lt: 'teta',
      sp: 'una tía',
      ar: 'عمة',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ftante.mp3?alt=media&token=5cb01c35-94b4-44fc-8df1-39068ca5d219',
    },
    {
      nor: 'en fetter',
      eng: 'a cousin',
      pl: 'kuzyn',
      ua: 'двоюрідний брат',
      ger: 'ein Cousin',
      lt: 'pusbrolis',
      sp: 'un primo',
      ar: 'ابن عم',
      soundLink: 'https://firebasestorage.googleapis.com/v0/b/norapp-69bd4.appspot.com/o/wordsList1%2Ffetter.mp3?alt=media&token=de27652a-a429-48b1-8396-1d1d9b954b16',
    },
]